#include "util/macros.h"

static const char* wa_instr_strings[] = {
    [WA_INSTR_INVALID] = "[invalid instruction]",
    [WA_INSTR_nop] = "nop",
    [WA_INSTR_unreachable] = "unreachable",
    [WA_INSTR_block] = "block",
    [WA_INSTR_loop] = "loop",
    [WA_INSTR_if] = "if",
    [WA_INSTR_else] = "else",
    [WA_INSTR_end] = "end",
    [WA_INSTR_br] = "br",
    [WA_INSTR_br_if] = "br_if",
    [WA_INSTR_br_table] = "br_table",
    [WA_INSTR_return] = "return",
    [WA_INSTR_call] = "call",
    [WA_INSTR_call_indirect] = "call_indirect",
    [WA_INSTR_ref_null] = "ref.null",
    [WA_INSTR_ref_is_null] = "ref.is_null",
    [WA_INSTR_ref_func] = "ref.func",
    [WA_INSTR_drop] = "drop",
    [WA_INSTR_select] = "select",
    [WA_INSTR_select_t] = "select_t",
    [WA_INSTR_local_get] = "local.get",
    [WA_INSTR_local_set] = "local.set",
    [WA_INSTR_local_tee] = "local.tee",
    [WA_INSTR_global_get] = "global.get",
    [WA_INSTR_global_set] = "global.set",
    [WA_INSTR_table_get] = "table.get",
    [WA_INSTR_table_set] = "table.set",
    [WA_INSTR_i32_load] = "i32.load",
    [WA_INSTR_i64_load] = "i64.load",
    [WA_INSTR_f32_load] = "f32.load",
    [WA_INSTR_f64_load] = "f64.load",
    [WA_INSTR_i32_load8_s] = "i32.load8_s",
    [WA_INSTR_i32_load8_u] = "i32.load8_u",
    [WA_INSTR_i32_load16_s] = "i32.load16_s",
    [WA_INSTR_i32_load16_u] = "i32.load16_u",
    [WA_INSTR_i64_load8_s] = "i64.load8_s",
    [WA_INSTR_i64_load8_u] = "i64.load8_u",
    [WA_INSTR_i64_load16_s] = "i64.load16_s",
    [WA_INSTR_i64_load16_u] = "i64.load16_u",
    [WA_INSTR_i64_load32_s] = "i64.load32_s",
    [WA_INSTR_i64_load32_u] = "i64.load32_u",
    [WA_INSTR_i32_store] = "i32.store",
    [WA_INSTR_i64_store] = "i64.store",
    [WA_INSTR_f32_store] = "f32.store",
    [WA_INSTR_f64_store] = "f64.store",
    [WA_INSTR_i32_store8] = "i32.store8",
    [WA_INSTR_i32_store16] = "i32.store16",
    [WA_INSTR_i64_store8] = "i64.store8",
    [WA_INSTR_i64_store16] = "i64.store16",
    [WA_INSTR_i64_store32] = "i64.store32",
    [WA_INSTR_memory_size] = "memory.size",
    [WA_INSTR_memory_grow] = "memory.grow",
    [WA_INSTR_i32_const] = "i32.const",
    [WA_INSTR_i64_const] = "i64.const",
    [WA_INSTR_f32_const] = "f32.const",
    [WA_INSTR_f64_const] = "f64.const",
    [WA_INSTR_i32_eqz] = "i32.eqz",
    [WA_INSTR_i32_eq] = "i32.eq",
    [WA_INSTR_i32_ne] = "i32.ne",
    [WA_INSTR_i32_lt_s] = "i32.lt_s",
    [WA_INSTR_i32_lt_u] = "i32.lt_u",
    [WA_INSTR_i32_gt_s] = "i32.gt_s",
    [WA_INSTR_i32_gt_u] = "i32.gt_u",
    [WA_INSTR_i32_le_s] = "i32.le_s",
    [WA_INSTR_i32_le_u] = "i32.le_u",
    [WA_INSTR_i32_ge_s] = "i32.ge_s",
    [WA_INSTR_i32_ge_u] = "i32.ge_u",
    [WA_INSTR_i64_eqz] = "i64.eqz",
    [WA_INSTR_i64_eq] = "i64.eq",
    [WA_INSTR_i64_ne] = "i64.ne",
    [WA_INSTR_i64_lt_s] = "i64.lt_s",
    [WA_INSTR_i64_lt_u] = "i64.lt_u",
    [WA_INSTR_i64_gt_s] = "i64.gt_s",
    [WA_INSTR_i64_gt_u] = "i64.gt_u",
    [WA_INSTR_i64_le_s] = "i64.le_s",
    [WA_INSTR_i64_le_u] = "i64.le_u",
    [WA_INSTR_i64_ge_s] = "i64.ge_s",
    [WA_INSTR_i64_ge_u] = "i64.ge_u",
    [WA_INSTR_f32_eq] = "f32.eq",
    [WA_INSTR_f32_ne] = "f32.ne",
    [WA_INSTR_f32_lt] = "f32.lt",
    [WA_INSTR_f32_gt] = "f32.gt",
    [WA_INSTR_f32_le] = "f32.le",
    [WA_INSTR_f32_ge] = "f32.ge",
    [WA_INSTR_f64_eq] = "f64.eq",
    [WA_INSTR_f64_ne] = "f64.ne",
    [WA_INSTR_f64_lt] = "f64.lt",
    [WA_INSTR_f64_gt] = "f64.gt",
    [WA_INSTR_f64_le] = "f64.le",
    [WA_INSTR_f64_ge] = "f64.ge",
    [WA_INSTR_i32_clz] = "i32.clz",
    [WA_INSTR_i32_ctz] = "i32.ctz",
    [WA_INSTR_i32_popcnt] = "i32.popcnt",
    [WA_INSTR_i32_add] = "i32.add",
    [WA_INSTR_i32_sub] = "i32.sub",
    [WA_INSTR_i32_mul] = "i32.mul",
    [WA_INSTR_i32_div_s] = "i32.div_s",
    [WA_INSTR_i32_div_u] = "i32.div_u",
    [WA_INSTR_i32_rem_s] = "i32.rem_s",
    [WA_INSTR_i32_rem_u] = "i32.rem_u",
    [WA_INSTR_i32_and] = "i32.and",
    [WA_INSTR_i32_or] = "i32.or",
    [WA_INSTR_i32_xor] = "i32.xor",
    [WA_INSTR_i32_shl] = "i32.shl",
    [WA_INSTR_i32_shr_s] = "i32.shr_s",
    [WA_INSTR_i32_shr_u] = "i32.shr_u",
    [WA_INSTR_i32_rotl] = "i32.rotl",
    [WA_INSTR_i32_rotr] = "i32.rotr",
    [WA_INSTR_i64_clz] = "i64.clz",
    [WA_INSTR_i64_ctz] = "i64.ctz",
    [WA_INSTR_i64_popcnt] = "i64.popcnt",
    [WA_INSTR_i64_add] = "i64.add",
    [WA_INSTR_i64_sub] = "i64.sub",
    [WA_INSTR_i64_mul] = "i64.mul",
    [WA_INSTR_i64_div_s] = "i64.div_s",
    [WA_INSTR_i64_div_u] = "i64.div_u",
    [WA_INSTR_i64_rem_s] = "i64.rem_s",
    [WA_INSTR_i64_rem_u] = "i64.rem_u",
    [WA_INSTR_i64_and] = "i64.and",
    [WA_INSTR_i64_or] = "i64.or",
    [WA_INSTR_i64_xor] = "i64.xor",
    [WA_INSTR_i64_shl] = "i64.shl",
    [WA_INSTR_i64_shr_s] = "i64.shr_s",
    [WA_INSTR_i64_shr_u] = "i64.shr_u",
    [WA_INSTR_i64_rotl] = "i64.rotl",
    [WA_INSTR_i64_rotr] = "i64.rotr",
    [WA_INSTR_f32_abs] = "f32.abs",
    [WA_INSTR_f32_neg] = "f32.neg",
    [WA_INSTR_f32_ceil] = "f32.ceil",
    [WA_INSTR_f32_floor] = "f32.floor",
    [WA_INSTR_f32_trunc] = "f32.trunc",
    [WA_INSTR_f32_nearest] = "f32.nearest",
    [WA_INSTR_f32_sqrt] = "f32.sqrt",
    [WA_INSTR_f32_add] = "f32.add",
    [WA_INSTR_f32_sub] = "f32.sub",
    [WA_INSTR_f32_mul] = "f32.mul",
    [WA_INSTR_f32_div] = "f32.div",
    [WA_INSTR_f32_min] = "f32.min",
    [WA_INSTR_f32_max] = "f32.max",
    [WA_INSTR_f32_copysign] = "f32.copysign",
    [WA_INSTR_f64_abs] = "f64.abs",
    [WA_INSTR_f64_neg] = "f64.neg",
    [WA_INSTR_f64_ceil] = "f64.ceil",
    [WA_INSTR_f64_floor] = "f64.floor",
    [WA_INSTR_f64_trunc] = "f64.trunc",
    [WA_INSTR_f64_nearest] = "f64.nearest",
    [WA_INSTR_f64_sqrt] = "f64.sqrt",
    [WA_INSTR_f64_add] = "f64.add",
    [WA_INSTR_f64_sub] = "f64.sub",
    [WA_INSTR_f64_mul] = "f64.mul",
    [WA_INSTR_f64_div] = "f64.div",
    [WA_INSTR_f64_min] = "f64.min",
    [WA_INSTR_f64_max] = "f64.max",
    [WA_INSTR_f64_copysign] = "f64.copysign",
    [WA_INSTR_i32_wrap_i64] = "i32.wrap_i64",
    [WA_INSTR_i32_trunc_f32_s] = "i32.trunc_f32_s",
    [WA_INSTR_i32_trunc_f32_u] = "i32.trunc_f32_u",
    [WA_INSTR_i32_trunc_f64_s] = "i32.trunc_f64_s",
    [WA_INSTR_i32_trunc_f64_u] = "i32.trunc_f64_u",
    [WA_INSTR_i64_extend_i32_s] = "i64.extend_i32_s",
    [WA_INSTR_i64_extend_i32_u] = "i64.extend_i32_u",
    [WA_INSTR_i64_trunc_f32_s] = "i64.trunc_f32_s",
    [WA_INSTR_i64_trunc_f32_u] = "i64.trunc_f32_u",
    [WA_INSTR_i64_trunc_f64_s] = "i64.trunc_f64_s",
    [WA_INSTR_i64_trunc_f64_u] = "i64.trunc_f64_u",
    [WA_INSTR_f32_convert_i32_s] = "f32.convert_i32_s",
    [WA_INSTR_f32_convert_i32_u] = "f32.convert_i32_u",
    [WA_INSTR_f32_convert_i64_s] = "f32.convert_i64_s",
    [WA_INSTR_f32_convert_i64_u] = "f32.convert_i64_u",
    [WA_INSTR_f32_demote_f64] = "f32.demote_f64",
    [WA_INSTR_f64_convert_i32_s] = "f64.convert_i32_s",
    [WA_INSTR_f64_convert_i32_u] = "f64.convert_i32_u",
    [WA_INSTR_f64_convert_i64_s] = "f64.convert_i64_s",
    [WA_INSTR_f64_convert_i64_u] = "f64.convert_i64_u",
    [WA_INSTR_f64_promote_f32] = "f64.promote_f32",
    [WA_INSTR_i32_reinterpret_f32] = "i32.reinterpret_f32",
    [WA_INSTR_i64_reinterpret_f64] = "i64.reinterpret_f64",
    [WA_INSTR_f32_reinterpret_i32] = "f32.reinterpret_i32",
    [WA_INSTR_f64_reinterpret_i64] = "f64.reinterpret_i64",
    [WA_INSTR_i32_extend8_s] = "i32.extend8_s",
    [WA_INSTR_i32_extend16_s] = "i32.extend16_s",
    [WA_INSTR_i64_extend8_s] = "i64.extend8_s",
    [WA_INSTR_i64_extend16_s] = "i64.extend16_s",
    [WA_INSTR_i64_extend32_s] = "i64.extend32_s",
    [WA_INSTR_table_init] = "table.init",
    [WA_INSTR_elem_drop] = "elem.drop",
    [WA_INSTR_table_copy] = "table.copy",
    [WA_INSTR_table_grow] = "table.grow",
    [WA_INSTR_table_size] = "table.size",
    [WA_INSTR_table_fill] = "table.fill",
    [WA_INSTR_memory_init] = "memory.init",
    [WA_INSTR_data_drop] = "data.drop",
    [WA_INSTR_memory_copy] = "memory.copy",
    [WA_INSTR_memory_fill] = "memory.fill",
    [WA_INSTR_i32_trunc_sat_f32_s] = "i32.trunc_sat_f32_s",
    [WA_INSTR_i32_trunc_sat_f32_u] = "i32.trunc_sat_f32_u",
    [WA_INSTR_i32_trunc_sat_f64_s] = "i32.trunc_sat_f64_s",
    [WA_INSTR_i32_trunc_sat_f64_u] = "i32.trunc_sat_f64_u",
    [WA_INSTR_i64_trunc_sat_f32_s] = "i64.trunc_sat_f32_s",
    [WA_INSTR_i64_trunc_sat_f32_u] = "i64.trunc_sat_f32_u",
    [WA_INSTR_i64_trunc_sat_f64_s] = "i64.trunc_sat_f64_s",
    [WA_INSTR_i64_trunc_sat_f64_u] = "i64.trunc_sat_f64_u",
    [WA_INSTR_v128_load] = "v128.load",
    [WA_INSTR_v128_load8x8_s] = "v128.load8x8_s",
    [WA_INSTR_v128_load8x8_u] = "v128.load8x8_u",
    [WA_INSTR_v128_load16x4_s] = "v128.load16x4_s",
    [WA_INSTR_v128_load16x4_u] = "v128.load16x4_u",
    [WA_INSTR_v128_load32x2_s] = "v128.load32x2_s",
    [WA_INSTR_v128_load32x2_u] = "v128.load32x2_u",
    [WA_INSTR_v128_load8_splat] = "v128.load8_splat",
    [WA_INSTR_v128_load16_splat] = "v128.load16_splat",
    [WA_INSTR_v128_load32_splat] = "v128.load32_splat",
    [WA_INSTR_v128_load64_splat] = "v128.load64_splat",
    [WA_INSTR_v128_store] = "v128.store",
    [WA_INSTR_v128_load32_zero] = "v128.load32_zero",
    [WA_INSTR_v128_load64_zero] = "v128.load64_zero",
    [WA_INSTR_v128_load8_lane] = "v128.load8_lane",
    [WA_INSTR_v128_load16_lane] = "v128.load16_lane",
    [WA_INSTR_v128_load32_lane] = "v128.load32_lane",
    [WA_INSTR_v128_load64_lane] = "v128.load64_lane",
    [WA_INSTR_v128_store8_lane] = "v128.store8_lane",
    [WA_INSTR_v128_store16_lane] = "v128.store16_lane",
    [WA_INSTR_v128_store32_lane] = "v128.store32_lane",
    [WA_INSTR_v128_store64_lane] = "v128.store64_lane",
    [WA_INSTR_v128_const] = "v128.const",
    [WA_INSTR_i8x16_shuffle] = "i8x16.shuffle",
    [WA_INSTR_i8x16_extract_lane_s] = "i8x16.extract_lane_s",
    [WA_INSTR_i8x16_extract_lane_u] = "i8x16.extract_lane_u",
    [WA_INSTR_i8x16_replace_lane] = "i8x16.replace_lane",
    [WA_INSTR_i16x8_extract_lane_s] = "i16x8.extract_lane_s",
    [WA_INSTR_i16x8_extract_lane_u] = "i16x8.extract_lane_u",
    [WA_INSTR_i16x8_replace_lane] = "i16x8.replace_lane",
    [WA_INSTR_i32x4_extract_lane] = "i32x4.extract_lane",
    [WA_INSTR_i32x4_replace_lane] = "i32x4.replace_lane",
    [WA_INSTR_i64x2_extract_lane] = "i64x2.extract_lane",
    [WA_INSTR_i64x2_replace_lane] = "i64x2.replace_lane",
    [WA_INSTR_f32x4_extract_lane] = "f32x4.extract_lane",
    [WA_INSTR_f32x4_replace_lane] = "f32x4.replace_lane",
    [WA_INSTR_f64x2_extract_lane] = "f64x2.extract_lane",
    [WA_INSTR_f64x2_replace_lane] = "f64x2.replace_lane",
    [WA_INSTR_i8x16_swizzle] = "i8x16.swizzle",
    [WA_INSTR_i8x16_splat] = "i8x16.splat",
    [WA_INSTR_i16x8_splat] = "i16x8.splat",
    [WA_INSTR_i32x4_splat] = "i32x4.splat",
    [WA_INSTR_i64x2_splat] = "i64x2.splat",
    [WA_INSTR_f32x4_splat] = "f32x4.splat",
    [WA_INSTR_f64x2_splat] = "f64x2.splat",
    [WA_INSTR_i8x16_eq] = "i8x16.eq",
    [WA_INSTR_i8x16_ne] = "i8x16.ne",
    [WA_INSTR_i8x16_lt_s] = "i8x16.lt_s",
    [WA_INSTR_i8x16_lt_u] = "i8x16.lt_u",
    [WA_INSTR_i8x16_gt_s] = "i8x16.gt_s",
    [WA_INSTR_i8x16_gt_u] = "i8x16.gt_u",
    [WA_INSTR_i8x16_le_s] = "i8x16.le_s",
    [WA_INSTR_i8x16_le_u] = "i8x16.le_u",
    [WA_INSTR_i8x16_ge_s] = "i8x16.ge_s",
    [WA_INSTR_i8x16_ge_u] = "i8x16.ge_u",
    [WA_INSTR_i16x8_eq] = "i16x8.eq",
    [WA_INSTR_i16x8_ne] = "i16x8.ne",
    [WA_INSTR_i16x8_lt_s] = "i16x8.lt_s",
    [WA_INSTR_i16x8_lt_u] = "i16x8.lt_u",
    [WA_INSTR_i16x8_gt_s] = "i16x8.gt_s",
    [WA_INSTR_i16x8_gt_u] = "i16x8.gt_u",
    [WA_INSTR_i16x8_le_s] = "i16x8.le_s",
    [WA_INSTR_i16x8_le_u] = "i16x8.le_u",
    [WA_INSTR_i16x8_ge_s] = "i16x8.ge_s",
    [WA_INSTR_i16x8_ge_u] = "i16x8.ge_u",
    [WA_INSTR_i32x4_eq] = "i32x4.eq",
    [WA_INSTR_i32x4_ne] = "i32x4.ne",
    [WA_INSTR_i32x4_lt_s] = "i32x4.lt_s",
    [WA_INSTR_i32x4_lt_u] = "i32x4.lt_u",
    [WA_INSTR_i32x4_gt_s] = "i32x4.gt_s",
    [WA_INSTR_i32x4_gt_u] = "i32x4.gt_u",
    [WA_INSTR_i32x4_le_s] = "i32x4.le_s",
    [WA_INSTR_i32x4_le_u] = "i32x4.le_u",
    [WA_INSTR_i32x4_ge_s] = "i32x4.ge_s",
    [WA_INSTR_i32x4_ge_u] = "i32x4.ge_u",
    [WA_INSTR_i64x2_eq] = "i64x2.eq",
    [WA_INSTR_i64x2_ne] = "i64x2.ne",
    [WA_INSTR_i64x2_lt_s] = "i64x2.lt_s",
    [WA_INSTR_i64x2_gt_s] = "i64x2.gt_s",
    [WA_INSTR_i64x2_le_s] = "i64x2.le_s",
    [WA_INSTR_i64x2_ge_s] = "i64x2.ge_s",
    [WA_INSTR_f32x4_eq] = "f32x4.eq",
    [WA_INSTR_f32x4_ne] = "f32x4.ne",
    [WA_INSTR_f32x4_lt] = "f32x4.lt",
    [WA_INSTR_f32x4_gt] = "f32x4.gt",
    [WA_INSTR_f32x4_le] = "f32x4.le",
    [WA_INSTR_f32x4_ge] = "f32x4.ge",
    [WA_INSTR_f64x2_eq] = "f64x2.eq",
    [WA_INSTR_f64x2_ne] = "f64x2.ne",
    [WA_INSTR_f64x2_lt] = "f64x2.lt",
    [WA_INSTR_f64x2_gt] = "f64x2.gt",
    [WA_INSTR_f64x2_le] = "f64x2.le",
    [WA_INSTR_f64x2_ge] = "f64x2.ge",
    [WA_INSTR_v128_not] = "v128.not",
    [WA_INSTR_v128_and] = "v128.and",
    [WA_INSTR_v128_andnot] = "v128.andnot",
    [WA_INSTR_v128_or] = "v128.or",
    [WA_INSTR_v128_xor] = "v128.xor",
    [WA_INSTR_v128_bitselect] = "v128.bitselect",
    [WA_INSTR_v128_any_true] = "v128.any_true",
    [WA_INSTR_i8x16_abs] = "i8x16.abs",
    [WA_INSTR_i8x16_neg] = "i8x16.neg",
    [WA_INSTR_i8x16_popcnt] = "i8x16.popcnt",
    [WA_INSTR_i8x16_all_true] = "i8x16.all_true",
    [WA_INSTR_i8x16_bitmask] = "i8x16.bitmask",
    [WA_INSTR_i8x16_narrow_i16x8_s] = "i8x16.narrow_i16x8_s",
    [WA_INSTR_i8x16_narrow_i16x8_u] = "i8x16.narrow_i16x8_u",
    [WA_INSTR_i8x16_shl] = "i8x16.shl",
    [WA_INSTR_i8x16_shr_s] = "i8x16.shr_s",
    [WA_INSTR_i8x16_shr_u] = "i8x16.shr_u",
    [WA_INSTR_i8x16_add] = "i8x16.add",
    [WA_INSTR_i8x16_add_sat_s] = "i8x16.add_sat_s",
    [WA_INSTR_i8x16_add_sat_u] = "i8x16.add_sat_u",
    [WA_INSTR_i8x16_sub] = "i8x16.sub",
    [WA_INSTR_i8x16_sub_sat_s] = "i8x16.sub_sat_s",
    [WA_INSTR_i8x16_sub_sat_u] = "i8x16.sub_sat_u",
    [WA_INSTR_i8x16_min_s] = "i8x16.min_s",
    [WA_INSTR_i8x16_min_u] = "i8x16.min_u",
    [WA_INSTR_i8x16_max_s] = "i8x16.max_s",
    [WA_INSTR_i8x16_max_u] = "i8x16.max_u",
    [WA_INSTR_i8x16_avgr_u] = "i8x16.avgr_u",
    [WA_INSTR_i16x8_extadd_pairwise_i8x16_s] = "i16x8.extadd_pairwise_i8x16_s",
    [WA_INSTR_i16x8_extadd_pairwise_i8x16_u] = "i16x8.extadd_pairwise_i8x16_u",
    [WA_INSTR_i16x8_abs] = "i16x8.abs",
    [WA_INSTR_i16x8_neg] = "i16x8.neg",
    [WA_INSTR_i16x8_q15_mulr_sat_s] = "i16x8.q15_mulr_sat_s",
    [WA_INSTR_i16x8_all_true] = "i16x8.all_true",
    [WA_INSTR_i16x8_bitmask] = "i16x8.bitmask",
    [WA_INSTR_i16x8_narrow_i32x4_s] = "i16x8.narrow_i32x4_s",
    [WA_INSTR_i16x8_narrow_i32x4_u] = "i16x8.narrow_i32x4_u",
    [WA_INSTR_i16x8_extend_low_i8x16_s] = "i16x8.extend_low_i8x16_s",
    [WA_INSTR_i16x8_extend_high_i8x16_s] = "i16x8.extend_high_i8x16_s",
    [WA_INSTR_i16x8_extend_low_i8x16_u] = "i16x8.extend_low_i8x16_u",
    [WA_INSTR_i16x8_extend_high_i8x16_u] = "i16x8.extend_high_i8x16_u",
    [WA_INSTR_i16x8_shl] = "i16x8.shl",
    [WA_INSTR_i16x8_shr_s] = "i16x8.shr_s",
    [WA_INSTR_i16x8_shr_u] = "i16x8.shr_u",
    [WA_INSTR_i16x8_add] = "i16x8.add",
    [WA_INSTR_i16x8_add_sat_s] = "i16x8.add_sat_s",
    [WA_INSTR_i16x8_add_sat_u] = "i16x8.add_sat_u",
    [WA_INSTR_i16x8_sub] = "i16x8.sub",
    [WA_INSTR_i16x8_sub_sat_s] = "i16x8.sub_sat_s",
    [WA_INSTR_i16x8_sub_sat_u] = "i16x8.sub_sat_u",
    [WA_INSTR_i16x8_mul] = "i16x8.mul",
    [WA_INSTR_i16x8_min_s] = "i16x8.min_s",
    [WA_INSTR_i16x8_min_u] = "i16x8.min_u",
    [WA_INSTR_i16x8_max_s] = "i16x8.max_s",
    [WA_INSTR_i16x8_max_u] = "i16x8.max_u",
    [WA_INSTR_i16x8_avgr_u] = "i16x8.avgr_u",
    [WA_INSTR_i16x8_extmul_low_i8x16_s] = "i16x8.extmul_low_i8x16_s",
    [WA_INSTR_i16x8_extmul_high_i8x16_s] = "i16x8.extmul_high_i8x16_s",
    [WA_INSTR_i16x8_extmul_low_i8x16_u] = "i16x8.extmul_low_i8x16_u",
    [WA_INSTR_i16x8_extmul_high_i8x16_u] = "i16x8.extmul_high_i8x16_u",
    [WA_INSTR_i32x4_extadd_pairwise_i16x8_s] = "i32x4.extadd_pairwise_i16x8_s",
    [WA_INSTR_i32x4_extadd_pairwise_i16x8_u] = "i32x4.extadd_pairwise_i16x8_u",
    [WA_INSTR_i32x4_abs] = "i32x4.abs",
    [WA_INSTR_i32x4_neg] = "i32x4.neg",
    [WA_INSTR_i32x4_all_true] = "i32x4.all_true",
    [WA_INSTR_i32x4_bitmask] = "i32x4.bitmask",
    [WA_INSTR_i32x4_extend_low_i16x8_s] = "i32x4.extend_low_i16x8_s",
    [WA_INSTR_i32x4_extend_high_i16x8_s] = "i32x4.extend_high_i16x8_s",
    [WA_INSTR_i32x4_extend_low_i16x8_u] = "i32x4.extend_low_i16x8_u",
    [WA_INSTR_i32x4_extend_high_i16x8_u] = "i32x4.extend_high_i16x8_u",
    [WA_INSTR_i32x4_shl] = "i32x4.shl",
    [WA_INSTR_i32x4_shr_s] = "i32x4.shr_s",
    [WA_INSTR_i32x4_shr_u] = "i32x4.shr_u",
    [WA_INSTR_i32x4_add] = "i32x4.add",
    [WA_INSTR_i32x4_sub] = "i32x4.sub",
    [WA_INSTR_i32x4_mul] = "i32x4.mul",
    [WA_INSTR_i32x4_min_s] = "i32x4.min_s",
    [WA_INSTR_i32x4_min_u] = "i32x4.min_u",
    [WA_INSTR_i32x4_max_s] = "i32x4.max_s",
    [WA_INSTR_i32x4_max_u] = "i32x4.max_u",
    [WA_INSTR_i32x4_dot_i16x8_s] = "i32x4.dot_i16x8_s",
    [WA_INSTR_i32x4_extmul_low_i16x8_s] = "i32x4.extmul_low_i16x8_s",
    [WA_INSTR_i32x4_extmul_high_i16x8_s] = "i32x4.extmul_high_i16x8_s",
    [WA_INSTR_i32x4_extmul_low_i16x8_u] = "i32x4.extmul_low_i16x8_u",
    [WA_INSTR_i32x4_extmul_high_i16x8_u] = "i32x4.extmul_high_i16x8_u",
    [WA_INSTR_i64x2_abs] = "i64x2.abs",
    [WA_INSTR_i64x2_neg] = "i64x2.neg",
    [WA_INSTR_i64x2_all_true] = "i64x2.all_true",
    [WA_INSTR_i64x2_bitmask] = "i64x2.bitmask",
    [WA_INSTR_i64x2_extend_low_i32x4_s] = "i64x2.extend_low_i32x4_s",
    [WA_INSTR_i64x2_extend_high_i32x4_s] = "i64x2.extend_high_i32x4_s",
    [WA_INSTR_i64x2_extend_low_i32x4_u] = "i64x2.extend_low_i32x4_u",
    [WA_INSTR_i64x2_extend_high_i32x4_u] = "i64x2.extend_high_i32x4_u",
    [WA_INSTR_i64x2_shl] = "i64x2.shl",
    [WA_INSTR_i64x2_shr_s] = "i64x2.shr_s",
    [WA_INSTR_i64x2_shr_u] = "i64x2.shr_u",
    [WA_INSTR_i64x2_add] = "i64x2.add",
    [WA_INSTR_i64x2_sub] = "i64x2.sub",
    [WA_INSTR_i64x2_mul] = "i64x2.mul",
    [WA_INSTR_i64x2_extmul_low_i32x4_s] = "i64x2.extmul_low_i32x4_s",
    [WA_INSTR_i64x2_extmul_high_i32x4_s] = "i64x2.extmul_high_i32x4_s",
    [WA_INSTR_i64x2_extmul_low_i32x4_u] = "i64x2.extmul_low_i32x4_u",
    [WA_INSTR_i64x2_extmul_high_i32x4_u] = "i64x2.extmul_high_i32x4_u",
    [WA_INSTR_f32x4_ceil] = "f32x4.ceil",
    [WA_INSTR_f32x4_floor] = "f32x4.floor",
    [WA_INSTR_f32x4_trunc] = "f32x4.trunc",
    [WA_INSTR_f32x4_nearest] = "f32x4.nearest",
    [WA_INSTR_f32x4_abs] = "f32x4.abs",
    [WA_INSTR_f32x4_neg] = "f32x4.neg",
    [WA_INSTR_f32x4_sqrt] = "f32x4.sqrt",
    [WA_INSTR_f32x4_add] = "f32x4.add",
    [WA_INSTR_f32x4_sub] = "f32x4.sub",
    [WA_INSTR_f32x4_mul] = "f32x4.mul",
    [WA_INSTR_f32x4_div] = "f32x4.div",
    [WA_INSTR_f32x4_min] = "f32x4.min",
    [WA_INSTR_f32x4_max] = "f32x4.max",
    [WA_INSTR_f32x4_pmin] = "f32x4.pmin",
    [WA_INSTR_f32x4_pmax] = "f32x4.pmax",
    [WA_INSTR_f64x2_ceil] = "f64x2.ceil",
    [WA_INSTR_f64x2_floor] = "f64x2.floor",
    [WA_INSTR_f64x2_trunc] = "f64x2.trunc",
    [WA_INSTR_f64x2_nearest] = "f64x2.nearest",
    [WA_INSTR_f64x2_abs] = "f64x2.abs",
    [WA_INSTR_f64x2_neg] = "f64x2.neg",
    [WA_INSTR_f64x2_sqrt] = "f64x2.sqrt",
    [WA_INSTR_f64x2_add] = "f64x2.add",
    [WA_INSTR_f64x2_sub] = "f64x2.sub",
    [WA_INSTR_f64x2_mul] = "f64x2.mul",
    [WA_INSTR_f64x2_div] = "f64x2.div",
    [WA_INSTR_f64x2_min] = "f64x2.min",
    [WA_INSTR_f64x2_max] = "f64x2.max",
    [WA_INSTR_f64x2_pmin] = "f64x2.pmin",
    [WA_INSTR_f64x2_pmax] = "f64x2.pmax",
    [WA_INSTR_i32x4_trunc_sat_f32x4_s] = "i32x4.trunc_sat_f32x4_s",
    [WA_INSTR_i32x4_trunc_sat_f32x4_u] = "i32x4.trunc_sat_f32x4_u",
    [WA_INSTR_f32x4_convert_i32x4_s] = "f32x4.convert_i32x4_s",
    [WA_INSTR_f32x4_convert_i32x4_u] = "f32x4.convert_i32x4_u",
    [WA_INSTR_i32x4_trunc_sat_f64x2_s_zero] = "i32x4.trunc_sat_f64x2_s_zero",
    [WA_INSTR_i32x4_trunc_sat_f64x2_u_zero] = "i32x4.trunc_sat_f64x2_u_zero",
    [WA_INSTR_f64x2_convert_low_i32x4_s] = "f64x2.convert_low_i32x4_s",
    [WA_INSTR_f64x2_convert_low_i32x4_u] = "f64x2.convert_low_i32x4_u",
    [WA_INSTR_f32x4_demote_f64x2_zero] = "f32x4.demote_f64x2_zero",
    [WA_INSTR_f64x2_promote_low_f32x4] = "f64x2.promote_low_f32x4",

    [WA_INSTR_move] = "move",
    [WA_INSTR_jump] = "jump",
    [WA_INSTR_jump_if_zero] = "jump_if_zero",
    [WA_INSTR_jump_table] = "jump_table",
};

typedef enum wa_instruction_prefix
{
    WA_INSTR_PREFIX_EXTENDED = 0xfc,
    WA_INSTR_PREFIX_VECTOR = 0xfd,
} wa_instruction_prefix;

static const wa_instr_op wa_instr_decode_basic[] = {
    [0x00] = WA_INSTR_unreachable,
    [0x01] = WA_INSTR_nop,
    [0x02] = WA_INSTR_block,
    [0x03] = WA_INSTR_loop,
    [0x04] = WA_INSTR_if,
    [0x05] = WA_INSTR_else,
    [0x0b] = WA_INSTR_end,
    [0x0c] = WA_INSTR_br,
    [0x0d] = WA_INSTR_br_if,
    [0x0e] = WA_INSTR_br_table,
    [0x0f] = WA_INSTR_return,
    [0x10] = WA_INSTR_call,
    [0x11] = WA_INSTR_call_indirect,
    [0xd0] = WA_INSTR_ref_null,
    [0xd1] = WA_INSTR_ref_is_null,
    [0xd2] = WA_INSTR_ref_func,
    [0x1a] = WA_INSTR_drop,
    [0x1b] = WA_INSTR_select,
    [0x1c] = WA_INSTR_select_t,
    [0x20] = WA_INSTR_local_get,
    [0x21] = WA_INSTR_local_set,
    [0x22] = WA_INSTR_local_tee,
    [0x23] = WA_INSTR_global_get,
    [0x24] = WA_INSTR_global_set,
    [0x25] = WA_INSTR_table_get,
    [0x26] = WA_INSTR_table_set,
    [0x28] = WA_INSTR_i32_load,
    [0x29] = WA_INSTR_i64_load,
    [0x2a] = WA_INSTR_f32_load,
    [0x2b] = WA_INSTR_f64_load,
    [0x2c] = WA_INSTR_i32_load8_s,
    [0x2d] = WA_INSTR_i32_load8_u,
    [0x2e] = WA_INSTR_i32_load16_s,
    [0x2f] = WA_INSTR_i32_load16_u,
    [0x30] = WA_INSTR_i64_load8_s,
    [0x31] = WA_INSTR_i64_load8_u,
    [0x32] = WA_INSTR_i64_load16_s,
    [0x33] = WA_INSTR_i64_load16_u,
    [0x34] = WA_INSTR_i64_load32_s,
    [0x35] = WA_INSTR_i64_load32_u,
    [0x36] = WA_INSTR_i32_store,
    [0x37] = WA_INSTR_i64_store,
    [0x38] = WA_INSTR_f32_store,
    [0x39] = WA_INSTR_f64_store,
    [0x3a] = WA_INSTR_i32_store8,
    [0x3b] = WA_INSTR_i32_store16,
    [0x3c] = WA_INSTR_i64_store8,
    [0x3d] = WA_INSTR_i64_store16,
    [0x3e] = WA_INSTR_i64_store32,
    [0x3f] = WA_INSTR_memory_size,
    [0x40] = WA_INSTR_memory_grow,
    [0x41] = WA_INSTR_i32_const,
    [0x42] = WA_INSTR_i64_const,
    [0x43] = WA_INSTR_f32_const,
    [0x44] = WA_INSTR_f64_const,
    [0x45] = WA_INSTR_i32_eqz,
    [0x46] = WA_INSTR_i32_eq,
    [0x47] = WA_INSTR_i32_ne,
    [0x48] = WA_INSTR_i32_lt_s,
    [0x49] = WA_INSTR_i32_lt_u,
    [0x4a] = WA_INSTR_i32_gt_s,
    [0x4b] = WA_INSTR_i32_gt_u,
    [0x4c] = WA_INSTR_i32_le_s,
    [0x4d] = WA_INSTR_i32_le_u,
    [0x4e] = WA_INSTR_i32_ge_s,
    [0x4f] = WA_INSTR_i32_ge_u,
    [0x50] = WA_INSTR_i64_eqz,
    [0x51] = WA_INSTR_i64_eq,
    [0x52] = WA_INSTR_i64_ne,
    [0x53] = WA_INSTR_i64_lt_s,
    [0x54] = WA_INSTR_i64_lt_u,
    [0x55] = WA_INSTR_i64_gt_s,
    [0x56] = WA_INSTR_i64_gt_u,
    [0x57] = WA_INSTR_i64_le_s,
    [0x58] = WA_INSTR_i64_le_u,
    [0x59] = WA_INSTR_i64_ge_s,
    [0x5a] = WA_INSTR_i64_ge_u,
    [0x5b] = WA_INSTR_f32_eq,
    [0x5c] = WA_INSTR_f32_ne,
    [0x5d] = WA_INSTR_f32_lt,
    [0x5e] = WA_INSTR_f32_gt,
    [0x5f] = WA_INSTR_f32_le,
    [0x60] = WA_INSTR_f32_ge,
    [0x61] = WA_INSTR_f64_eq,
    [0x62] = WA_INSTR_f64_ne,
    [0x63] = WA_INSTR_f64_lt,
    [0x64] = WA_INSTR_f64_gt,
    [0x65] = WA_INSTR_f64_le,
    [0x66] = WA_INSTR_f64_ge,
    [0x67] = WA_INSTR_i32_clz,
    [0x68] = WA_INSTR_i32_ctz,
    [0x69] = WA_INSTR_i32_popcnt,
    [0x6a] = WA_INSTR_i32_add,
    [0x6b] = WA_INSTR_i32_sub,
    [0x6c] = WA_INSTR_i32_mul,
    [0x6d] = WA_INSTR_i32_div_s,
    [0x6e] = WA_INSTR_i32_div_u,
    [0x6f] = WA_INSTR_i32_rem_s,
    [0x70] = WA_INSTR_i32_rem_u,
    [0x71] = WA_INSTR_i32_and,
    [0x72] = WA_INSTR_i32_or,
    [0x73] = WA_INSTR_i32_xor,
    [0x74] = WA_INSTR_i32_shl,
    [0x75] = WA_INSTR_i32_shr_s,
    [0x76] = WA_INSTR_i32_shr_u,
    [0x77] = WA_INSTR_i32_rotl,
    [0x78] = WA_INSTR_i32_rotr,
    [0x79] = WA_INSTR_i64_clz,
    [0x7a] = WA_INSTR_i64_ctz,
    [0x7b] = WA_INSTR_i64_popcnt,
    [0x7c] = WA_INSTR_i64_add,
    [0x7d] = WA_INSTR_i64_sub,
    [0x7e] = WA_INSTR_i64_mul,
    [0x7f] = WA_INSTR_i64_div_s,
    [0x80] = WA_INSTR_i64_div_u,
    [0x81] = WA_INSTR_i64_rem_s,
    [0x82] = WA_INSTR_i64_rem_u,
    [0x83] = WA_INSTR_i64_and,
    [0x84] = WA_INSTR_i64_or,
    [0x85] = WA_INSTR_i64_xor,
    [0x86] = WA_INSTR_i64_shl,
    [0x87] = WA_INSTR_i64_shr_s,
    [0x88] = WA_INSTR_i64_shr_u,
    [0x89] = WA_INSTR_i64_rotl,
    [0x8a] = WA_INSTR_i64_rotr,
    [0x8b] = WA_INSTR_f32_abs,
    [0x8c] = WA_INSTR_f32_neg,
    [0x8d] = WA_INSTR_f32_ceil,
    [0x8e] = WA_INSTR_f32_floor,
    [0x8f] = WA_INSTR_f32_trunc,
    [0x90] = WA_INSTR_f32_nearest,
    [0x91] = WA_INSTR_f32_sqrt,
    [0x92] = WA_INSTR_f32_add,
    [0x93] = WA_INSTR_f32_sub,
    [0x94] = WA_INSTR_f32_mul,
    [0x95] = WA_INSTR_f32_div,
    [0x96] = WA_INSTR_f32_min,
    [0x97] = WA_INSTR_f32_max,
    [0x98] = WA_INSTR_f32_copysign,
    [0x99] = WA_INSTR_f64_abs,
    [0x9a] = WA_INSTR_f64_neg,
    [0x9b] = WA_INSTR_f64_ceil,
    [0x9c] = WA_INSTR_f64_floor,
    [0x9d] = WA_INSTR_f64_trunc,
    [0x9e] = WA_INSTR_f64_nearest,
    [0x9f] = WA_INSTR_f64_sqrt,
    [0xa0] = WA_INSTR_f64_add,
    [0xa1] = WA_INSTR_f64_sub,
    [0xa2] = WA_INSTR_f64_mul,
    [0xa3] = WA_INSTR_f64_div,
    [0xa4] = WA_INSTR_f64_min,
    [0xa5] = WA_INSTR_f64_max,
    [0xa6] = WA_INSTR_f64_copysign,
    [0xa7] = WA_INSTR_i32_wrap_i64,
    [0xa8] = WA_INSTR_i32_trunc_f32_s,
    [0xa9] = WA_INSTR_i32_trunc_f32_u,
    [0xaa] = WA_INSTR_i32_trunc_f64_s,
    [0xab] = WA_INSTR_i32_trunc_f64_u,
    [0xac] = WA_INSTR_i64_extend_i32_s,
    [0xad] = WA_INSTR_i64_extend_i32_u,
    [0xae] = WA_INSTR_i64_trunc_f32_s,
    [0xaf] = WA_INSTR_i64_trunc_f32_u,
    [0xb0] = WA_INSTR_i64_trunc_f64_s,
    [0xb1] = WA_INSTR_i64_trunc_f64_u,
    [0xb2] = WA_INSTR_f32_convert_i32_s,
    [0xb3] = WA_INSTR_f32_convert_i32_u,
    [0xb4] = WA_INSTR_f32_convert_i64_s,
    [0xb5] = WA_INSTR_f32_convert_i64_u,
    [0xb6] = WA_INSTR_f32_demote_f64,
    [0xb7] = WA_INSTR_f64_convert_i32_s,
    [0xb8] = WA_INSTR_f64_convert_i32_u,
    [0xb9] = WA_INSTR_f64_convert_i64_s,
    [0xba] = WA_INSTR_f64_convert_i64_u,
    [0xbb] = WA_INSTR_f64_promote_f32,
    [0xbc] = WA_INSTR_i32_reinterpret_f32,
    [0xbd] = WA_INSTR_i64_reinterpret_f64,
    [0xbe] = WA_INSTR_f32_reinterpret_i32,
    [0xbf] = WA_INSTR_f64_reinterpret_i64,
    [0xc0] = WA_INSTR_i32_extend8_s,
    [0xc1] = WA_INSTR_i32_extend16_s,
    [0xc2] = WA_INSTR_i64_extend8_s,
    [0xc3] = WA_INSTR_i64_extend16_s,
    [0xc4] = WA_INSTR_i64_extend32_s,
};

static const wa_instr_op wa_instr_decode_extended[] = {
    [12] = WA_INSTR_table_init,
    [13] = WA_INSTR_elem_drop,
    [14] = WA_INSTR_table_copy,
    [15] = WA_INSTR_table_grow,
    [16] = WA_INSTR_table_size,
    [17] = WA_INSTR_table_fill,
    [8] = WA_INSTR_memory_init,
    [9] = WA_INSTR_data_drop,
    [10] = WA_INSTR_memory_copy,
    [11] = WA_INSTR_memory_fill,
    [0] = WA_INSTR_i32_trunc_sat_f32_s,
    [1] = WA_INSTR_i32_trunc_sat_f32_u,
    [2] = WA_INSTR_i32_trunc_sat_f64_s,
    [3] = WA_INSTR_i32_trunc_sat_f64_u,
    [4] = WA_INSTR_i64_trunc_sat_f32_s,
    [5] = WA_INSTR_i64_trunc_sat_f32_u,
    [6] = WA_INSTR_i64_trunc_sat_f64_s,
    [7] = WA_INSTR_i64_trunc_sat_f64_u,
};

static const wa_instr_op wa_instr_decode_vector[] = {
    [0] = WA_INSTR_v128_load,
    [1] = WA_INSTR_v128_load8x8_s,
    [2] = WA_INSTR_v128_load8x8_u,
    [3] = WA_INSTR_v128_load16x4_s,
    [4] = WA_INSTR_v128_load16x4_u,
    [5] = WA_INSTR_v128_load32x2_s,
    [6] = WA_INSTR_v128_load32x2_u,
    [7] = WA_INSTR_v128_load8_splat,
    [8] = WA_INSTR_v128_load16_splat,
    [9] = WA_INSTR_v128_load32_splat,
    [10] = WA_INSTR_v128_load64_splat,
    [11] = WA_INSTR_v128_store,
    [92] = WA_INSTR_v128_load32_zero,
    [93] = WA_INSTR_v128_load64_zero,
    [84] = WA_INSTR_v128_load8_lane,
    [85] = WA_INSTR_v128_load16_lane,
    [86] = WA_INSTR_v128_load32_lane,
    [87] = WA_INSTR_v128_load64_lane,
    [88] = WA_INSTR_v128_store8_lane,
    [89] = WA_INSTR_v128_store16_lane,
    [90] = WA_INSTR_v128_store32_lane,
    [91] = WA_INSTR_v128_store64_lane,
    [12] = WA_INSTR_v128_const,
    [13] = WA_INSTR_i8x16_shuffle,
    [21] = WA_INSTR_i8x16_extract_lane_s,
    [22] = WA_INSTR_i8x16_extract_lane_u,
    [23] = WA_INSTR_i8x16_replace_lane,
    [24] = WA_INSTR_i16x8_extract_lane_s,
    [25] = WA_INSTR_i16x8_extract_lane_u,
    [26] = WA_INSTR_i16x8_replace_lane,
    [27] = WA_INSTR_i32x4_extract_lane,
    [28] = WA_INSTR_i32x4_replace_lane,
    [29] = WA_INSTR_i64x2_extract_lane,
    [30] = WA_INSTR_i64x2_replace_lane,
    [31] = WA_INSTR_f32x4_extract_lane,
    [32] = WA_INSTR_f32x4_replace_lane,
    [33] = WA_INSTR_f64x2_extract_lane,
    [34] = WA_INSTR_f64x2_replace_lane,
    [14] = WA_INSTR_i8x16_swizzle,
    [15] = WA_INSTR_i8x16_splat,
    [16] = WA_INSTR_i16x8_splat,
    [17] = WA_INSTR_i32x4_splat,
    [18] = WA_INSTR_i64x2_splat,
    [19] = WA_INSTR_f32x4_splat,
    [20] = WA_INSTR_f64x2_splat,
    [35] = WA_INSTR_i8x16_eq,
    [36] = WA_INSTR_i8x16_ne,
    [37] = WA_INSTR_i8x16_lt_s,
    [38] = WA_INSTR_i8x16_lt_u,
    [39] = WA_INSTR_i8x16_gt_s,
    [40] = WA_INSTR_i8x16_gt_u,
    [41] = WA_INSTR_i8x16_le_s,
    [42] = WA_INSTR_i8x16_le_u,
    [43] = WA_INSTR_i8x16_ge_s,
    [44] = WA_INSTR_i8x16_ge_u,
    [45] = WA_INSTR_i16x8_eq,
    [46] = WA_INSTR_i16x8_ne,
    [47] = WA_INSTR_i16x8_lt_s,
    [48] = WA_INSTR_i16x8_lt_u,
    [49] = WA_INSTR_i16x8_gt_s,
    [50] = WA_INSTR_i16x8_gt_u,
    [51] = WA_INSTR_i16x8_le_s,
    [52] = WA_INSTR_i16x8_le_u,
    [53] = WA_INSTR_i16x8_ge_s,
    [54] = WA_INSTR_i16x8_ge_u,
    [55] = WA_INSTR_i32x4_eq,
    [56] = WA_INSTR_i32x4_ne,
    [57] = WA_INSTR_i32x4_lt_s,
    [58] = WA_INSTR_i32x4_lt_u,
    [59] = WA_INSTR_i32x4_gt_s,
    [60] = WA_INSTR_i32x4_gt_u,
    [61] = WA_INSTR_i32x4_le_s,
    [62] = WA_INSTR_i32x4_le_u,
    [63] = WA_INSTR_i32x4_ge_s,
    [64] = WA_INSTR_i32x4_ge_u,
    [214] = WA_INSTR_i64x2_eq,
    [215] = WA_INSTR_i64x2_ne,
    [216] = WA_INSTR_i64x2_lt_s,
    [217] = WA_INSTR_i64x2_gt_s,
    [218] = WA_INSTR_i64x2_le_s,
    [219] = WA_INSTR_i64x2_ge_s,
    [65] = WA_INSTR_f32x4_eq,
    [66] = WA_INSTR_f32x4_ne,
    [67] = WA_INSTR_f32x4_lt,
    [68] = WA_INSTR_f32x4_gt,
    [69] = WA_INSTR_f32x4_le,
    [70] = WA_INSTR_f32x4_ge,
    [71] = WA_INSTR_f64x2_eq,
    [72] = WA_INSTR_f64x2_ne,
    [73] = WA_INSTR_f64x2_lt,
    [74] = WA_INSTR_f64x2_gt,
    [75] = WA_INSTR_f64x2_le,
    [76] = WA_INSTR_f64x2_ge,
    [77] = WA_INSTR_v128_not,
    [78] = WA_INSTR_v128_and,
    [79] = WA_INSTR_v128_andnot,
    [80] = WA_INSTR_v128_or,
    [81] = WA_INSTR_v128_xor,
    [82] = WA_INSTR_v128_bitselect,
    [83] = WA_INSTR_v128_any_true,
    [96] = WA_INSTR_i8x16_abs,
    [97] = WA_INSTR_i8x16_neg,
    [98] = WA_INSTR_i8x16_popcnt,
    [99] = WA_INSTR_i8x16_all_true,
    [100] = WA_INSTR_i8x16_bitmask,
    [101] = WA_INSTR_i8x16_narrow_i16x8_s,
    [102] = WA_INSTR_i8x16_narrow_i16x8_u,
    [107] = WA_INSTR_i8x16_shl,
    [108] = WA_INSTR_i8x16_shr_s,
    [109] = WA_INSTR_i8x16_shr_u,
    [110] = WA_INSTR_i8x16_add,
    [111] = WA_INSTR_i8x16_add_sat_s,
    [112] = WA_INSTR_i8x16_add_sat_u,
    [113] = WA_INSTR_i8x16_sub,
    [114] = WA_INSTR_i8x16_sub_sat_s,
    [115] = WA_INSTR_i8x16_sub_sat_u,
    [118] = WA_INSTR_i8x16_min_s,
    [119] = WA_INSTR_i8x16_min_u,
    [120] = WA_INSTR_i8x16_max_s,
    [121] = WA_INSTR_i8x16_max_u,
    [123] = WA_INSTR_i8x16_avgr_u,
    [124] = WA_INSTR_i16x8_extadd_pairwise_i8x16_s,
    [125] = WA_INSTR_i16x8_extadd_pairwise_i8x16_u,
    [128] = WA_INSTR_i16x8_abs,
    [129] = WA_INSTR_i16x8_neg,
    [130] = WA_INSTR_i16x8_q15_mulr_sat_s,
    [131] = WA_INSTR_i16x8_all_true,
    [132] = WA_INSTR_i16x8_bitmask,
    [133] = WA_INSTR_i16x8_narrow_i32x4_s,
    [134] = WA_INSTR_i16x8_narrow_i32x4_u,
    [135] = WA_INSTR_i16x8_extend_low_i8x16_s,
    [136] = WA_INSTR_i16x8_extend_high_i8x16_s,
    [137] = WA_INSTR_i16x8_extend_low_i8x16_u,
    [138] = WA_INSTR_i16x8_extend_high_i8x16_u,
    [139] = WA_INSTR_i16x8_shl,
    [140] = WA_INSTR_i16x8_shr_s,
    [141] = WA_INSTR_i16x8_shr_u,
    [142] = WA_INSTR_i16x8_add,
    [143] = WA_INSTR_i16x8_add_sat_s,
    [144] = WA_INSTR_i16x8_add_sat_u,
    [145] = WA_INSTR_i16x8_sub,
    [146] = WA_INSTR_i16x8_sub_sat_s,
    [147] = WA_INSTR_i16x8_sub_sat_u,
    [149] = WA_INSTR_i16x8_mul,
    [150] = WA_INSTR_i16x8_min_s,
    [151] = WA_INSTR_i16x8_min_u,
    [152] = WA_INSTR_i16x8_max_s,
    [153] = WA_INSTR_i16x8_max_u,
    [155] = WA_INSTR_i16x8_avgr_u,
    [156] = WA_INSTR_i16x8_extmul_low_i8x16_s,
    [157] = WA_INSTR_i16x8_extmul_high_i8x16_s,
    [158] = WA_INSTR_i16x8_extmul_low_i8x16_u,
    [159] = WA_INSTR_i16x8_extmul_high_i8x16_u,
    [126] = WA_INSTR_i32x4_extadd_pairwise_i16x8_s,
    [127] = WA_INSTR_i32x4_extadd_pairwise_i16x8_u,
    [160] = WA_INSTR_i32x4_abs,
    [161] = WA_INSTR_i32x4_neg,
    [163] = WA_INSTR_i32x4_all_true,
    [164] = WA_INSTR_i32x4_bitmask,
    [167] = WA_INSTR_i32x4_extend_low_i16x8_s,
    [168] = WA_INSTR_i32x4_extend_high_i16x8_s,
    [169] = WA_INSTR_i32x4_extend_low_i16x8_u,
    [170] = WA_INSTR_i32x4_extend_high_i16x8_u,
    [171] = WA_INSTR_i32x4_shl,
    [172] = WA_INSTR_i32x4_shr_s,
    [173] = WA_INSTR_i32x4_shr_u,
    [174] = WA_INSTR_i32x4_add,
    [177] = WA_INSTR_i32x4_sub,
    [181] = WA_INSTR_i32x4_mul,
    [182] = WA_INSTR_i32x4_min_s,
    [183] = WA_INSTR_i32x4_min_u,
    [184] = WA_INSTR_i32x4_max_s,
    [185] = WA_INSTR_i32x4_max_u,
    [186] = WA_INSTR_i32x4_dot_i16x8_s,
    [188] = WA_INSTR_i32x4_extmul_low_i16x8_s,
    [189] = WA_INSTR_i32x4_extmul_high_i16x8_s,
    [190] = WA_INSTR_i32x4_extmul_low_i16x8_u,
    [191] = WA_INSTR_i32x4_extmul_high_i16x8_u,
    [192] = WA_INSTR_i64x2_abs,
    [193] = WA_INSTR_i64x2_neg,
    [195] = WA_INSTR_i64x2_all_true,
    [196] = WA_INSTR_i64x2_bitmask,
    [199] = WA_INSTR_i64x2_extend_low_i32x4_s,
    [200] = WA_INSTR_i64x2_extend_high_i32x4_s,
    [201] = WA_INSTR_i64x2_extend_low_i32x4_u,
    [202] = WA_INSTR_i64x2_extend_high_i32x4_u,
    [203] = WA_INSTR_i64x2_shl,
    [204] = WA_INSTR_i64x2_shr_s,
    [205] = WA_INSTR_i64x2_shr_u,
    [206] = WA_INSTR_i64x2_add,
    [209] = WA_INSTR_i64x2_sub,
    [213] = WA_INSTR_i64x2_mul,
    [220] = WA_INSTR_i64x2_extmul_low_i32x4_s,
    [221] = WA_INSTR_i64x2_extmul_high_i32x4_s,
    [222] = WA_INSTR_i64x2_extmul_low_i32x4_u,
    [223] = WA_INSTR_i64x2_extmul_high_i32x4_u,
    [103] = WA_INSTR_f32x4_ceil,
    [104] = WA_INSTR_f32x4_floor,
    [105] = WA_INSTR_f32x4_trunc,
    [106] = WA_INSTR_f32x4_nearest,
    [224] = WA_INSTR_f32x4_abs,
    [225] = WA_INSTR_f32x4_neg,
    [227] = WA_INSTR_f32x4_sqrt,
    [228] = WA_INSTR_f32x4_add,
    [229] = WA_INSTR_f32x4_sub,
    [230] = WA_INSTR_f32x4_mul,
    [231] = WA_INSTR_f32x4_div,
    [232] = WA_INSTR_f32x4_min,
    [233] = WA_INSTR_f32x4_max,
    [234] = WA_INSTR_f32x4_pmin,
    [235] = WA_INSTR_f32x4_pmax,
    [116] = WA_INSTR_f64x2_ceil,
    [117] = WA_INSTR_f64x2_floor,
    [122] = WA_INSTR_f64x2_trunc,
    [148] = WA_INSTR_f64x2_nearest,
    [236] = WA_INSTR_f64x2_abs,
    [237] = WA_INSTR_f64x2_neg,
    [239] = WA_INSTR_f64x2_sqrt,
    [240] = WA_INSTR_f64x2_add,
    [241] = WA_INSTR_f64x2_sub,
    [242] = WA_INSTR_f64x2_mul,
    [243] = WA_INSTR_f64x2_div,
    [244] = WA_INSTR_f64x2_min,
    [245] = WA_INSTR_f64x2_max,
    [246] = WA_INSTR_f64x2_pmin,
    [247] = WA_INSTR_f64x2_pmax,
    [248] = WA_INSTR_i32x4_trunc_sat_f32x4_s,
    [249] = WA_INSTR_i32x4_trunc_sat_f32x4_u,
    [250] = WA_INSTR_f32x4_convert_i32x4_s,
    [251] = WA_INSTR_f32x4_convert_i32x4_u,
    [252] = WA_INSTR_i32x4_trunc_sat_f64x2_s_zero,
    [253] = WA_INSTR_i32x4_trunc_sat_f64x2_u_zero,
    [254] = WA_INSTR_f64x2_convert_low_i32x4_s,
    [255] = WA_INSTR_f64x2_convert_low_i32x4_u,
    [94] = WA_INSTR_f32x4_demote_f64x2_zero,
    [95] = WA_INSTR_f64x2_promote_low_f32x4,
};

static const u64 wa_instr_decode_basic_len = oc_array_size(wa_instr_decode_basic);
static const u64 wa_instr_decode_extended_len = oc_array_size(wa_instr_decode_extended);
static const u64 wa_instr_decode_vector_len = oc_array_size(wa_instr_decode_vector);

typedef enum wa_immediate_type
{
    WA_IMM_ZERO,
    WA_IMM_I32,
    WA_IMM_I64,
    WA_IMM_F32,
    WA_IMM_F64,
    WA_IMM_VALUE_TYPE,
    WA_IMM_REF_TYPE,
    WA_IMM_LOCAL_INDEX,
    WA_IMM_GLOBAL_INDEX,
    WA_IMM_FUNC_INDEX,
    WA_IMM_TYPE_INDEX,
    WA_IMM_TABLE_INDEX,
    WA_IMM_ELEM_INDEX,
    WA_IMM_DATA_INDEX,
    WA_IMM_MEM_ARG,
    WA_IMM_LANE_INDEX,
    WA_IMM_V128,
    WA_IMM_LABEL,

} wa_immediate_type;

typedef enum wa_opd_kind
{
    WA_OPD_UNKNOWN = 0,
    WA_OPD_CONST_I32,
    WA_OPD_CONST_I64,
    WA_OPD_CONST_F32,
    WA_OPD_CONST_F64,
    WA_OPD_LOCAL_INDEX,
    WA_OPD_JUMP_TARGET,
} wa_opd_kind;

enum
{
    WA_INSTR_IN_MAX_COUNT = 3,
    WA_INSTR_OUT_MAX_COUNT = 3,
    WA_INSTR_OPD_MAX_COUNT = 4,
};

typedef struct wa_instr_info
{
    u32 immCount;
    wa_immediate_type imm[WA_INSTR_IMM_MAX_COUNT];

    u32 inCount;
    wa_value_type in[WA_INSTR_IN_MAX_COUNT];

    u32 outCount;
    wa_value_type out[WA_INSTR_OUT_MAX_COUNT];

    u32 opdCount;
    wa_opd_kind opd[WA_INSTR_OPD_MAX_COUNT];

    bool defined;
} wa_instr_info;

static const wa_instr_info wa_instr_infos[] = {
    [WA_INSTR_nop] = {
        .defined = true,
    },
    [WA_INSTR_unreachable] = {
        .defined = true,
    },
    [WA_INSTR_block] = {
        .defined = true,
    },
    [WA_INSTR_loop] = {
        .defined = true,
    },
    [WA_INSTR_if] = {
        .defined = true,
    },
    [WA_INSTR_else] = {
        .defined = true,
    },
    [WA_INSTR_end] = {
        .defined = true,
    },
    [WA_INSTR_br] = {
        .immCount = 1,
        .imm = { WA_IMM_LABEL },
        .defined = true,
    },
    [WA_INSTR_br_if] = {
        .immCount = 1,
        .imm = { WA_IMM_LABEL },
        .defined = true,
    },
    [WA_INSTR_br_table] = {
        .defined = true,
    },
    [WA_INSTR_return] = {
        .defined = true,
    },
    [WA_INSTR_call] = {
        .immCount = 1,
        .imm = { WA_IMM_FUNC_INDEX },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_call_indirect] = {
        .immCount = 2,
        .imm = {
            WA_IMM_TYPE_INDEX,
            WA_IMM_TABLE_INDEX,
        },
        .opdCount = 4,
        .defined = true,
    },
    [WA_INSTR_ref_null] = {
        .immCount = 1,
        .imm = { WA_IMM_REF_TYPE },
        .outCount = 1,
        .out = { WA_TYPE_FUNC_REF },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_ref_is_null] = {
        .inCount = 1,
        .in = { WA_TYPE_REF },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_ref_func] = {
        .immCount = 1,
        .imm = { WA_IMM_FUNC_INDEX },
        .outCount = 1,
        .out = { WA_TYPE_FUNC_REF },
        .opdCount = 2,
        .defined = true,
    },

    // parametric instructions
    [WA_INSTR_drop] = {
        .inCount = 1,
        .in = { WA_TYPE_ANY },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_select] = {
        .inCount = 3,
        .in = {
            WA_TYPE_NUM_OR_VEC,
            WA_TYPE_NUM_OR_VEC,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_ANY,
        },
        .opdCount = 4,
        .defined = true,
    },
    [WA_INSTR_select_t] = {
        .immCount = 1,
        .imm = { WA_IMM_VALUE_TYPE },
        .inCount = 3,
        .in = {
            WA_TYPE_ANY,
            WA_TYPE_ANY,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_ANY,
        },
        .opdCount = 5,
        .defined = true,
    },

    [WA_INSTR_local_get] = {
        .immCount = 1,
        .imm = { WA_IMM_LOCAL_INDEX },
        .outCount = 1,
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_local_set] = {
        .immCount = 1,
        .imm = { WA_IMM_LOCAL_INDEX },
        .inCount = 1,
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_local_tee] = {
        .immCount = 1,
        .imm = { WA_IMM_LOCAL_INDEX },
        .inCount = 1,
        .outCount = 1,
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_global_get] = {
        .immCount = 1,
        .imm = { WA_IMM_GLOBAL_INDEX },
        .outCount = 1,
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_global_set] = {
        .immCount = 1,
        .imm = { WA_IMM_GLOBAL_INDEX },
        .inCount = 1,
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_table_get] = {
        // special cased
        .immCount = 1,
        .imm = { WA_IMM_TABLE_INDEX },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_FUNC_REF },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_table_set] = {
        // special cased
        .immCount = 1,
        .imm = { WA_IMM_TABLE_INDEX },
        .inCount = 2,
        .in = {
            WA_TYPE_FUNC_REF,
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_load] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_load] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_load] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_load] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_load8_s] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_load8_u] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_load16_s] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_load16_u] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_load8_s] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_load8_u] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_load16_s] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_load16_u] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_load32_s] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_load32_u] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_store] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_store] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I64,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_store] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_F32,

        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_store] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_F64,

        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_store8] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_store16] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_store8] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I64,

        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_store16] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I64,

        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_store32] = {
        .immCount = 1,
        .imm = { WA_IMM_MEM_ARG },
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I64,

        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_memory_size] = {
        .immCount = 1,
        .imm = { WA_IMM_ZERO },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_memory_grow] = {
        .immCount = 1,
        .imm = { WA_IMM_ZERO },
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },

    [WA_INSTR_i32_const] = {
        .immCount = 1,
        .imm = { WA_IMM_I32 },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .opd = {
            WA_OPD_LOCAL_INDEX,
            WA_OPD_CONST_I32,
        },
        .defined = true,
    },
    [WA_INSTR_i64_const] = {
        .immCount = 1,
        .imm = { WA_IMM_I64 },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 2,
        .opd = {
            WA_OPD_LOCAL_INDEX,
            WA_OPD_CONST_I64,
        },
        .defined = true,
    },
    [WA_INSTR_f32_const] = {
        .immCount = 1,
        .imm = { WA_IMM_F32 },
        .outCount = 1,
        .out = {
            WA_TYPE_F32,
        },
        .opdCount = 2,
        .opd = {
            WA_OPD_LOCAL_INDEX,
            WA_OPD_CONST_F32,
        },
        .defined = true,
    },
    [WA_INSTR_f64_const] = {
        .immCount = 1,
        .imm = { WA_IMM_F64 },
        .outCount = 1,
        .out = {
            WA_TYPE_F64,
        },
        .opdCount = 2,
        .opd = {
            WA_OPD_LOCAL_INDEX,
            WA_OPD_CONST_F64,
        },
        .defined = true,
    },
    [WA_INSTR_i32_eqz] = {
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_eq] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_ne] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_lt_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_lt_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_gt_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_gt_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_le_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_le_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_ge_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_ge_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },

    [WA_INSTR_i64_eqz] = {
        .inCount = 1,
        .in = { WA_TYPE_I64 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_eq] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_ne] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_lt_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_lt_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_gt_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_gt_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_le_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_le_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_ge_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_ge_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },

    [WA_INSTR_f32_eq] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_ne] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_lt] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_gt] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_le] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_ge] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_eq] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_ne] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_lt] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_gt] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_le] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_ge] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 3,
        .defined = true,
    },

    [WA_INSTR_i32_clz] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_ctz] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_popcnt] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_add] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_sub] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_mul] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_div_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_div_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_rem_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_rem_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_and] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_or] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_xor] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_shl] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_shr_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_shr_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_rotl] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i32_rotr] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I32,
        },
        .opdCount = 3,
        .defined = true,
    },

    [WA_INSTR_i64_clz] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_ctz] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_popcnt] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_add] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_sub] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_mul] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_div_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_div_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_rem_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_rem_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_and] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_or] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_xor] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_shl] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_shr_s] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_shr_u] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_rotl] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_i64_rotr] = {
        .inCount = 2,
        .in = {
            WA_TYPE_I64,
            WA_TYPE_I64,
        },
        .outCount = 1,
        .out = {
            WA_TYPE_I64,
        },
        .opdCount = 3,
        .defined = true,
    },

    [WA_INSTR_f32_abs] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_neg] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_ceil] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_floor] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_trunc] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_nearest] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_sqrt] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_add] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_sub] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_mul] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_div] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_min] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_max] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f32_copysign] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F32,
            WA_TYPE_F32,
        },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 3,
        .defined = true,
    },

    [WA_INSTR_f64_abs] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_neg] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_ceil] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_floor] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_trunc] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_nearest] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_sqrt] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_add] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_sub] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_mul] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_div] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_min] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_max] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 3,
        .defined = true,
    },
    [WA_INSTR_f64_copysign] = {
        .inCount = 2,
        .in = {
            WA_TYPE_F64,
            WA_TYPE_F64,
        },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 3,
        .defined = true,
    },

    [WA_INSTR_i32_wrap_i64] = {
        .inCount = 1,
        .in = { WA_TYPE_I64 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_trunc_f32_s] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_trunc_f32_u] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_trunc_f64_s] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_trunc_f64_u] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_extend_i32_s] = {
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_extend_i32_u] = {
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_trunc_f32_s] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_trunc_f32_u] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_trunc_f64_s] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_trunc_f64_u] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_convert_i32_s] = {
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_convert_i32_u] = {
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_convert_i64_s] = {
        .inCount = 1,
        .in = { WA_TYPE_I64 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_convert_i64_u] = {
        .inCount = 1,
        .in = { WA_TYPE_I64 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_demote_f64] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_convert_i32_s] = {
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_convert_i32_u] = {
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_convert_i64_s] = {
        .inCount = 1,
        .in = { WA_TYPE_I64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_convert_i64_u] = {
        .inCount = 1,
        .in = { WA_TYPE_I64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_promote_f32] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_reinterpret_f32] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_reinterpret_f64] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f32_reinterpret_i32] = {
        .inCount = 1,
        .in = { WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_F32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_f64_reinterpret_i64] = {
        .inCount = 1,
        .in = { WA_TYPE_I64 },
        .outCount = 1,
        .out = { WA_TYPE_F64 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_extend8_s] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I32,
        },
        .outCount = 1,
        {
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i32_extend16_s] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I32,
        },
        .outCount = 1,
        {
            WA_TYPE_I32,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_extend8_s] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I64,
        },
        .outCount = 1,
        {
            WA_TYPE_I64,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_extend16_s] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I64,
        },
        .outCount = 1,
        {
            WA_TYPE_I64,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_i64_extend32_s] = {
        .inCount = 1,
        .in = {
            WA_TYPE_I64,
        },
        .outCount = 1,
        {
            WA_TYPE_I64,
        },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_table_init] = {
        .immCount = 2,
        .imm = {
            WA_IMM_ELEM_INDEX,
            WA_IMM_TABLE_INDEX,
        },
        .inCount = 3,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .opdCount = 5,
        .defined = true,
    },
    [WA_INSTR_elem_drop] = {
        .immCount = 1,
        .imm = { WA_IMM_ELEM_INDEX },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_table_copy] = {
        .immCount = 2,
        .imm = {
            WA_IMM_TABLE_INDEX,
            WA_IMM_TABLE_INDEX,
        },
        .inCount = 3,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .opdCount = 5,
        .defined = true,
    },
    [WA_INSTR_table_grow] = {
        //special cased
        .immCount = 1,
        .imm = { WA_IMM_TABLE_INDEX },
        .inCount = 2,
        .in = { WA_TYPE_FUNC_REF, WA_TYPE_I32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 4,
        .defined = true,
    },
    [WA_INSTR_table_size] = {
        .immCount = 1,
        .imm = { WA_IMM_TABLE_INDEX },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 2,
        .defined = true,
    },
    [WA_INSTR_table_fill] = {
        //special cased
        .immCount = 1,
        .imm = { WA_IMM_TABLE_INDEX },
        .inCount = 3,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_FUNC_REF,
            WA_TYPE_I32,
        },
        .opdCount = 4,
        .defined = true,
    },
    [WA_INSTR_memory_init] = {
        .immCount = 2,
        .imm = {
            WA_IMM_DATA_INDEX,
            WA_IMM_ZERO,
        },
        .inCount = 3,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .opdCount = 5,
        .defined = true,
    },
    [WA_INSTR_data_drop] = {
        .immCount = 1,
        .imm = { WA_IMM_DATA_INDEX },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_memory_copy] = {
        .immCount = 2,
        .imm = {
            WA_IMM_ZERO,
            WA_IMM_ZERO,
        },
        .inCount = 3,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .opdCount = 5,
        .defined = true,
    },
    [WA_INSTR_memory_fill] = {
        .immCount = 1,
        .imm = { WA_IMM_ZERO },
        .inCount = 3,
        .in = {
            WA_TYPE_I32,
            WA_TYPE_I32,
            WA_TYPE_I32,
        },
        .opdCount = 4,
        .defined = true,
    },

    [WA_INSTR_i32_trunc_sat_f32_s] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_i32_trunc_sat_f32_u] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_i32_trunc_sat_f64_s] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_i32_trunc_sat_f64_u] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I32 },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_i64_trunc_sat_f32_s] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_i64_trunc_sat_f32_u] = {
        .inCount = 1,
        .in = { WA_TYPE_F32 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_i64_trunc_sat_f64_s] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_i64_trunc_sat_f64_u] = {
        .inCount = 1,
        .in = { WA_TYPE_F64 },
        .outCount = 1,
        .out = { WA_TYPE_I64 },
        .opdCount = 1,
        .defined = true,
    },
    [WA_INSTR_v128_load] = {},
    [WA_INSTR_v128_load8x8_s] = {},
    [WA_INSTR_v128_load8x8_u] = {},
    [WA_INSTR_v128_load16x4_s] = {},
    [WA_INSTR_v128_load16x4_u] = {},
    [WA_INSTR_v128_load32x2_s] = {},
    [WA_INSTR_v128_load32x2_u] = {},
    [WA_INSTR_v128_load8_splat] = {},
    [WA_INSTR_v128_load16_splat] = {},
    [WA_INSTR_v128_load32_splat] = {},
    [WA_INSTR_v128_load64_splat] = {},
    [WA_INSTR_v128_store] = {},
    [WA_INSTR_v128_load32_zero] = {},
    [WA_INSTR_v128_load64_zero] = {},
    [WA_INSTR_v128_load8_lane] = {},
    [WA_INSTR_v128_load16_lane] = {},
    [WA_INSTR_v128_load32_lane] = {},
    [WA_INSTR_v128_load64_lane] = {},
    [WA_INSTR_v128_store8_lane] = {},
    [WA_INSTR_v128_store16_lane] = {},
    [WA_INSTR_v128_store32_lane] = {},
    [WA_INSTR_v128_store64_lane] = {},
    [WA_INSTR_v128_const] = {},
    [WA_INSTR_i8x16_shuffle] = {},
    [WA_INSTR_i8x16_extract_lane_s] = {},
    [WA_INSTR_i8x16_extract_lane_u] = {},
    [WA_INSTR_i8x16_replace_lane] = {},
    [WA_INSTR_i16x8_extract_lane_s] = {},
    [WA_INSTR_i16x8_extract_lane_u] = {},
    [WA_INSTR_i16x8_replace_lane] = {},
    [WA_INSTR_i32x4_extract_lane] = {},
    [WA_INSTR_i32x4_replace_lane] = {},
    [WA_INSTR_i64x2_extract_lane] = {},
    [WA_INSTR_i64x2_replace_lane] = {},
    [WA_INSTR_f32x4_extract_lane] = {},
    [WA_INSTR_f32x4_replace_lane] = {},
    [WA_INSTR_f64x2_extract_lane] = {},
    [WA_INSTR_f64x2_replace_lane] = {},
    [WA_INSTR_i8x16_swizzle] = {},
    [WA_INSTR_i8x16_splat] = {},
    [WA_INSTR_i16x8_splat] = {},
    [WA_INSTR_i32x4_splat] = {},
    [WA_INSTR_i64x2_splat] = {},
    [WA_INSTR_f32x4_splat] = {},
    [WA_INSTR_f64x2_splat] = {},
    [WA_INSTR_i8x16_eq] = {},
    [WA_INSTR_i8x16_ne] = {},
    [WA_INSTR_i8x16_lt_s] = {},
    [WA_INSTR_i8x16_lt_u] = {},
    [WA_INSTR_i8x16_gt_s] = {},
    [WA_INSTR_i8x16_gt_u] = {},
    [WA_INSTR_i8x16_le_s] = {},
    [WA_INSTR_i8x16_le_u] = {},
    [WA_INSTR_i8x16_ge_s] = {},
    [WA_INSTR_i8x16_ge_u] = {},
    [WA_INSTR_i16x8_eq] = {},
    [WA_INSTR_i16x8_ne] = {},
    [WA_INSTR_i16x8_lt_s] = {},
    [WA_INSTR_i16x8_lt_u] = {},
    [WA_INSTR_i16x8_gt_s] = {},
    [WA_INSTR_i16x8_gt_u] = {},
    [WA_INSTR_i16x8_le_s] = {},
    [WA_INSTR_i16x8_le_u] = {},
    [WA_INSTR_i16x8_ge_s] = {},
    [WA_INSTR_i16x8_ge_u] = {},
    [WA_INSTR_i32x4_eq] = {},
    [WA_INSTR_i32x4_ne] = {},
    [WA_INSTR_i32x4_lt_s] = {},
    [WA_INSTR_i32x4_lt_u] = {},
    [WA_INSTR_i32x4_gt_s] = {},
    [WA_INSTR_i32x4_gt_u] = {},
    [WA_INSTR_i32x4_le_s] = {},
    [WA_INSTR_i32x4_le_u] = {},
    [WA_INSTR_i32x4_ge_s] = {},
    [WA_INSTR_i32x4_ge_u] = {},
    [WA_INSTR_i64x2_eq] = {},
    [WA_INSTR_i64x2_ne] = {},
    [WA_INSTR_i64x2_lt_s] = {},
    [WA_INSTR_i64x2_gt_s] = {},
    [WA_INSTR_i64x2_le_s] = {},
    [WA_INSTR_i64x2_ge_s] = {},
    [WA_INSTR_f32x4_eq] = {},
    [WA_INSTR_f32x4_ne] = {},
    [WA_INSTR_f32x4_lt] = {},
    [WA_INSTR_f32x4_gt] = {},
    [WA_INSTR_f32x4_le] = {},
    [WA_INSTR_f32x4_ge] = {},
    [WA_INSTR_f64x2_eq] = {},
    [WA_INSTR_f64x2_ne] = {},
    [WA_INSTR_f64x2_lt] = {},
    [WA_INSTR_f64x2_gt] = {},
    [WA_INSTR_f64x2_le] = {},
    [WA_INSTR_f64x2_ge] = {},
    [WA_INSTR_v128_not] = {},
    [WA_INSTR_v128_and] = {},
    [WA_INSTR_v128_andnot] = {},
    [WA_INSTR_v128_or] = {},
    [WA_INSTR_v128_xor] = {},
    [WA_INSTR_v128_bitselect] = {},
    [WA_INSTR_v128_any_true] = {},
    [WA_INSTR_i8x16_abs] = {},
    [WA_INSTR_i8x16_neg] = {},
    [WA_INSTR_i8x16_popcnt] = {},
    [WA_INSTR_i8x16_all_true] = {},
    [WA_INSTR_i8x16_bitmask] = {},
    [WA_INSTR_i8x16_narrow_i16x8_s] = {},
    [WA_INSTR_i8x16_narrow_i16x8_u] = {},
    [WA_INSTR_i8x16_shl] = {},
    [WA_INSTR_i8x16_shr_s] = {},
    [WA_INSTR_i8x16_shr_u] = {},
    [WA_INSTR_i8x16_add] = {},
    [WA_INSTR_i8x16_add_sat_s] = {},
    [WA_INSTR_i8x16_add_sat_u] = {},
    [WA_INSTR_i8x16_sub] = {},
    [WA_INSTR_i8x16_sub_sat_s] = {},
    [WA_INSTR_i8x16_sub_sat_u] = {},
    [WA_INSTR_i8x16_min_s] = {},
    [WA_INSTR_i8x16_min_u] = {},
    [WA_INSTR_i8x16_max_s] = {},
    [WA_INSTR_i8x16_max_u] = {},
    [WA_INSTR_i8x16_avgr_u] = {},
    [WA_INSTR_i16x8_extadd_pairwise_i8x16_s] = {},
    [WA_INSTR_i16x8_extadd_pairwise_i8x16_u] = {},
    [WA_INSTR_i16x8_abs] = {},
    [WA_INSTR_i16x8_neg] = {},
    [WA_INSTR_i16x8_q15_mulr_sat_s] = {},
    [WA_INSTR_i16x8_all_true] = {},
    [WA_INSTR_i16x8_bitmask] = {},
    [WA_INSTR_i16x8_narrow_i32x4_s] = {},
    [WA_INSTR_i16x8_narrow_i32x4_u] = {},
    [WA_INSTR_i16x8_extend_low_i8x16_s] = {},
    [WA_INSTR_i16x8_extend_high_i8x16_s] = {},
    [WA_INSTR_i16x8_extend_low_i8x16_u] = {},
    [WA_INSTR_i16x8_extend_high_i8x16_u] = {},
    [WA_INSTR_i16x8_shl] = {},
    [WA_INSTR_i16x8_shr_s] = {},
    [WA_INSTR_i16x8_shr_u] = {},
    [WA_INSTR_i16x8_add] = {},
    [WA_INSTR_i16x8_add_sat_s] = {},
    [WA_INSTR_i16x8_add_sat_u] = {},
    [WA_INSTR_i16x8_sub] = {},
    [WA_INSTR_i16x8_sub_sat_s] = {},
    [WA_INSTR_i16x8_sub_sat_u] = {},
    [WA_INSTR_i16x8_mul] = {},
    [WA_INSTR_i16x8_min_s] = {},
    [WA_INSTR_i16x8_min_u] = {},
    [WA_INSTR_i16x8_max_s] = {},
    [WA_INSTR_i16x8_max_u] = {},
    [WA_INSTR_i16x8_avgr_u] = {},
    [WA_INSTR_i16x8_extmul_low_i8x16_s] = {},
    [WA_INSTR_i16x8_extmul_high_i8x16_s] = {},
    [WA_INSTR_i16x8_extmul_low_i8x16_u] = {},
    [WA_INSTR_i16x8_extmul_high_i8x16_u] = {},
    [WA_INSTR_i32x4_extadd_pairwise_i16x8_s] = {},
    [WA_INSTR_i32x4_extadd_pairwise_i16x8_u] = {},
    [WA_INSTR_i32x4_abs] = {},
    [WA_INSTR_i32x4_neg] = {},
    [WA_INSTR_i32x4_all_true] = {},
    [WA_INSTR_i32x4_bitmask] = {},
    [WA_INSTR_i32x4_extend_low_i16x8_s] = {},
    [WA_INSTR_i32x4_extend_high_i16x8_s] = {},
    [WA_INSTR_i32x4_extend_low_i16x8_u] = {},
    [WA_INSTR_i32x4_extend_high_i16x8_u] = {},
    [WA_INSTR_i32x4_shl] = {},
    [WA_INSTR_i32x4_shr_s] = {},
    [WA_INSTR_i32x4_shr_u] = {},
    [WA_INSTR_i32x4_add] = {},
    [WA_INSTR_i32x4_sub] = {},
    [WA_INSTR_i32x4_mul] = {},
    [WA_INSTR_i32x4_min_s] = {},
    [WA_INSTR_i32x4_min_u] = {},
    [WA_INSTR_i32x4_max_s] = {},
    [WA_INSTR_i32x4_max_u] = {},
    [WA_INSTR_i32x4_dot_i16x8_s] = {},
    [WA_INSTR_i32x4_extmul_low_i16x8_s] = {},
    [WA_INSTR_i32x4_extmul_high_i16x8_s] = {},
    [WA_INSTR_i32x4_extmul_low_i16x8_u] = {},
    [WA_INSTR_i32x4_extmul_high_i16x8_u] = {},
    [WA_INSTR_i64x2_abs] = {},
    [WA_INSTR_i64x2_neg] = {},
    [WA_INSTR_i64x2_all_true] = {},
    [WA_INSTR_i64x2_bitmask] = {},
    [WA_INSTR_i64x2_extend_low_i32x4_s] = {},
    [WA_INSTR_i64x2_extend_high_i32x4_s] = {},
    [WA_INSTR_i64x2_extend_low_i32x4_u] = {},
    [WA_INSTR_i64x2_extend_high_i32x4_u] = {},
    [WA_INSTR_i64x2_shl] = {},
    [WA_INSTR_i64x2_shr_s] = {},
    [WA_INSTR_i64x2_shr_u] = {},
    [WA_INSTR_i64x2_add] = {},
    [WA_INSTR_i64x2_sub] = {},
    [WA_INSTR_i64x2_mul] = {},
    [WA_INSTR_i64x2_extmul_low_i32x4_s] = {},
    [WA_INSTR_i64x2_extmul_high_i32x4_s] = {},
    [WA_INSTR_i64x2_extmul_low_i32x4_u] = {},
    [WA_INSTR_i64x2_extmul_high_i32x4_u] = {},
    [WA_INSTR_f32x4_ceil] = {},
    [WA_INSTR_f32x4_floor] = {},
    [WA_INSTR_f32x4_trunc] = {},
    [WA_INSTR_f32x4_nearest] = {},
    [WA_INSTR_f32x4_abs] = {},
    [WA_INSTR_f32x4_neg] = {},
    [WA_INSTR_f32x4_sqrt] = {},
    [WA_INSTR_f32x4_add] = {},
    [WA_INSTR_f32x4_sub] = {},
    [WA_INSTR_f32x4_mul] = {},
    [WA_INSTR_f32x4_div] = {},
    [WA_INSTR_f32x4_min] = {},
    [WA_INSTR_f32x4_max] = {},
    [WA_INSTR_f32x4_pmin] = {},
    [WA_INSTR_f32x4_pmax] = {},
    [WA_INSTR_f64x2_ceil] = {},
    [WA_INSTR_f64x2_floor] = {},
    [WA_INSTR_f64x2_trunc] = {},
    [WA_INSTR_f64x2_nearest] = {},
    [WA_INSTR_f64x2_abs] = {},
    [WA_INSTR_f64x2_neg] = {},
    [WA_INSTR_f64x2_sqrt] = {},
    [WA_INSTR_f64x2_add] = {},
    [WA_INSTR_f64x2_sub] = {},
    [WA_INSTR_f64x2_mul] = {},
    [WA_INSTR_f64x2_div] = {},
    [WA_INSTR_f64x2_min] = {},
    [WA_INSTR_f64x2_max] = {},
    [WA_INSTR_f64x2_pmin] = {},
    [WA_INSTR_f64x2_pmax] = {},
    [WA_INSTR_i32x4_trunc_sat_f32x4_s] = {},
    [WA_INSTR_i32x4_trunc_sat_f32x4_u] = {},
    [WA_INSTR_f32x4_convert_i32x4_s] = {},
    [WA_INSTR_f32x4_convert_i32x4_u] = {},
    [WA_INSTR_i32x4_trunc_sat_f64x2_s_zero] = {},
    [WA_INSTR_i32x4_trunc_sat_f64x2_u_zero] = {},
    [WA_INSTR_f64x2_convert_low_i32x4_s] = {},
    [WA_INSTR_f64x2_convert_low_i32x4_u] = {},
    [WA_INSTR_f32x4_demote_f64x2_zero] = {},
    [WA_INSTR_f64x2_promote_low_f32x4] = {},

    [WA_INSTR_move] = {
        .opdCount = 2,
        .opd = {
            WA_OPD_LOCAL_INDEX,
            WA_OPD_LOCAL_INDEX,
        },
    },
    [WA_INSTR_jump] = {
        .opdCount = 1,
        .opd = { WA_OPD_JUMP_TARGET },
    },
    [WA_INSTR_jump_if] = {
        .opdCount = 2,
        .opd = {
            WA_OPD_JUMP_TARGET,
            WA_OPD_LOCAL_INDEX,
        },
    },
    [WA_INSTR_jump_if_zero] = {
        .opdCount = 2,
        .opd = {
            WA_OPD_JUMP_TARGET,
            WA_OPD_LOCAL_INDEX,
        },
    },
    [WA_INSTR_jump_table] = {
        .opdCount = 2,
    },
};
