site_name: Orca Documentation
site_url: https://docs.orca-app.dev
site_description: Official Orca Documentation

copyright: Copyright &copy; 2024 Martin Fouilleul and the Orca project contributors

extra_css:
  - css/extra.css
theme: readthedocs

nav:
  - Home: 'index.md'
  - Getting Started:
    - Installation: 'install.md'
    - Quick Start: 'QuickStart.md'
  - User Guide:
    - API Spec:
      - Overview: 'api/api_reference.md'
      - Utility:
        - Overview: 'api/Utility.md'
        - Algebra: 'api/Utility/Algebra.md'
        - Debug: 'api/Utility/Debug.md'
        - Lists: 'api/Utility/Lists.md'
        - Memory: 'api/Utility/Memory.md'
        - Strings: 'api/Utility/Strings.md'
        - UTF8: 'api/Utility/UTF8.md'
      - Application:
        - Overview: 'api/Application.md'
        - Events: 'api/Application/Events.md'
      - I/O:
        - Overview: 'api/I_O.md'
        - File API: 'api/I_O/File API.md'
        - Dialogs: 'api/I_O/Dialogs.md'
        - Paths: 'api/I_O/Paths.md'
      - Graphics:
        - Overview: 'api/Graphics.md'
        - Canvas API: 'api/Graphics/Canvas API.md'
        - GLES Surface: 'api/Graphics/GLES Surface.md'
      - UI: 'api/UI.md'

  - Developer Guide:
    - Building: 'building.md'
    - Editing the Documentation: 'documentation.md'
  - FAQ: 'faq.md'
