/*********************************************************************
*
*  Orca
*  Copyright 2023 Martin Fouilleul and the Orca project contributors
*  See LICENSE.txt for licensing information
*
*  Unicode script tables generated by gen_unicode_scripts_tables.py from unicode_scripts.h
*
**********************************************************************/
#ifndef __UNICODE_SCRIPTS_TABLE_H_
#define __UNICODE_SCRIPTS_TABLE_H_

#include "util/typedefs.h"
#include "util/macros.h"

#define OC_UNICODE_SCRIPTS(_) \
    _(COMMON, 0x0, 0x40, Zyyy) \
    _(LATIN, 0x41, 0x5a, Latn) \
    _(COMMON, 0x5b, 0x60, Zyyy) \
    _(LATIN, 0x61, 0x7a, Latn) \
    _(COMMON, 0x7b, 0xa9, Zyyy) \
    _(LATIN, 0xaa, 0xaa, Latn) \
    _(COMMON, 0xab, 0xb9, Zyyy) \
    _(LATIN, 0xba, 0xba, Latn) \
    _(COMMON, 0xbb, 0xbf, Zyyy) \
    _(LATIN, 0xc0, 0xd6, Latn) \
    _(COMMON, 0xd7, 0xd7, Zyyy) \
    _(LATIN, 0xd8, 0xf6, Latn) \
    _(COMMON, 0xf7, 0xf7, Zyyy) \
    _(LATIN, 0xf8, 0x2b8, Latn) \
    _(COMMON, 0x2b9, 0x2df, Zyyy) \
    _(LATIN, 0x2e0, 0x2e4, Latn) \
    _(COMMON, 0x2e5, 0x2e9, Zyyy) \
    _(BOPOMOFO, 0x2ea, 0x2eb, Bopo) \
    _(COMMON, 0x2ec, 0x2ff, Zyyy) \
    _(INHERITED, 0x300, 0x36f, Zinh) \
    _(GREEK, 0x370, 0x373, Grek) \
    _(COMMON, 0x374, 0x374, Zyyy) \
    _(GREEK, 0x375, 0x37d, Grek) \
    _(COMMON, 0x37e, 0x37e, Zyyy) \
    _(GREEK, 0x37f, 0x384, Grek) \
    _(COMMON, 0x385, 0x385, Zyyy) \
    _(GREEK, 0x386, 0x386, Grek) \
    _(COMMON, 0x387, 0x387, Zyyy) \
    _(GREEK, 0x388, 0x3e1, Grek) \
    _(COPTIC, 0x3e2, 0x3ef, Copt) \
    _(GREEK, 0x3f0, 0x3ff, Grek) \
    _(CYRILLIC, 0x400, 0x484, Cyrl) \
    _(INHERITED, 0x485, 0x486, Zinh) \
    _(CYRILLIC, 0x487, 0x530, Cyrl) \
    _(ARMENIAN, 0x531, 0x590, Armn) \
    _(HEBREW, 0x591, 0x5ff, Hebr) \
    _(ARABIC, 0x600, 0x604, Arab) \
    _(COMMON, 0x605, 0x605, Zyyy) \
    _(ARABIC, 0x606, 0x60b, Arab) \
    _(COMMON, 0x60c, 0x60c, Zyyy) \
    _(ARABIC, 0x60d, 0x61a, Arab) \
    _(COMMON, 0x61b, 0x61b, Zyyy) \
    _(ARABIC, 0x61c, 0x61e, Arab) \
    _(COMMON, 0x61f, 0x61f, Zyyy) \
    _(ARABIC, 0x620, 0x63f, Arab) \
    _(COMMON, 0x640, 0x640, Zyyy) \
    _(ARABIC, 0x641, 0x64a, Arab) \
    _(INHERITED, 0x64b, 0x655, Zinh) \
    _(ARABIC, 0x656, 0x66f, Arab) \
    _(INHERITED, 0x670, 0x670, Zinh) \
    _(ARABIC, 0x671, 0x6dc, Arab) \
    _(COMMON, 0x6dd, 0x6dd, Zyyy) \
    _(ARABIC, 0x6de, 0x6ff, Arab) \
    _(SYRIAC, 0x700, 0x74f, Syrc) \
    _(ARABIC, 0x750, 0x77f, Arab) \
    _(THAANA, 0x780, 0x7bf, Thaa) \
    _(NKO, 0x7c0, 0x7ff, Nkoo) \
    _(SAMARITAN, 0x800, 0x83f, Samr) \
    _(MANDAIC, 0x840, 0x85f, Mand) \
    _(SYRIAC, 0x860, 0x86f, Syrc) \
    _(ARABIC, 0x870, 0x8e1, Arab) \
    _(COMMON, 0x8e2, 0x8e2, Zyyy) \
    _(ARABIC, 0x8e3, 0x8ff, Arab) \
    _(DEVANAGARI, 0x900, 0x950, Deva) \
    _(INHERITED, 0x951, 0x954, Zinh) \
    _(DEVANAGARI, 0x955, 0x963, Deva) \
    _(COMMON, 0x964, 0x965, Zyyy) \
    _(DEVANAGARI, 0x966, 0x97f, Deva) \
    _(BENGALI, 0x980, 0xa00, Beng) \
    _(GURMUKHI, 0xa01, 0xa80, Guru) \
    _(GUJARATI, 0xa81, 0xb00, Gujr) \
    _(ORIYA, 0xb01, 0xb81, Orya) \
    _(TAMIL, 0xb82, 0xbff, Taml) \
    _(TELUGU, 0xc00, 0xc7f, Telu) \
    _(KANNADA, 0xc80, 0xcff, Knda) \
    _(MALAYALAM, 0xd00, 0xd80, Mlym) \
    _(SINHALA, 0xd81, 0xe00, Sinh) \
    _(THAI, 0xe01, 0xe3e, Thai) \
    _(COMMON, 0xe3f, 0xe3f, Zyyy) \
    _(THAI, 0xe40, 0xe80, Thai) \
    _(LAO, 0xe81, 0xeff, Laoo) \
    _(TIBETAN, 0xf00, 0xfd4, Tibt) \
    _(COMMON, 0xfd5, 0xfd8, Zyyy) \
    _(TIBETAN, 0xfd9, 0xfff, Tibt) \
    _(MYANMAR, 0x1000, 0x109f, Mymr) \
    _(GEORGIAN, 0x10a0, 0x10fa, Geor) \
    _(COMMON, 0x10fb, 0x10fb, Zyyy) \
    _(GEORGIAN, 0x10fc, 0x10ff, Geor) \
    _(HANGUL, 0x1100, 0x11ff, Hang) \
    _(ETHIOPIC, 0x1200, 0x139f, Ethi) \
    _(CHEROKEE, 0x13a0, 0x13ff, Cher) \
    _(CANADIAN_ABORIGINAL, 0x1400, 0x167f, Cans) \
    _(OGHAM, 0x1680, 0x169f, Ogam) \
    _(RUNIC, 0x16a0, 0x16ea, Runr) \
    _(COMMON, 0x16eb, 0x16ed, Zyyy) \
    _(RUNIC, 0x16ee, 0x16ff, Runr) \
    _(TAGALOG, 0x1700, 0x171f, Tglg) \
    _(HANUNOO, 0x1720, 0x1734, Hano) \
    _(COMMON, 0x1735, 0x173f, Zyyy) \
    _(BUHID, 0x1740, 0x175f, Buhd) \
    _(TAGBANWA, 0x1760, 0x177f, Tagb) \
    _(KHMER, 0x1780, 0x17ff, Khmr) \
    _(MONGOLIAN, 0x1800, 0x1801, Mong) \
    _(COMMON, 0x1802, 0x1803, Zyyy) \
    _(MONGOLIAN, 0x1804, 0x1804, Mong) \
    _(COMMON, 0x1805, 0x1805, Zyyy) \
    _(MONGOLIAN, 0x1806, 0x18af, Mong) \
    _(CANADIAN_ABORIGINAL, 0x18b0, 0x18ff, Cans) \
    _(LIMBU, 0x1900, 0x194f, Limb) \
    _(TAI_LE, 0x1950, 0x197f, Tale) \
    _(NEW_TAI_LUE, 0x1980, 0x19df, Talu) \
    _(KHMER, 0x19e0, 0x19ff, Khmr) \
    _(BUGINESE, 0x1a00, 0x1a1f, Bugi) \
    _(TAI_THAM, 0x1a20, 0x1aaf, Lana) \
    _(INHERITED, 0x1ab0, 0x1aff, Zinh) \
    _(BALINESE, 0x1b00, 0x1b7f, Bali) \
    _(SUNDANESE, 0x1b80, 0x1bbf, Sund) \
    _(BATAK, 0x1bc0, 0x1bff, Batk) \
    _(LEPCHA, 0x1c00, 0x1c4f, Lepc) \
    _(OL_CHIKI, 0x1c50, 0x1c7f, Olck) \
    _(CYRILLIC, 0x1c80, 0x1c8f, Cyrl) \
    _(GEORGIAN, 0x1c90, 0x1cbf, Geor) \
    _(SUNDANESE, 0x1cc0, 0x1ccf, Sund) \
    _(INHERITED, 0x1cd0, 0x1cd2, Zinh) \
    _(COMMON, 0x1cd3, 0x1cd3, Zyyy) \
    _(INHERITED, 0x1cd4, 0x1ce0, Zinh) \
    _(COMMON, 0x1ce1, 0x1ce1, Zyyy) \
    _(INHERITED, 0x1ce2, 0x1ce8, Zinh) \
    _(COMMON, 0x1ce9, 0x1cec, Zyyy) \
    _(INHERITED, 0x1ced, 0x1ced, Zinh) \
    _(COMMON, 0x1cee, 0x1cf3, Zyyy) \
    _(INHERITED, 0x1cf4, 0x1cf4, Zinh) \
    _(COMMON, 0x1cf5, 0x1cf7, Zyyy) \
    _(INHERITED, 0x1cf8, 0x1cf9, Zinh) \
    _(COMMON, 0x1cfa, 0x1cff, Zyyy) \
    _(LATIN, 0x1d00, 0x1d25, Latn) \
    _(GREEK, 0x1d26, 0x1d2a, Grek) \
    _(CYRILLIC, 0x1d2b, 0x1d2b, Cyrl) \
    _(LATIN, 0x1d2c, 0x1d5c, Latn) \
    _(GREEK, 0x1d5d, 0x1d61, Grek) \
    _(LATIN, 0x1d62, 0x1d65, Latn) \
    _(GREEK, 0x1d66, 0x1d6a, Grek) \
    _(LATIN, 0x1d6b, 0x1d77, Latn) \
    _(CYRILLIC, 0x1d78, 0x1d78, Cyrl) \
    _(LATIN, 0x1d79, 0x1dbe, Latn) \
    _(GREEK, 0x1dbf, 0x1dbf, Grek) \
    _(INHERITED, 0x1dc0, 0x1dff, Zinh) \
    _(LATIN, 0x1e00, 0x1eff, Latn) \
    _(GREEK, 0x1f00, 0x1fff, Grek) \
    _(COMMON, 0x2000, 0x200b, Zyyy) \
    _(INHERITED, 0x200c, 0x200d, Zinh) \
    _(COMMON, 0x200e, 0x2070, Zyyy) \
    _(LATIN, 0x2071, 0x2073, Latn) \
    _(COMMON, 0x2074, 0x207e, Zyyy) \
    _(LATIN, 0x207f, 0x207f, Latn) \
    _(COMMON, 0x2080, 0x208f, Zyyy) \
    _(LATIN, 0x2090, 0x209f, Latn) \
    _(COMMON, 0x20a0, 0x20cf, Zyyy) \
    _(INHERITED, 0x20d0, 0x20ff, Zinh) \
    _(COMMON, 0x2100, 0x2125, Zyyy) \
    _(GREEK, 0x2126, 0x2126, Grek) \
    _(COMMON, 0x2127, 0x2129, Zyyy) \
    _(LATIN, 0x212a, 0x212b, Latn) \
    _(COMMON, 0x212c, 0x2131, Zyyy) \
    _(LATIN, 0x2132, 0x2132, Latn) \
    _(COMMON, 0x2133, 0x214d, Zyyy) \
    _(LATIN, 0x214e, 0x214e, Latn) \
    _(COMMON, 0x214f, 0x215f, Zyyy) \
    _(LATIN, 0x2160, 0x2188, Latn) \
    _(COMMON, 0x2189, 0x27ff, Zyyy) \
    _(BRAILLE, 0x2800, 0x28ff, Brai) \
    _(COMMON, 0x2900, 0x2bff, Zyyy) \
    _(GLAGOLITIC, 0x2c00, 0x2c5f, Glag) \
    _(LATIN, 0x2c60, 0x2c7f, Latn) \
    _(COPTIC, 0x2c80, 0x2cff, Copt) \
    _(GEORGIAN, 0x2d00, 0x2d2f, Geor) \
    _(TIFINAGH, 0x2d30, 0x2d7f, Tfng) \
    _(ETHIOPIC, 0x2d80, 0x2ddf, Ethi) \
    _(CYRILLIC, 0x2de0, 0x2dff, Cyrl) \
    _(COMMON, 0x2e00, 0x2e7f, Zyyy) \
    _(HAN, 0x2e80, 0x2fef, Hani) \
    _(COMMON, 0x2ff0, 0x3004, Zyyy) \
    _(HAN, 0x3005, 0x3005, Hani) \
    _(COMMON, 0x3006, 0x3006, Zyyy) \
    _(HAN, 0x3007, 0x3007, Hani) \
    _(COMMON, 0x3008, 0x3020, Zyyy) \
    _(HAN, 0x3021, 0x3029, Hani) \
    _(INHERITED, 0x302a, 0x302d, Zinh) \
    _(HANGUL, 0x302e, 0x302f, Hang) \
    _(COMMON, 0x3030, 0x3037, Zyyy) \
    _(HAN, 0x3038, 0x303b, Hani) \
    _(COMMON, 0x303c, 0x3040, Zyyy) \
    _(HIRAGANA, 0x3041, 0x3098, Hira) \
    _(INHERITED, 0x3099, 0x309a, Zinh) \
    _(COMMON, 0x309b, 0x309c, Zyyy) \
    _(HIRAGANA, 0x309d, 0x309f, Hira) \
    _(COMMON, 0x30a0, 0x30a0, Zyyy) \
    _(KATAKANA, 0x30a1, 0x30fa, Kana) \
    _(COMMON, 0x30fb, 0x30fc, Zyyy) \
    _(KATAKANA, 0x30fd, 0x3104, Kana) \
    _(BOPOMOFO, 0x3105, 0x3130, Bopo) \
    _(HANGUL, 0x3131, 0x318f, Hang) \
    _(COMMON, 0x3190, 0x319f, Zyyy) \
    _(BOPOMOFO, 0x31a0, 0x31bf, Bopo) \
    _(COMMON, 0x31c0, 0x31ef, Zyyy) \
    _(KATAKANA, 0x31f0, 0x31ff, Kana) \
    _(HANGUL, 0x3200, 0x321f, Hang) \
    _(COMMON, 0x3220, 0x325f, Zyyy) \
    _(HANGUL, 0x3260, 0x327e, Hang) \
    _(COMMON, 0x327f, 0x32cf, Zyyy) \
    _(KATAKANA, 0x32d0, 0x32fe, Kana) \
    _(COMMON, 0x32ff, 0x32ff, Zyyy) \
    _(KATAKANA, 0x3300, 0x3357, Kana) \
    _(COMMON, 0x3358, 0x33ff, Zyyy) \
    _(HAN, 0x3400, 0x4dbf, Hani) \
    _(COMMON, 0x4dc0, 0x4dff, Zyyy) \
    _(HAN, 0x4e00, 0x9fff, Hani) \
    _(YI, 0xa000, 0xa4cf, Yiii) \
    _(LISU, 0xa4d0, 0xa4ff, Lisu) \
    _(VAI, 0xa500, 0xa63f, Vaii) \
    _(CYRILLIC, 0xa640, 0xa69f, Cyrl) \
    _(BAMUM, 0xa6a0, 0xa6ff, Bamu) \
    _(COMMON, 0xa700, 0xa721, Zyyy) \
    _(LATIN, 0xa722, 0xa787, Latn) \
    _(COMMON, 0xa788, 0xa78a, Zyyy) \
    _(LATIN, 0xa78b, 0xa7ff, Latn) \
    _(SYLOTI_NAGRI, 0xa800, 0xa82f, Sylo) \
    _(COMMON, 0xa830, 0xa83f, Zyyy) \
    _(PHAGS_PA, 0xa840, 0xa87f, Phag) \
    _(SAURASHTRA, 0xa880, 0xa8df, Saur) \
    _(DEVANAGARI, 0xa8e0, 0xa8ff, Deva) \
    _(KAYAH_LI, 0xa900, 0xa92d, Kali) \
    _(COMMON, 0xa92e, 0xa92e, Zyyy) \
    _(KAYAH_LI, 0xa92f, 0xa92f, Kali) \
    _(REJANG, 0xa930, 0xa95f, Rjng) \
    _(HANGUL, 0xa960, 0xa97f, Hang) \
    _(JAVANESE, 0xa980, 0xa9ce, Java) \
    _(COMMON, 0xa9cf, 0xa9cf, Zyyy) \
    _(JAVANESE, 0xa9d0, 0xa9df, Java) \
    _(MYANMAR, 0xa9e0, 0xa9ff, Mymr) \
    _(CHAM, 0xaa00, 0xaa5f, Cham) \
    _(MYANMAR, 0xaa60, 0xaa7f, Mymr) \
    _(TAI_VIET, 0xaa80, 0xaadf, Tavt) \
    _(MEETEI_MAYEK, 0xaae0, 0xab00, Mtei) \
    _(ETHIOPIC, 0xab01, 0xab2f, Ethi) \
    _(LATIN, 0xab30, 0xab5a, Latn) \
    _(COMMON, 0xab5b, 0xab5b, Zyyy) \
    _(LATIN, 0xab5c, 0xab64, Latn) \
    _(GREEK, 0xab65, 0xab65, Grek) \
    _(LATIN, 0xab66, 0xab69, Latn) \
    _(COMMON, 0xab6a, 0xab6f, Zyyy) \
    _(CHEROKEE, 0xab70, 0xabbf, Cher) \
    _(MEETEI_MAYEK, 0xabc0, 0xabff, Mtei) \
    _(HANGUL, 0xac00, 0xf8ff, Hang) \
    _(HAN, 0xf900, 0xfaff, Hani) \
    _(LATIN, 0xfb00, 0xfb12, Latn) \
    _(ARMENIAN, 0xfb13, 0xfb1c, Armn) \
    _(HEBREW, 0xfb1d, 0xfb4f, Hebr) \
    _(ARABIC, 0xfb50, 0xfd3d, Arab) \
    _(COMMON, 0xfd3e, 0xfd3f, Zyyy) \
    _(ARABIC, 0xfd40, 0xfdff, Arab) \
    _(INHERITED, 0xfe00, 0xfe0f, Zinh) \
    _(COMMON, 0xfe10, 0xfe1f, Zyyy) \
    _(INHERITED, 0xfe20, 0xfe2d, Zinh) \
    _(CYRILLIC, 0xfe2e, 0xfe2f, Cyrl) \
    _(COMMON, 0xfe30, 0xfe6f, Zyyy) \
    _(ARABIC, 0xfe70, 0xfefe, Arab) \
    _(COMMON, 0xfeff, 0xff20, Zyyy) \
    _(LATIN, 0xff21, 0xff3a, Latn) \
    _(COMMON, 0xff3b, 0xff40, Zyyy) \
    _(LATIN, 0xff41, 0xff5a, Latn) \
    _(COMMON, 0xff5b, 0xff65, Zyyy) \
    _(KATAKANA, 0xff66, 0xff6f, Kana) \
    _(COMMON, 0xff70, 0xff70, Zyyy) \
    _(KATAKANA, 0xff71, 0xff9d, Kana) \
    _(COMMON, 0xff9e, 0xff9f, Zyyy) \
    _(HANGUL, 0xffa0, 0xffdf, Hang) \
    _(COMMON, 0xffe0, 0xffff, Zyyy) \
    _(LINEAR_B, 0x10000, 0x100ff, Linb) \
    _(COMMON, 0x10100, 0x1013f, Zyyy) \
    _(GREEK, 0x10140, 0x1018f, Grek) \
    _(COMMON, 0x10190, 0x1019f, Zyyy) \
    _(GREEK, 0x101a0, 0x101cf, Grek) \
    _(COMMON, 0x101d0, 0x101fc, Zyyy) \
    _(INHERITED, 0x101fd, 0x1027f, Zinh) \
    _(LYCIAN, 0x10280, 0x1029f, Lyci) \
    _(CARIAN, 0x102a0, 0x102df, Cari) \
    _(INHERITED, 0x102e0, 0x102e0, Zinh) \
    _(COMMON, 0x102e1, 0x102ff, Zyyy) \
    _(OLD_ITALIC, 0x10300, 0x1032f, Ital) \
    _(GOTHIC, 0x10330, 0x1034f, Goth) \
    _(OLD_PERMIC, 0x10350, 0x1037f, Perm) \
    _(UGARITIC, 0x10380, 0x1039f, Ugar) \
    _(OLD_PERSIAN, 0x103a0, 0x103ff, Xpeo) \
    _(DESERET, 0x10400, 0x1044f, Dsrt) \
    _(SHAVIAN, 0x10450, 0x1047f, Shaw) \
    _(OSMANYA, 0x10480, 0x104af, Osma) \
    _(OSAGE, 0x104b0, 0x104ff, Osge) \
    _(ELBASAN, 0x10500, 0x1052f, Elba) \
    _(CAUCASIAN_ALBANIAN, 0x10530, 0x1056f, Aghb) \
    _(VITHKUQI, 0x10570, 0x105bf, Vith) \
    _(TODHRI, 0x105c0, 0x105ff, Todr) \
    _(LINEAR_A, 0x10600, 0x1077f, Lina) \
    _(LATIN, 0x10780, 0x107ff, Latn) \
    _(CYPRIOT, 0x10800, 0x1083f, Cprt) \
    _(IMPERIAL_ARAMAIC, 0x10840, 0x1085f, Armi) \
    _(PALMYRENE, 0x10860, 0x1087f, Palm) \
    _(NABATAEAN, 0x10880, 0x108df, Nbat) \
    _(HATRAN, 0x108e0, 0x108ff, Hatr) \
    _(PHOENICIAN, 0x10900, 0x1091f, Phnx) \
    _(LYDIAN, 0x10920, 0x1097f, Lydi) \
    _(MEROITIC_HIEROGLYPHS, 0x10980, 0x1099f, Mero) \
    _(MEROITIC_CURSIVE, 0x109a0, 0x109ff, Merc) \
    _(KHAROSHTHI, 0x10a00, 0x10a5f, Khar) \
    _(OLD_SOUTH_ARABIAN, 0x10a60, 0x10a7f, Sarb) \
    _(OLD_NORTH_ARABIAN, 0x10a80, 0x10abf, Narb) \
    _(MANICHAEAN, 0x10ac0, 0x10aff, Mani) \
    _(AVESTAN, 0x10b00, 0x10b3f, Avst) \
    _(INSCRIPTIONAL_PARTHIAN, 0x10b40, 0x10b5f, Prti) \
    _(INSCRIPTIONAL_PAHLAVI, 0x10b60, 0x10b7f, Phli) \
    _(PSALTER_PAHLAVI, 0x10b80, 0x10bff, Phlp) \
    _(OLD_TURKIC, 0x10c00, 0x10c7f, Orkh) \
    _(OLD_HUNGARIAN, 0x10c80, 0x10cff, Hung) \
    _(HANIFI_ROHINGYA, 0x10d00, 0x10d3f, Rohg) \
    _(GARAY, 0x10d40, 0x10e5f, Gara) \
    _(ARABIC, 0x10e60, 0x10e7f, Arab) \
    _(YEZIDI, 0x10e80, 0x10ec1, Yezi) \
    _(ARABIC, 0x10ec2, 0x10eff, Arab) \
    _(OLD_SOGDIAN, 0x10f00, 0x10f2f, Sogo) \
    _(SOGDIAN, 0x10f30, 0x10f6f, Sogd) \
    _(OLD_UYGHUR, 0x10f70, 0x10faf, Ougr) \
    _(CHORASMIAN, 0x10fb0, 0x10fdf, Chrs) \
    _(ELYMAIC, 0x10fe0, 0x10fff, Elym) \
    _(BRAHMI, 0x11000, 0x1107f, Brah) \
    _(KAITHI, 0x11080, 0x110cf, Kthi) \
    _(SORA_SOMPENG, 0x110d0, 0x110ff, Sora) \
    _(CHAKMA, 0x11100, 0x1114f, Cakm) \
    _(MAHAJANI, 0x11150, 0x1117f, Mahj) \
    _(SHARADA, 0x11180, 0x111e0, Shrd) \
    _(SINHALA, 0x111e1, 0x111ff, Sinh) \
    _(KHOJKI, 0x11200, 0x1127f, Khoj) \
    _(MULTANI, 0x11280, 0x112af, Mult) \
    _(KHUDAWADI, 0x112b0, 0x112ff, Sind) \
    _(GRANTHA, 0x11300, 0x1133a, Gran) \
    _(INHERITED, 0x1133b, 0x1133b, Zinh) \
    _(GRANTHA, 0x1133c, 0x1137f, Gran) \
    _(TULU_TIGALARI, 0x11380, 0x113ff, Tutg) \
    _(NEWA, 0x11400, 0x1147f, Newa) \
    _(TIRHUTA, 0x11480, 0x1157f, Tirh) \
    _(SIDDHAM, 0x11580, 0x115ff, Sidd) \
    _(MODI, 0x11600, 0x1165f, Modi) \
    _(MONGOLIAN, 0x11660, 0x1167f, Mong) \
    _(TAKRI, 0x11680, 0x116cf, Takr) \
    _(MYANMAR, 0x116d0, 0x116ff, Mymr) \
    _(AHOM, 0x11700, 0x117ff, Ahom) \
    _(DOGRA, 0x11800, 0x1189f, Dogr) \
    _(WARANG_CITI, 0x118a0, 0x118ff, Wara) \
    _(DIVES_AKURU, 0x11900, 0x1199f, Diak) \
    _(NANDINAGARI, 0x119a0, 0x119ff, Nand) \
    _(ZANABAZAR_SQUARE, 0x11a00, 0x11a4f, Zanb) \
    _(SOYOMBO, 0x11a50, 0x11aaf, Soyo) \
    _(CANADIAN_ABORIGINAL, 0x11ab0, 0x11abf, Cans) \
    _(PAU_CIN_HAU, 0x11ac0, 0x11aff, Pauc) \
    _(DEVANAGARI, 0x11b00, 0x11bbf, Deva) \
    _(SUNUWAR, 0x11bc0, 0x11bff, Sunu) \
    _(BHAIKSUKI, 0x11c00, 0x11c6f, Bhks) \
    _(MARCHEN, 0x11c70, 0x11cff, Marc) \
    _(MASARAM_GONDI, 0x11d00, 0x11d5f, Gonm) \
    _(GUNJALA_GONDI, 0x11d60, 0x11edf, Gong) \
    _(MAKASAR, 0x11ee0, 0x11eff, Maka) \
    _(KAWI, 0x11f00, 0x11faf, Kawi) \
    _(LISU, 0x11fb0, 0x11fbf, Lisu) \
    _(TAMIL, 0x11fc0, 0x11fff, Taml) \
    _(CUNEIFORM, 0x12000, 0x12f8f, Xsux) \
    _(CYPRO_MINOAN, 0x12f90, 0x12fff, Cpmn) \
    _(EGYPTIAN_HIEROGLYPHS, 0x13000, 0x143ff, Egyp) \
    _(ANATOLIAN_HIEROGLYPHS, 0x14400, 0x160ff, Hluw) \
    _(GURUNG_KHEMA, 0x16100, 0x167ff, Gukh) \
    _(BAMUM, 0x16800, 0x16a3f, Bamu) \
    _(MRO, 0x16a40, 0x16a6f, Mroo) \
    _(TANGSA, 0x16a70, 0x16acf, Tnsa) \
    _(BASSA_VAH, 0x16ad0, 0x16aff, Bass) \
    _(PAHAWH_HMONG, 0x16b00, 0x16d3f, Hmng) \
    _(KIRAT_RAI, 0x16d40, 0x16e3f, Krai) \
    _(MEDEFAIDRIN, 0x16e40, 0x16eff, Medf) \
    _(MIAO, 0x16f00, 0x16fdf, Plrd) \
    _(TANGUT, 0x16fe0, 0x16fe0, Tang) \
    _(NUSHU, 0x16fe1, 0x16fe1, Nshu) \
    _(HAN, 0x16fe2, 0x16fe3, Hani) \
    _(KHITAN_SMALL_SCRIPT, 0x16fe4, 0x16fef, Kits) \
    _(HAN, 0x16ff0, 0x16fff, Hani) \
    _(TANGUT, 0x17000, 0x18aff, Tang) \
    _(KHITAN_SMALL_SCRIPT, 0x18b00, 0x18cff, Kits) \
    _(TANGUT, 0x18d00, 0x1afef, Tang) \
    _(KATAKANA, 0x1aff0, 0x1b000, Kana) \
    _(HIRAGANA, 0x1b001, 0x1b11f, Hira) \
    _(KATAKANA, 0x1b120, 0x1b131, Kana) \
    _(HIRAGANA, 0x1b132, 0x1b154, Hira) \
    _(KATAKANA, 0x1b155, 0x1b16f, Kana) \
    _(NUSHU, 0x1b170, 0x1bbff, Nshu) \
    _(DUPLOYAN, 0x1bc00, 0x1bc9f, Dupl) \
    _(COMMON, 0x1bca0, 0x1ceff, Zyyy) \
    _(INHERITED, 0x1cf00, 0x1cf4f, Zinh) \
    _(COMMON, 0x1cf50, 0x1d166, Zyyy) \
    _(INHERITED, 0x1d167, 0x1d169, Zinh) \
    _(COMMON, 0x1d16a, 0x1d17a, Zyyy) \
    _(INHERITED, 0x1d17b, 0x1d182, Zinh) \
    _(COMMON, 0x1d183, 0x1d184, Zyyy) \
    _(INHERITED, 0x1d185, 0x1d18b, Zinh) \
    _(COMMON, 0x1d18c, 0x1d1a9, Zyyy) \
    _(INHERITED, 0x1d1aa, 0x1d1ad, Zinh) \
    _(COMMON, 0x1d1ae, 0x1d1ff, Zyyy) \
    _(GREEK, 0x1d200, 0x1d2bf, Grek) \
    _(COMMON, 0x1d2c0, 0x1d7ff, Zyyy) \
    _(SIGNWRITING, 0x1d800, 0x1deff, Sgnw) \
    _(LATIN, 0x1df00, 0x1dfff, Latn) \
    _(GLAGOLITIC, 0x1e000, 0x1e02f, Glag) \
    _(CYRILLIC, 0x1e030, 0x1e0ff, Cyrl) \
    _(NYIAKENG_PUACHUE_HMONG, 0x1e100, 0x1e28f, Hmnp) \
    _(TOTO, 0x1e290, 0x1e2bf, Toto) \
    _(WANCHO, 0x1e2c0, 0x1e4cf, Wcho) \
    _(NAG_MUNDARI, 0x1e4d0, 0x1e5cf, Nagm) \
    _(OL_ONAL, 0x1e5d0, 0x1e7df, Onao) \
    _(ETHIOPIC, 0x1e7e0, 0x1e7ff, Ethi) \
    _(MENDE_KIKAKUI, 0x1e800, 0x1e8ff, Mend) \
    _(ADLAM, 0x1e900, 0x1ec70, Adlm) \
    _(COMMON, 0x1ec71, 0x1edff, Zyyy) \
    _(ARABIC, 0x1ee00, 0x1efff, Arab) \
    _(COMMON, 0x1f000, 0x1f1ff, Zyyy) \
    _(HIRAGANA, 0x1f200, 0x1f200, Hira) \
    _(COMMON, 0x1f201, 0x1ffff, Zyyy) \
    _(HAN, 0x20000, 0xe0000, Hani) \
    _(COMMON, 0xe0001, 0xe00ff, Zyyy) \
    _(INHERITED, 0xe0100, 0xe01ef, Zinh) \

typedef enum {
#define X(name, ...) OC_CAT2(OC_UNICODE_SCRIPT_, name),
    OC_UNICODE_SCRIPTS(X)
#undef X
} oc_unicode_script;

typedef struct oc_unicode_script_range {
    u64 start;
    u64 end;
    oc_unicode_script script;
    oc_str8 tag;
} oc_unicode_script_range;

static const oc_unicode_script_range OC_UNICODE_SCRIPT_RANGES[] = {
    { 0x0, 0x40, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x41, 0x5a, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x5b, 0x60, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x61, 0x7a, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x7b, 0xa9, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xaa, 0xaa, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xab, 0xb9, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xba, 0xba, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xbb, 0xbf, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xc0, 0xd6, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xd7, 0xd7, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xd8, 0xf6, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xf7, 0xf7, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xf8, 0x2b8, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x2b9, 0x2df, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2e0, 0x2e4, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x2e5, 0x2e9, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2ea, 0x2eb, OC_UNICODE_SCRIPT_BOPOMOFO, OC_STR8_LIT("Bopo") },
    { 0x2ec, 0x2ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x300, 0x36f, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x370, 0x373, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x374, 0x374, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x375, 0x37d, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x37e, 0x37e, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x37f, 0x384, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x385, 0x385, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x386, 0x386, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x387, 0x387, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x388, 0x3e1, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x3e2, 0x3ef, OC_UNICODE_SCRIPT_COPTIC, OC_STR8_LIT("Copt") },
    { 0x3f0, 0x3ff, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x400, 0x484, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0x485, 0x486, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x487, 0x530, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0x531, 0x590, OC_UNICODE_SCRIPT_ARMENIAN, OC_STR8_LIT("Armn") },
    { 0x591, 0x5ff, OC_UNICODE_SCRIPT_HEBREW, OC_STR8_LIT("Hebr") },
    { 0x600, 0x604, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x605, 0x605, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x606, 0x60b, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x60c, 0x60c, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x60d, 0x61a, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x61b, 0x61b, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x61c, 0x61e, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x61f, 0x61f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x620, 0x63f, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x640, 0x640, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x641, 0x64a, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x64b, 0x655, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x656, 0x66f, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x670, 0x670, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x671, 0x6dc, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x6dd, 0x6dd, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x6de, 0x6ff, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x700, 0x74f, OC_UNICODE_SCRIPT_SYRIAC, OC_STR8_LIT("Syrc") },
    { 0x750, 0x77f, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x780, 0x7bf, OC_UNICODE_SCRIPT_THAANA, OC_STR8_LIT("Thaa") },
    { 0x7c0, 0x7ff, OC_UNICODE_SCRIPT_NKO, OC_STR8_LIT("Nkoo") },
    { 0x800, 0x83f, OC_UNICODE_SCRIPT_SAMARITAN, OC_STR8_LIT("Samr") },
    { 0x840, 0x85f, OC_UNICODE_SCRIPT_MANDAIC, OC_STR8_LIT("Mand") },
    { 0x860, 0x86f, OC_UNICODE_SCRIPT_SYRIAC, OC_STR8_LIT("Syrc") },
    { 0x870, 0x8e1, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x8e2, 0x8e2, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x8e3, 0x8ff, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x900, 0x950, OC_UNICODE_SCRIPT_DEVANAGARI, OC_STR8_LIT("Deva") },
    { 0x951, 0x954, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x955, 0x963, OC_UNICODE_SCRIPT_DEVANAGARI, OC_STR8_LIT("Deva") },
    { 0x964, 0x965, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x966, 0x97f, OC_UNICODE_SCRIPT_DEVANAGARI, OC_STR8_LIT("Deva") },
    { 0x980, 0xa00, OC_UNICODE_SCRIPT_BENGALI, OC_STR8_LIT("Beng") },
    { 0xa01, 0xa80, OC_UNICODE_SCRIPT_GURMUKHI, OC_STR8_LIT("Guru") },
    { 0xa81, 0xb00, OC_UNICODE_SCRIPT_GUJARATI, OC_STR8_LIT("Gujr") },
    { 0xb01, 0xb81, OC_UNICODE_SCRIPT_ORIYA, OC_STR8_LIT("Orya") },
    { 0xb82, 0xbff, OC_UNICODE_SCRIPT_TAMIL, OC_STR8_LIT("Taml") },
    { 0xc00, 0xc7f, OC_UNICODE_SCRIPT_TELUGU, OC_STR8_LIT("Telu") },
    { 0xc80, 0xcff, OC_UNICODE_SCRIPT_KANNADA, OC_STR8_LIT("Knda") },
    { 0xd00, 0xd80, OC_UNICODE_SCRIPT_MALAYALAM, OC_STR8_LIT("Mlym") },
    { 0xd81, 0xe00, OC_UNICODE_SCRIPT_SINHALA, OC_STR8_LIT("Sinh") },
    { 0xe01, 0xe3e, OC_UNICODE_SCRIPT_THAI, OC_STR8_LIT("Thai") },
    { 0xe3f, 0xe3f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xe40, 0xe80, OC_UNICODE_SCRIPT_THAI, OC_STR8_LIT("Thai") },
    { 0xe81, 0xeff, OC_UNICODE_SCRIPT_LAO, OC_STR8_LIT("Laoo") },
    { 0xf00, 0xfd4, OC_UNICODE_SCRIPT_TIBETAN, OC_STR8_LIT("Tibt") },
    { 0xfd5, 0xfd8, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xfd9, 0xfff, OC_UNICODE_SCRIPT_TIBETAN, OC_STR8_LIT("Tibt") },
    { 0x1000, 0x109f, OC_UNICODE_SCRIPT_MYANMAR, OC_STR8_LIT("Mymr") },
    { 0x10a0, 0x10fa, OC_UNICODE_SCRIPT_GEORGIAN, OC_STR8_LIT("Geor") },
    { 0x10fb, 0x10fb, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x10fc, 0x10ff, OC_UNICODE_SCRIPT_GEORGIAN, OC_STR8_LIT("Geor") },
    { 0x1100, 0x11ff, OC_UNICODE_SCRIPT_HANGUL, OC_STR8_LIT("Hang") },
    { 0x1200, 0x139f, OC_UNICODE_SCRIPT_ETHIOPIC, OC_STR8_LIT("Ethi") },
    { 0x13a0, 0x13ff, OC_UNICODE_SCRIPT_CHEROKEE, OC_STR8_LIT("Cher") },
    { 0x1400, 0x167f, OC_UNICODE_SCRIPT_CANADIAN_ABORIGINAL, OC_STR8_LIT("Cans") },
    { 0x1680, 0x169f, OC_UNICODE_SCRIPT_OGHAM, OC_STR8_LIT("Ogam") },
    { 0x16a0, 0x16ea, OC_UNICODE_SCRIPT_RUNIC, OC_STR8_LIT("Runr") },
    { 0x16eb, 0x16ed, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x16ee, 0x16ff, OC_UNICODE_SCRIPT_RUNIC, OC_STR8_LIT("Runr") },
    { 0x1700, 0x171f, OC_UNICODE_SCRIPT_TAGALOG, OC_STR8_LIT("Tglg") },
    { 0x1720, 0x1734, OC_UNICODE_SCRIPT_HANUNOO, OC_STR8_LIT("Hano") },
    { 0x1735, 0x173f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1740, 0x175f, OC_UNICODE_SCRIPT_BUHID, OC_STR8_LIT("Buhd") },
    { 0x1760, 0x177f, OC_UNICODE_SCRIPT_TAGBANWA, OC_STR8_LIT("Tagb") },
    { 0x1780, 0x17ff, OC_UNICODE_SCRIPT_KHMER, OC_STR8_LIT("Khmr") },
    { 0x1800, 0x1801, OC_UNICODE_SCRIPT_MONGOLIAN, OC_STR8_LIT("Mong") },
    { 0x1802, 0x1803, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1804, 0x1804, OC_UNICODE_SCRIPT_MONGOLIAN, OC_STR8_LIT("Mong") },
    { 0x1805, 0x1805, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1806, 0x18af, OC_UNICODE_SCRIPT_MONGOLIAN, OC_STR8_LIT("Mong") },
    { 0x18b0, 0x18ff, OC_UNICODE_SCRIPT_CANADIAN_ABORIGINAL, OC_STR8_LIT("Cans") },
    { 0x1900, 0x194f, OC_UNICODE_SCRIPT_LIMBU, OC_STR8_LIT("Limb") },
    { 0x1950, 0x197f, OC_UNICODE_SCRIPT_TAI_LE, OC_STR8_LIT("Tale") },
    { 0x1980, 0x19df, OC_UNICODE_SCRIPT_NEW_TAI_LUE, OC_STR8_LIT("Talu") },
    { 0x19e0, 0x19ff, OC_UNICODE_SCRIPT_KHMER, OC_STR8_LIT("Khmr") },
    { 0x1a00, 0x1a1f, OC_UNICODE_SCRIPT_BUGINESE, OC_STR8_LIT("Bugi") },
    { 0x1a20, 0x1aaf, OC_UNICODE_SCRIPT_TAI_THAM, OC_STR8_LIT("Lana") },
    { 0x1ab0, 0x1aff, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1b00, 0x1b7f, OC_UNICODE_SCRIPT_BALINESE, OC_STR8_LIT("Bali") },
    { 0x1b80, 0x1bbf, OC_UNICODE_SCRIPT_SUNDANESE, OC_STR8_LIT("Sund") },
    { 0x1bc0, 0x1bff, OC_UNICODE_SCRIPT_BATAK, OC_STR8_LIT("Batk") },
    { 0x1c00, 0x1c4f, OC_UNICODE_SCRIPT_LEPCHA, OC_STR8_LIT("Lepc") },
    { 0x1c50, 0x1c7f, OC_UNICODE_SCRIPT_OL_CHIKI, OC_STR8_LIT("Olck") },
    { 0x1c80, 0x1c8f, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0x1c90, 0x1cbf, OC_UNICODE_SCRIPT_GEORGIAN, OC_STR8_LIT("Geor") },
    { 0x1cc0, 0x1ccf, OC_UNICODE_SCRIPT_SUNDANESE, OC_STR8_LIT("Sund") },
    { 0x1cd0, 0x1cd2, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1cd3, 0x1cd3, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1cd4, 0x1ce0, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1ce1, 0x1ce1, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1ce2, 0x1ce8, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1ce9, 0x1cec, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1ced, 0x1ced, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1cee, 0x1cf3, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1cf4, 0x1cf4, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1cf5, 0x1cf7, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1cf8, 0x1cf9, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1cfa, 0x1cff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1d00, 0x1d25, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x1d26, 0x1d2a, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x1d2b, 0x1d2b, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0x1d2c, 0x1d5c, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x1d5d, 0x1d61, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x1d62, 0x1d65, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x1d66, 0x1d6a, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x1d6b, 0x1d77, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x1d78, 0x1d78, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0x1d79, 0x1dbe, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x1dbf, 0x1dbf, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x1dc0, 0x1dff, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1e00, 0x1eff, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x1f00, 0x1fff, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x2000, 0x200b, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x200c, 0x200d, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x200e, 0x2070, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2071, 0x2073, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x2074, 0x207e, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x207f, 0x207f, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x2080, 0x208f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2090, 0x209f, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x20a0, 0x20cf, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x20d0, 0x20ff, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x2100, 0x2125, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2126, 0x2126, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x2127, 0x2129, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x212a, 0x212b, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x212c, 0x2131, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2132, 0x2132, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x2133, 0x214d, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x214e, 0x214e, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x214f, 0x215f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2160, 0x2188, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x2189, 0x27ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2800, 0x28ff, OC_UNICODE_SCRIPT_BRAILLE, OC_STR8_LIT("Brai") },
    { 0x2900, 0x2bff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2c00, 0x2c5f, OC_UNICODE_SCRIPT_GLAGOLITIC, OC_STR8_LIT("Glag") },
    { 0x2c60, 0x2c7f, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x2c80, 0x2cff, OC_UNICODE_SCRIPT_COPTIC, OC_STR8_LIT("Copt") },
    { 0x2d00, 0x2d2f, OC_UNICODE_SCRIPT_GEORGIAN, OC_STR8_LIT("Geor") },
    { 0x2d30, 0x2d7f, OC_UNICODE_SCRIPT_TIFINAGH, OC_STR8_LIT("Tfng") },
    { 0x2d80, 0x2ddf, OC_UNICODE_SCRIPT_ETHIOPIC, OC_STR8_LIT("Ethi") },
    { 0x2de0, 0x2dff, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0x2e00, 0x2e7f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x2e80, 0x2fef, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0x2ff0, 0x3004, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x3005, 0x3005, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0x3006, 0x3006, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x3007, 0x3007, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0x3008, 0x3020, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x3021, 0x3029, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0x302a, 0x302d, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x302e, 0x302f, OC_UNICODE_SCRIPT_HANGUL, OC_STR8_LIT("Hang") },
    { 0x3030, 0x3037, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x3038, 0x303b, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0x303c, 0x3040, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x3041, 0x3098, OC_UNICODE_SCRIPT_HIRAGANA, OC_STR8_LIT("Hira") },
    { 0x3099, 0x309a, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x309b, 0x309c, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x309d, 0x309f, OC_UNICODE_SCRIPT_HIRAGANA, OC_STR8_LIT("Hira") },
    { 0x30a0, 0x30a0, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x30a1, 0x30fa, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0x30fb, 0x30fc, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x30fd, 0x3104, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0x3105, 0x3130, OC_UNICODE_SCRIPT_BOPOMOFO, OC_STR8_LIT("Bopo") },
    { 0x3131, 0x318f, OC_UNICODE_SCRIPT_HANGUL, OC_STR8_LIT("Hang") },
    { 0x3190, 0x319f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x31a0, 0x31bf, OC_UNICODE_SCRIPT_BOPOMOFO, OC_STR8_LIT("Bopo") },
    { 0x31c0, 0x31ef, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x31f0, 0x31ff, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0x3200, 0x321f, OC_UNICODE_SCRIPT_HANGUL, OC_STR8_LIT("Hang") },
    { 0x3220, 0x325f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x3260, 0x327e, OC_UNICODE_SCRIPT_HANGUL, OC_STR8_LIT("Hang") },
    { 0x327f, 0x32cf, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x32d0, 0x32fe, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0x32ff, 0x32ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x3300, 0x3357, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0x3358, 0x33ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x3400, 0x4dbf, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0x4dc0, 0x4dff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x4e00, 0x9fff, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0xa000, 0xa4cf, OC_UNICODE_SCRIPT_YI, OC_STR8_LIT("Yiii") },
    { 0xa4d0, 0xa4ff, OC_UNICODE_SCRIPT_LISU, OC_STR8_LIT("Lisu") },
    { 0xa500, 0xa63f, OC_UNICODE_SCRIPT_VAI, OC_STR8_LIT("Vaii") },
    { 0xa640, 0xa69f, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0xa6a0, 0xa6ff, OC_UNICODE_SCRIPT_BAMUM, OC_STR8_LIT("Bamu") },
    { 0xa700, 0xa721, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xa722, 0xa787, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xa788, 0xa78a, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xa78b, 0xa7ff, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xa800, 0xa82f, OC_UNICODE_SCRIPT_SYLOTI_NAGRI, OC_STR8_LIT("Sylo") },
    { 0xa830, 0xa83f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xa840, 0xa87f, OC_UNICODE_SCRIPT_PHAGS_PA, OC_STR8_LIT("Phag") },
    { 0xa880, 0xa8df, OC_UNICODE_SCRIPT_SAURASHTRA, OC_STR8_LIT("Saur") },
    { 0xa8e0, 0xa8ff, OC_UNICODE_SCRIPT_DEVANAGARI, OC_STR8_LIT("Deva") },
    { 0xa900, 0xa92d, OC_UNICODE_SCRIPT_KAYAH_LI, OC_STR8_LIT("Kali") },
    { 0xa92e, 0xa92e, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xa92f, 0xa92f, OC_UNICODE_SCRIPT_KAYAH_LI, OC_STR8_LIT("Kali") },
    { 0xa930, 0xa95f, OC_UNICODE_SCRIPT_REJANG, OC_STR8_LIT("Rjng") },
    { 0xa960, 0xa97f, OC_UNICODE_SCRIPT_HANGUL, OC_STR8_LIT("Hang") },
    { 0xa980, 0xa9ce, OC_UNICODE_SCRIPT_JAVANESE, OC_STR8_LIT("Java") },
    { 0xa9cf, 0xa9cf, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xa9d0, 0xa9df, OC_UNICODE_SCRIPT_JAVANESE, OC_STR8_LIT("Java") },
    { 0xa9e0, 0xa9ff, OC_UNICODE_SCRIPT_MYANMAR, OC_STR8_LIT("Mymr") },
    { 0xaa00, 0xaa5f, OC_UNICODE_SCRIPT_CHAM, OC_STR8_LIT("Cham") },
    { 0xaa60, 0xaa7f, OC_UNICODE_SCRIPT_MYANMAR, OC_STR8_LIT("Mymr") },
    { 0xaa80, 0xaadf, OC_UNICODE_SCRIPT_TAI_VIET, OC_STR8_LIT("Tavt") },
    { 0xaae0, 0xab00, OC_UNICODE_SCRIPT_MEETEI_MAYEK, OC_STR8_LIT("Mtei") },
    { 0xab01, 0xab2f, OC_UNICODE_SCRIPT_ETHIOPIC, OC_STR8_LIT("Ethi") },
    { 0xab30, 0xab5a, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xab5b, 0xab5b, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xab5c, 0xab64, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xab65, 0xab65, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0xab66, 0xab69, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xab6a, 0xab6f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xab70, 0xabbf, OC_UNICODE_SCRIPT_CHEROKEE, OC_STR8_LIT("Cher") },
    { 0xabc0, 0xabff, OC_UNICODE_SCRIPT_MEETEI_MAYEK, OC_STR8_LIT("Mtei") },
    { 0xac00, 0xf8ff, OC_UNICODE_SCRIPT_HANGUL, OC_STR8_LIT("Hang") },
    { 0xf900, 0xfaff, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0xfb00, 0xfb12, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xfb13, 0xfb1c, OC_UNICODE_SCRIPT_ARMENIAN, OC_STR8_LIT("Armn") },
    { 0xfb1d, 0xfb4f, OC_UNICODE_SCRIPT_HEBREW, OC_STR8_LIT("Hebr") },
    { 0xfb50, 0xfd3d, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0xfd3e, 0xfd3f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xfd40, 0xfdff, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0xfe00, 0xfe0f, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0xfe10, 0xfe1f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xfe20, 0xfe2d, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0xfe2e, 0xfe2f, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0xfe30, 0xfe6f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xfe70, 0xfefe, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0xfeff, 0xff20, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xff21, 0xff3a, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xff3b, 0xff40, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xff41, 0xff5a, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0xff5b, 0xff65, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xff66, 0xff6f, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0xff70, 0xff70, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xff71, 0xff9d, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0xff9e, 0xff9f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xffa0, 0xffdf, OC_UNICODE_SCRIPT_HANGUL, OC_STR8_LIT("Hang") },
    { 0xffe0, 0xffff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x10000, 0x100ff, OC_UNICODE_SCRIPT_LINEAR_B, OC_STR8_LIT("Linb") },
    { 0x10100, 0x1013f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x10140, 0x1018f, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x10190, 0x1019f, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x101a0, 0x101cf, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x101d0, 0x101fc, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x101fd, 0x1027f, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x10280, 0x1029f, OC_UNICODE_SCRIPT_LYCIAN, OC_STR8_LIT("Lyci") },
    { 0x102a0, 0x102df, OC_UNICODE_SCRIPT_CARIAN, OC_STR8_LIT("Cari") },
    { 0x102e0, 0x102e0, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x102e1, 0x102ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x10300, 0x1032f, OC_UNICODE_SCRIPT_OLD_ITALIC, OC_STR8_LIT("Ital") },
    { 0x10330, 0x1034f, OC_UNICODE_SCRIPT_GOTHIC, OC_STR8_LIT("Goth") },
    { 0x10350, 0x1037f, OC_UNICODE_SCRIPT_OLD_PERMIC, OC_STR8_LIT("Perm") },
    { 0x10380, 0x1039f, OC_UNICODE_SCRIPT_UGARITIC, OC_STR8_LIT("Ugar") },
    { 0x103a0, 0x103ff, OC_UNICODE_SCRIPT_OLD_PERSIAN, OC_STR8_LIT("Xpeo") },
    { 0x10400, 0x1044f, OC_UNICODE_SCRIPT_DESERET, OC_STR8_LIT("Dsrt") },
    { 0x10450, 0x1047f, OC_UNICODE_SCRIPT_SHAVIAN, OC_STR8_LIT("Shaw") },
    { 0x10480, 0x104af, OC_UNICODE_SCRIPT_OSMANYA, OC_STR8_LIT("Osma") },
    { 0x104b0, 0x104ff, OC_UNICODE_SCRIPT_OSAGE, OC_STR8_LIT("Osge") },
    { 0x10500, 0x1052f, OC_UNICODE_SCRIPT_ELBASAN, OC_STR8_LIT("Elba") },
    { 0x10530, 0x1056f, OC_UNICODE_SCRIPT_CAUCASIAN_ALBANIAN, OC_STR8_LIT("Aghb") },
    { 0x10570, 0x105bf, OC_UNICODE_SCRIPT_VITHKUQI, OC_STR8_LIT("Vith") },
    { 0x105c0, 0x105ff, OC_UNICODE_SCRIPT_TODHRI, OC_STR8_LIT("Todr") },
    { 0x10600, 0x1077f, OC_UNICODE_SCRIPT_LINEAR_A, OC_STR8_LIT("Lina") },
    { 0x10780, 0x107ff, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x10800, 0x1083f, OC_UNICODE_SCRIPT_CYPRIOT, OC_STR8_LIT("Cprt") },
    { 0x10840, 0x1085f, OC_UNICODE_SCRIPT_IMPERIAL_ARAMAIC, OC_STR8_LIT("Armi") },
    { 0x10860, 0x1087f, OC_UNICODE_SCRIPT_PALMYRENE, OC_STR8_LIT("Palm") },
    { 0x10880, 0x108df, OC_UNICODE_SCRIPT_NABATAEAN, OC_STR8_LIT("Nbat") },
    { 0x108e0, 0x108ff, OC_UNICODE_SCRIPT_HATRAN, OC_STR8_LIT("Hatr") },
    { 0x10900, 0x1091f, OC_UNICODE_SCRIPT_PHOENICIAN, OC_STR8_LIT("Phnx") },
    { 0x10920, 0x1097f, OC_UNICODE_SCRIPT_LYDIAN, OC_STR8_LIT("Lydi") },
    { 0x10980, 0x1099f, OC_UNICODE_SCRIPT_MEROITIC_HIEROGLYPHS, OC_STR8_LIT("Mero") },
    { 0x109a0, 0x109ff, OC_UNICODE_SCRIPT_MEROITIC_CURSIVE, OC_STR8_LIT("Merc") },
    { 0x10a00, 0x10a5f, OC_UNICODE_SCRIPT_KHAROSHTHI, OC_STR8_LIT("Khar") },
    { 0x10a60, 0x10a7f, OC_UNICODE_SCRIPT_OLD_SOUTH_ARABIAN, OC_STR8_LIT("Sarb") },
    { 0x10a80, 0x10abf, OC_UNICODE_SCRIPT_OLD_NORTH_ARABIAN, OC_STR8_LIT("Narb") },
    { 0x10ac0, 0x10aff, OC_UNICODE_SCRIPT_MANICHAEAN, OC_STR8_LIT("Mani") },
    { 0x10b00, 0x10b3f, OC_UNICODE_SCRIPT_AVESTAN, OC_STR8_LIT("Avst") },
    { 0x10b40, 0x10b5f, OC_UNICODE_SCRIPT_INSCRIPTIONAL_PARTHIAN, OC_STR8_LIT("Prti") },
    { 0x10b60, 0x10b7f, OC_UNICODE_SCRIPT_INSCRIPTIONAL_PAHLAVI, OC_STR8_LIT("Phli") },
    { 0x10b80, 0x10bff, OC_UNICODE_SCRIPT_PSALTER_PAHLAVI, OC_STR8_LIT("Phlp") },
    { 0x10c00, 0x10c7f, OC_UNICODE_SCRIPT_OLD_TURKIC, OC_STR8_LIT("Orkh") },
    { 0x10c80, 0x10cff, OC_UNICODE_SCRIPT_OLD_HUNGARIAN, OC_STR8_LIT("Hung") },
    { 0x10d00, 0x10d3f, OC_UNICODE_SCRIPT_HANIFI_ROHINGYA, OC_STR8_LIT("Rohg") },
    { 0x10d40, 0x10e5f, OC_UNICODE_SCRIPT_GARAY, OC_STR8_LIT("Gara") },
    { 0x10e60, 0x10e7f, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x10e80, 0x10ec1, OC_UNICODE_SCRIPT_YEZIDI, OC_STR8_LIT("Yezi") },
    { 0x10ec2, 0x10eff, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x10f00, 0x10f2f, OC_UNICODE_SCRIPT_OLD_SOGDIAN, OC_STR8_LIT("Sogo") },
    { 0x10f30, 0x10f6f, OC_UNICODE_SCRIPT_SOGDIAN, OC_STR8_LIT("Sogd") },
    { 0x10f70, 0x10faf, OC_UNICODE_SCRIPT_OLD_UYGHUR, OC_STR8_LIT("Ougr") },
    { 0x10fb0, 0x10fdf, OC_UNICODE_SCRIPT_CHORASMIAN, OC_STR8_LIT("Chrs") },
    { 0x10fe0, 0x10fff, OC_UNICODE_SCRIPT_ELYMAIC, OC_STR8_LIT("Elym") },
    { 0x11000, 0x1107f, OC_UNICODE_SCRIPT_BRAHMI, OC_STR8_LIT("Brah") },
    { 0x11080, 0x110cf, OC_UNICODE_SCRIPT_KAITHI, OC_STR8_LIT("Kthi") },
    { 0x110d0, 0x110ff, OC_UNICODE_SCRIPT_SORA_SOMPENG, OC_STR8_LIT("Sora") },
    { 0x11100, 0x1114f, OC_UNICODE_SCRIPT_CHAKMA, OC_STR8_LIT("Cakm") },
    { 0x11150, 0x1117f, OC_UNICODE_SCRIPT_MAHAJANI, OC_STR8_LIT("Mahj") },
    { 0x11180, 0x111e0, OC_UNICODE_SCRIPT_SHARADA, OC_STR8_LIT("Shrd") },
    { 0x111e1, 0x111ff, OC_UNICODE_SCRIPT_SINHALA, OC_STR8_LIT("Sinh") },
    { 0x11200, 0x1127f, OC_UNICODE_SCRIPT_KHOJKI, OC_STR8_LIT("Khoj") },
    { 0x11280, 0x112af, OC_UNICODE_SCRIPT_MULTANI, OC_STR8_LIT("Mult") },
    { 0x112b0, 0x112ff, OC_UNICODE_SCRIPT_KHUDAWADI, OC_STR8_LIT("Sind") },
    { 0x11300, 0x1133a, OC_UNICODE_SCRIPT_GRANTHA, OC_STR8_LIT("Gran") },
    { 0x1133b, 0x1133b, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1133c, 0x1137f, OC_UNICODE_SCRIPT_GRANTHA, OC_STR8_LIT("Gran") },
    { 0x11380, 0x113ff, OC_UNICODE_SCRIPT_TULU_TIGALARI, OC_STR8_LIT("Tutg") },
    { 0x11400, 0x1147f, OC_UNICODE_SCRIPT_NEWA, OC_STR8_LIT("Newa") },
    { 0x11480, 0x1157f, OC_UNICODE_SCRIPT_TIRHUTA, OC_STR8_LIT("Tirh") },
    { 0x11580, 0x115ff, OC_UNICODE_SCRIPT_SIDDHAM, OC_STR8_LIT("Sidd") },
    { 0x11600, 0x1165f, OC_UNICODE_SCRIPT_MODI, OC_STR8_LIT("Modi") },
    { 0x11660, 0x1167f, OC_UNICODE_SCRIPT_MONGOLIAN, OC_STR8_LIT("Mong") },
    { 0x11680, 0x116cf, OC_UNICODE_SCRIPT_TAKRI, OC_STR8_LIT("Takr") },
    { 0x116d0, 0x116ff, OC_UNICODE_SCRIPT_MYANMAR, OC_STR8_LIT("Mymr") },
    { 0x11700, 0x117ff, OC_UNICODE_SCRIPT_AHOM, OC_STR8_LIT("Ahom") },
    { 0x11800, 0x1189f, OC_UNICODE_SCRIPT_DOGRA, OC_STR8_LIT("Dogr") },
    { 0x118a0, 0x118ff, OC_UNICODE_SCRIPT_WARANG_CITI, OC_STR8_LIT("Wara") },
    { 0x11900, 0x1199f, OC_UNICODE_SCRIPT_DIVES_AKURU, OC_STR8_LIT("Diak") },
    { 0x119a0, 0x119ff, OC_UNICODE_SCRIPT_NANDINAGARI, OC_STR8_LIT("Nand") },
    { 0x11a00, 0x11a4f, OC_UNICODE_SCRIPT_ZANABAZAR_SQUARE, OC_STR8_LIT("Zanb") },
    { 0x11a50, 0x11aaf, OC_UNICODE_SCRIPT_SOYOMBO, OC_STR8_LIT("Soyo") },
    { 0x11ab0, 0x11abf, OC_UNICODE_SCRIPT_CANADIAN_ABORIGINAL, OC_STR8_LIT("Cans") },
    { 0x11ac0, 0x11aff, OC_UNICODE_SCRIPT_PAU_CIN_HAU, OC_STR8_LIT("Pauc") },
    { 0x11b00, 0x11bbf, OC_UNICODE_SCRIPT_DEVANAGARI, OC_STR8_LIT("Deva") },
    { 0x11bc0, 0x11bff, OC_UNICODE_SCRIPT_SUNUWAR, OC_STR8_LIT("Sunu") },
    { 0x11c00, 0x11c6f, OC_UNICODE_SCRIPT_BHAIKSUKI, OC_STR8_LIT("Bhks") },
    { 0x11c70, 0x11cff, OC_UNICODE_SCRIPT_MARCHEN, OC_STR8_LIT("Marc") },
    { 0x11d00, 0x11d5f, OC_UNICODE_SCRIPT_MASARAM_GONDI, OC_STR8_LIT("Gonm") },
    { 0x11d60, 0x11edf, OC_UNICODE_SCRIPT_GUNJALA_GONDI, OC_STR8_LIT("Gong") },
    { 0x11ee0, 0x11eff, OC_UNICODE_SCRIPT_MAKASAR, OC_STR8_LIT("Maka") },
    { 0x11f00, 0x11faf, OC_UNICODE_SCRIPT_KAWI, OC_STR8_LIT("Kawi") },
    { 0x11fb0, 0x11fbf, OC_UNICODE_SCRIPT_LISU, OC_STR8_LIT("Lisu") },
    { 0x11fc0, 0x11fff, OC_UNICODE_SCRIPT_TAMIL, OC_STR8_LIT("Taml") },
    { 0x12000, 0x12f8f, OC_UNICODE_SCRIPT_CUNEIFORM, OC_STR8_LIT("Xsux") },
    { 0x12f90, 0x12fff, OC_UNICODE_SCRIPT_CYPRO_MINOAN, OC_STR8_LIT("Cpmn") },
    { 0x13000, 0x143ff, OC_UNICODE_SCRIPT_EGYPTIAN_HIEROGLYPHS, OC_STR8_LIT("Egyp") },
    { 0x14400, 0x160ff, OC_UNICODE_SCRIPT_ANATOLIAN_HIEROGLYPHS, OC_STR8_LIT("Hluw") },
    { 0x16100, 0x167ff, OC_UNICODE_SCRIPT_GURUNG_KHEMA, OC_STR8_LIT("Gukh") },
    { 0x16800, 0x16a3f, OC_UNICODE_SCRIPT_BAMUM, OC_STR8_LIT("Bamu") },
    { 0x16a40, 0x16a6f, OC_UNICODE_SCRIPT_MRO, OC_STR8_LIT("Mroo") },
    { 0x16a70, 0x16acf, OC_UNICODE_SCRIPT_TANGSA, OC_STR8_LIT("Tnsa") },
    { 0x16ad0, 0x16aff, OC_UNICODE_SCRIPT_BASSA_VAH, OC_STR8_LIT("Bass") },
    { 0x16b00, 0x16d3f, OC_UNICODE_SCRIPT_PAHAWH_HMONG, OC_STR8_LIT("Hmng") },
    { 0x16d40, 0x16e3f, OC_UNICODE_SCRIPT_KIRAT_RAI, OC_STR8_LIT("Krai") },
    { 0x16e40, 0x16eff, OC_UNICODE_SCRIPT_MEDEFAIDRIN, OC_STR8_LIT("Medf") },
    { 0x16f00, 0x16fdf, OC_UNICODE_SCRIPT_MIAO, OC_STR8_LIT("Plrd") },
    { 0x16fe0, 0x16fe0, OC_UNICODE_SCRIPT_TANGUT, OC_STR8_LIT("Tang") },
    { 0x16fe1, 0x16fe1, OC_UNICODE_SCRIPT_NUSHU, OC_STR8_LIT("Nshu") },
    { 0x16fe2, 0x16fe3, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0x16fe4, 0x16fef, OC_UNICODE_SCRIPT_KHITAN_SMALL_SCRIPT, OC_STR8_LIT("Kits") },
    { 0x16ff0, 0x16fff, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0x17000, 0x18aff, OC_UNICODE_SCRIPT_TANGUT, OC_STR8_LIT("Tang") },
    { 0x18b00, 0x18cff, OC_UNICODE_SCRIPT_KHITAN_SMALL_SCRIPT, OC_STR8_LIT("Kits") },
    { 0x18d00, 0x1afef, OC_UNICODE_SCRIPT_TANGUT, OC_STR8_LIT("Tang") },
    { 0x1aff0, 0x1b000, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0x1b001, 0x1b11f, OC_UNICODE_SCRIPT_HIRAGANA, OC_STR8_LIT("Hira") },
    { 0x1b120, 0x1b131, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0x1b132, 0x1b154, OC_UNICODE_SCRIPT_HIRAGANA, OC_STR8_LIT("Hira") },
    { 0x1b155, 0x1b16f, OC_UNICODE_SCRIPT_KATAKANA, OC_STR8_LIT("Kana") },
    { 0x1b170, 0x1bbff, OC_UNICODE_SCRIPT_NUSHU, OC_STR8_LIT("Nshu") },
    { 0x1bc00, 0x1bc9f, OC_UNICODE_SCRIPT_DUPLOYAN, OC_STR8_LIT("Dupl") },
    { 0x1bca0, 0x1ceff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1cf00, 0x1cf4f, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1cf50, 0x1d166, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1d167, 0x1d169, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1d16a, 0x1d17a, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1d17b, 0x1d182, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1d183, 0x1d184, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1d185, 0x1d18b, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1d18c, 0x1d1a9, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1d1aa, 0x1d1ad, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
    { 0x1d1ae, 0x1d1ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1d200, 0x1d2bf, OC_UNICODE_SCRIPT_GREEK, OC_STR8_LIT("Grek") },
    { 0x1d2c0, 0x1d7ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1d800, 0x1deff, OC_UNICODE_SCRIPT_SIGNWRITING, OC_STR8_LIT("Sgnw") },
    { 0x1df00, 0x1dfff, OC_UNICODE_SCRIPT_LATIN, OC_STR8_LIT("Latn") },
    { 0x1e000, 0x1e02f, OC_UNICODE_SCRIPT_GLAGOLITIC, OC_STR8_LIT("Glag") },
    { 0x1e030, 0x1e0ff, OC_UNICODE_SCRIPT_CYRILLIC, OC_STR8_LIT("Cyrl") },
    { 0x1e100, 0x1e28f, OC_UNICODE_SCRIPT_NYIAKENG_PUACHUE_HMONG, OC_STR8_LIT("Hmnp") },
    { 0x1e290, 0x1e2bf, OC_UNICODE_SCRIPT_TOTO, OC_STR8_LIT("Toto") },
    { 0x1e2c0, 0x1e4cf, OC_UNICODE_SCRIPT_WANCHO, OC_STR8_LIT("Wcho") },
    { 0x1e4d0, 0x1e5cf, OC_UNICODE_SCRIPT_NAG_MUNDARI, OC_STR8_LIT("Nagm") },
    { 0x1e5d0, 0x1e7df, OC_UNICODE_SCRIPT_OL_ONAL, OC_STR8_LIT("Onao") },
    { 0x1e7e0, 0x1e7ff, OC_UNICODE_SCRIPT_ETHIOPIC, OC_STR8_LIT("Ethi") },
    { 0x1e800, 0x1e8ff, OC_UNICODE_SCRIPT_MENDE_KIKAKUI, OC_STR8_LIT("Mend") },
    { 0x1e900, 0x1ec70, OC_UNICODE_SCRIPT_ADLAM, OC_STR8_LIT("Adlm") },
    { 0x1ec71, 0x1edff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1ee00, 0x1efff, OC_UNICODE_SCRIPT_ARABIC, OC_STR8_LIT("Arab") },
    { 0x1f000, 0x1f1ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x1f200, 0x1f200, OC_UNICODE_SCRIPT_HIRAGANA, OC_STR8_LIT("Hira") },
    { 0x1f201, 0x1ffff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0x20000, 0xe0000, OC_UNICODE_SCRIPT_HAN, OC_STR8_LIT("Hani") },
    { 0xe0001, 0xe00ff, OC_UNICODE_SCRIPT_COMMON, OC_STR8_LIT("Zyyy") },
    { 0xe0100, 0xe01ef, OC_UNICODE_SCRIPT_INHERITED, OC_STR8_LIT("Zinh") },
};

enum {
    OC_UNICODE_SCRIPT_RANGE_COUNT = 434,
};

#endif // __UNICODE_SCRIPTS_TABLE_H_
