/********************************************************
*
*	@file: gl_api.h
*	@note: auto-generated by glapi.py from gl.xml
*	@date: 12/072023
*
*********************************************************/
#ifndef __GL_API_H__
#define __GL_API_H__

#include"GL/glcorearb.h"
#include"GLES3/gl32.h"

typedef struct mg_gl_api
{
	PFNGLVERTEXATTRIB4NBVPROC VertexAttrib4Nbv;
	PFNGLCLEARDEPTHPROC ClearDepth;
	PFNGLSAMPLERPARAMETERIVPROC SamplerParameteriv;
	PFNGLUNIFORMSUBROUTINESUIVPROC UniformSubroutinesuiv;
	PFNGLVERTEXATTRIB3SVPROC VertexAttrib3sv;
	PFNGLINVALIDATEBUFFERSUBDATAPROC InvalidateBufferSubData;
	PFNGLACTIVESHADERPROGRAMPROC ActiveShaderProgram;
	PFNGLGENPROGRAMPIPELINESPROC GenProgramPipelines;
	PFNGLUNIFORMMATRIX4X3FVPROC UniformMatrix4x3fv;
	PFNGLVERTEXATTRIB1FVPROC VertexAttrib1fv;
	PFNGLGETSAMPLERPARAMETERIVPROC GetSamplerParameteriv;
	PFNGLLOGICOPPROC LogicOp;
	PFNGLCLEARBUFFERDATAPROC ClearBufferData;
	PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC DrawElementsInstancedBaseVertex;
	PFNGLTEXSTORAGE2DMULTISAMPLEPROC TexStorage2DMultisample;
	PFNGLPROGRAMUNIFORM2IPROC ProgramUniform2i;
	PFNGLSTENCILMASKSEPARATEPROC StencilMaskSeparate;
	PFNGLVERTEXATTRIB1DPROC VertexAttrib1d;
	PFNGLBLENDEQUATIONSEPARATEIPROC BlendEquationSeparatei;
	PFNGLVERTEXATTRIB2FVPROC VertexAttrib2fv;
	PFNGLVERTEXATTRIBI2UIVPROC VertexAttribI2uiv;
	PFNGLVERTEXATTRIB4USVPROC VertexAttrib4usv;
	PFNGLVERTEXATTRIBL2DPROC VertexAttribL2d;
	PFNGLBINDBUFFERPROC BindBuffer;
	PFNGLBLENDFUNCPROC BlendFunc;
	PFNGLDELETEQUERIESPROC DeleteQueries;
	PFNGLGETPROGRAMBINARYPROC GetProgramBinary;
	PFNGLBLENDEQUATIONSEPARATEPROC BlendEquationSeparate;
	PFNGLGETUNIFORMSUBROUTINEUIVPROC GetUniformSubroutineuiv;
	PFNGLBINDPROGRAMPIPELINEPROC BindProgramPipeline;
	PFNGLGENSAMPLERSPROC GenSamplers;
	PFNGLGETOBJECTPTRLABELPROC GetObjectPtrLabel;
	PFNGLGETRENDERBUFFERPARAMETERIVPROC GetRenderbufferParameteriv;
	PFNGLGETTEXPARAMETERIUIVPROC GetTexParameterIuiv;
	PFNGLPROGRAMUNIFORMMATRIX3FVPROC ProgramUniformMatrix3fv;
	PFNGLCOPYTEXIMAGE2DPROC CopyTexImage2D;
	PFNGLGETSHADERIVPROC GetShaderiv;
	PFNGLCLEARBUFFERUIVPROC ClearBufferuiv;
	PFNGLVERTEXATTRIBP1UIVPROC VertexAttribP1uiv;
	PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC ProgramUniformMatrix3x4fv;
	PFNGLMEMORYBARRIERPROC MemoryBarrier;
	PFNGLVERTEXATTRIBL1DVPROC VertexAttribL1dv;
	PFNGLUNIFORMBLOCKBINDINGPROC UniformBlockBinding;
	PFNGLBINDTEXTURESPROC BindTextures;
	PFNGLBLENDFUNCIPROC BlendFunci;
	PFNGLVERTEXATTRIBL3DVPROC VertexAttribL3dv;
	PFNGLTEXSTORAGE1DPROC TexStorage1D;
	PFNGLUNIFORM1DPROC Uniform1d;
	PFNGLUNIFORMMATRIX2X4DVPROC UniformMatrix2x4dv;
	PFNGLPROGRAMUNIFORM1IPROC ProgramUniform1i;
	PFNGLQUERYCOUNTERPROC QueryCounter;
	PFNGLGETDEBUGMESSAGELOGPROC GetDebugMessageLog;
	PFNGLGETMULTISAMPLEFVPROC GetMultisamplefv;
	PFNGLGETFRAGDATALOCATIONPROC GetFragDataLocation;
	PFNGLCHECKFRAMEBUFFERSTATUSPROC CheckFramebufferStatus;
	PFNGLISFRAMEBUFFERPROC IsFramebuffer;
	PFNGLTEXSTORAGE3DPROC TexStorage3D;
	PFNGLVERTEXATTRIBIFORMATPROC VertexAttribIFormat;
	PFNGLVERTEXATTRIB4NUBPROC VertexAttrib4Nub;
	PFNGLVERTEXATTRIB4NIVPROC VertexAttrib4Niv;
	PFNGLUNIFORMMATRIX3X4FVPROC UniformMatrix3x4fv;
	PFNGLGETBUFFERSUBDATAPROC GetBufferSubData;
	PFNGLUNIFORM2IVPROC Uniform2iv;
	PFNGLISENABLEDIPROC IsEnabledi;
	PFNGLGETPROGRAMRESOURCELOCATIONPROC GetProgramResourceLocation;
	PFNGLCOMPRESSEDTEXIMAGE3DPROC CompressedTexImage3D;
	PFNGLCOPYTEXSUBIMAGE2DPROC CopyTexSubImage2D;
	PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC ProgramUniformMatrix4x3dv;
	PFNGLVIEWPORTINDEXEDFVPROC ViewportIndexedfv;
	PFNGLENABLEIPROC Enablei;
	PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC ProgramUniformMatrix4x2dv;
	PFNGLPROGRAMUNIFORM4IPROC ProgramUniform4i;
	PFNGLGETSYNCIVPROC GetSynciv;
	PFNGLGENRENDERBUFFERSPROC GenRenderbuffers;
	PFNGLSAMPLERPARAMETERIUIVPROC SamplerParameterIuiv;
	PFNGLPROGRAMUNIFORM3IPROC ProgramUniform3i;
	PFNGLUNIFORM3IVPROC Uniform3iv;
	PFNGLVERTEXATTRIB1SVPROC VertexAttrib1sv;
	PFNGLPROVOKINGVERTEXPROC ProvokingVertex;
	PFNGLPOPDEBUGGROUPPROC PopDebugGroup;
	PFNGLTEXSUBIMAGE2DPROC TexSubImage2D;
	PFNGLBINDBUFFERSRANGEPROC BindBuffersRange;
	PFNGLUNIFORMMATRIX3DVPROC UniformMatrix3dv;
	PFNGLPROGRAMUNIFORM1UIPROC ProgramUniform1ui;
	PFNGLCREATESHADERPROGRAMVPROC CreateShaderProgramv;
	PFNGLDISPATCHCOMPUTEINDIRECTPROC DispatchComputeIndirect;
	PFNGLCLEARTEXIMAGEPROC ClearTexImage;
	PFNGLVERTEXATTRIBP1UIPROC VertexAttribP1ui;
	PFNGLSAMPLEMASKIPROC SampleMaski;
	PFNGLUNIFORM4IPROC Uniform4i;
	PFNGLCOPYTEXIMAGE1DPROC CopyTexImage1D;
	PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC GetSubroutineUniformLocation;
	PFNGLGETGRAPHICSRESETSTATUSPROC GetGraphicsResetStatus;
	PFNGLPOLYGONMODEPROC PolygonMode;
	PFNGLUNIFORM4FVPROC Uniform4fv;
	PFNGLPUSHDEBUGGROUPPROC PushDebugGroup;
	PFNGLMULTIDRAWARRAYSINDIRECTPROC MultiDrawArraysIndirect;
	PFNGLCREATEPROGRAMPROC CreateProgram;
	PFNGLSCISSORINDEXEDVPROC ScissorIndexedv;
	PFNGLFRAMEBUFFERTEXTURE1DPROC FramebufferTexture1D;
	PFNGLPROGRAMUNIFORMMATRIX3DVPROC ProgramUniformMatrix3dv;
	PFNGLSHADERSOURCEPROC ShaderSource;
	PFNGLUNIFORM2FPROC Uniform2f;
	PFNGLBUFFERSUBDATAPROC BufferSubData;
	PFNGLBINDSAMPLERSPROC BindSamplers;
	PFNGLCLEARTEXSUBIMAGEPROC ClearTexSubImage;
	PFNGLBLENDCOLORPROC BlendColor;
	PFNGLBINDVERTEXARRAYPROC BindVertexArray;
	PFNGLCLEARBUFFERFVPROC ClearBufferfv;
	PFNGLTEXSUBIMAGE1DPROC TexSubImage1D;
	PFNGLVERTEXATTRIBI1UIPROC VertexAttribI1ui;
	PFNGLGETBOOLEANI_VPROC GetBooleani_v;
	PFNGLGETACTIVEUNIFORMSIVPROC GetActiveUniformsiv;
	PFNGLUNIFORM2UIVPROC Uniform2uiv;
	PFNGLGETSUBROUTINEINDEXPROC GetSubroutineIndex;
	PFNGLBEGINCONDITIONALRENDERPROC BeginConditionalRender;
	PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC GetFramebufferAttachmentParameteriv;
	PFNGLVERTEXATTRIBI4UIVPROC VertexAttribI4uiv;
	PFNGLVIEWPORTARRAYVPROC ViewportArrayv;
	PFNGLUNIFORM3FPROC Uniform3f;
	PFNGLVERTEXATTRIB4DPROC VertexAttrib4d;
	PFNGLGETQUERYIVPROC GetQueryiv;
	PFNGLCOPYBUFFERSUBDATAPROC CopyBufferSubData;
	PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC DrawTransformFeedbackStream;
	PFNGLGETPOINTERVPROC GetPointerv;
	PFNGLVERTEXATTRIBPOINTERPROC VertexAttribPointer;
	PFNGLGETACTIVEUNIFORMPROC GetActiveUniform;
	PFNGLUNIFORM3UIVPROC Uniform3uiv;
	PFNGLGETBUFFERPARAMETERI64VPROC GetBufferParameteri64v;
	PFNGLTEXIMAGE1DPROC TexImage1D;
	PFNGLPROGRAMUNIFORMMATRIX2FVPROC ProgramUniformMatrix2fv;
	PFNGLDRAWTRANSFORMFEEDBACKPROC DrawTransformFeedback;
	PFNGLTEXTUREVIEWPROC TextureView;
	PFNGLVERTEXATTRIB4SVPROC VertexAttrib4sv;
	PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog;
	PFNGLVERTEXATTRIBLPOINTERPROC VertexAttribLPointer;
	PFNGLPROGRAMUNIFORM4IVPROC ProgramUniform4iv;
	PFNGLSAMPLERPARAMETERFPROC SamplerParameterf;
	PFNGLGETTEXPARAMETERFVPROC GetTexParameterfv;
	PFNGLGETUNIFORMFVPROC GetUniformfv;
	PFNGLSCISSORARRAYVPROC ScissorArrayv;
	PFNGLDEBUGMESSAGEINSERTPROC DebugMessageInsert;
	PFNGLDRAWELEMENTSINSTANCEDPROC DrawElementsInstanced;
	PFNGLGETDOUBLEVPROC GetDoublev;
	PFNGLGETINTEGER64VPROC GetInteger64v;
	PFNGLDRAWARRAYSINDIRECTPROC DrawArraysIndirect;
	PFNGLLINEWIDTHPROC LineWidth;
	PFNGLVERTEXATTRIB2SPROC VertexAttrib2s;
	PFNGLGETBOOLEANVPROC GetBooleanv;
	PFNGLTRANSFORMFEEDBACKVARYINGSPROC TransformFeedbackVaryings;
	PFNGLGETTEXLEVELPARAMETERFVPROC GetTexLevelParameterfv;
	PFNGLCOPYTEXSUBIMAGE3DPROC CopyTexSubImage3D;
	PFNGLVIEWPORTINDEXEDFPROC ViewportIndexedf;
	PFNGLSCISSORPROC Scissor;
	PFNGLTEXPARAMETERIIVPROC TexParameterIiv;
	PFNGLINVALIDATETEXIMAGEPROC InvalidateTexImage;
	PFNGLBEGINTRANSFORMFEEDBACKPROC BeginTransformFeedback;
	PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC DrawTransformFeedbackStreamInstanced;
	PFNGLGETQUERYOBJECTUIVPROC GetQueryObjectuiv;
	PFNGLUNIFORMMATRIX2DVPROC UniformMatrix2dv;
	PFNGLCOLORMASKPROC ColorMask;
	PFNGLTEXIMAGE2DMULTISAMPLEPROC TexImage2DMultisample;
	PFNGLFRAMEBUFFERTEXTURE3DPROC FramebufferTexture3D;
	PFNGLGETVERTEXATTRIBIIVPROC GetVertexAttribIiv;
	PFNGLVERTEXATTRIBL3DPROC VertexAttribL3d;
	PFNGLVERTEXATTRIB1FPROC VertexAttrib1f;
	PFNGLGETTRANSFORMFEEDBACKVARYINGPROC GetTransformFeedbackVarying;
	PFNGLISSHADERPROC IsShader;
	PFNGLCLEARBUFFERFIPROC ClearBufferfi;
	PFNGLVALIDATEPROGRAMPROC ValidateProgram;
	PFNGLPROGRAMUNIFORM2FPROC ProgramUniform2f;
	PFNGLGETNUNIFORMFVPROC GetnUniformfv;
	PFNGLTEXIMAGE3DMULTISAMPLEPROC TexImage3DMultisample;
	PFNGLFRONTFACEPROC FrontFace;
	PFNGLVERTEXATTRIBI2IVPROC VertexAttribI2iv;
	PFNGLRENDERBUFFERSTORAGEPROC RenderbufferStorage;
	PFNGLPROGRAMUNIFORM4DVPROC ProgramUniform4dv;
	PFNGLGETSHADERSOURCEPROC GetShaderSource;
	PFNGLGETVERTEXATTRIBDVPROC GetVertexAttribdv;
	PFNGLPRIMITIVERESTARTINDEXPROC PrimitiveRestartIndex;
	PFNGLUNMAPBUFFERPROC UnmapBuffer;
	PFNGLVERTEXATTRIBP2UIVPROC VertexAttribP2uiv;
	PFNGLGETBUFFERPARAMETERIVPROC GetBufferParameteriv;
	PFNGLUNIFORMMATRIX2X3FVPROC UniformMatrix2x3fv;
	PFNGLDEBUGMESSAGECONTROLPROC DebugMessageControl;
	PFNGLPIXELSTOREFPROC PixelStoref;
	PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC ProgramUniformMatrix3x2fv;
	PFNGLGETNUNIFORMIVPROC GetnUniformiv;
	PFNGLGETINTEGERI_VPROC GetIntegeri_v;
	PFNGLVERTEXATTRIBL4DPROC VertexAttribL4d;
	PFNGLREADNPIXELSPROC ReadnPixels;
	PFNGLUSEPROGRAMPROC UseProgram;
	PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC GetActiveSubroutineUniformiv;
	PFNGLDISABLEPROC Disable;
	PFNGLCULLFACEPROC CullFace;
	PFNGLGETVERTEXATTRIBIVPROC GetVertexAttribiv;
	PFNGLVERTEXATTRIBI4IVPROC VertexAttribI4iv;
	PFNGLVIEWPORTPROC Viewport;
	PFNGLATTACHSHADERPROC AttachShader;
	PFNGLPROGRAMBINARYPROC ProgramBinary;
	PFNGLDEPTHRANGEPROC DepthRange;
	PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC ProgramUniformMatrix3x2dv;
	PFNGLPROGRAMUNIFORM3DVPROC ProgramUniform3dv;
	PFNGLFRAMEBUFFERPARAMETERIPROC FramebufferParameteri;
	PFNGLDRAWBUFFERSPROC DrawBuffers;
	PFNGLVERTEXATTRIBI3IPROC VertexAttribI3i;
	PFNGLVERTEXATTRIBL1DPROC VertexAttribL1d;
	PFNGLBLENDBARRIERPROC BlendBarrier;
	PFNGLGETVERTEXATTRIBPOINTERVPROC GetVertexAttribPointerv;
	PFNGLUNIFORM4UIVPROC Uniform4uiv;
	PFNGLBEGINQUERYPROC BeginQuery;
	PFNGLENDCONDITIONALRENDERPROC EndConditionalRender;
	PFNGLSHADERSTORAGEBLOCKBINDINGPROC ShaderStorageBlockBinding;
	PFNGLGETVERTEXATTRIBIUIVPROC GetVertexAttribIuiv;
	PFNGLBINDBUFFERRANGEPROC BindBufferRange;
	PFNGLCOPYTEXSUBIMAGE1DPROC CopyTexSubImage1D;
	PFNGLVERTEXATTRIB3SPROC VertexAttrib3s;
	PFNGLMAPBUFFERRANGEPROC MapBufferRange;
	PFNGLPROGRAMUNIFORM4UIPROC ProgramUniform4ui;
	PFNGLINVALIDATESUBFRAMEBUFFERPROC InvalidateSubFramebuffer;
	PFNGLSCISSORINDEXEDPROC ScissorIndexed;
	PFNGLDELETESYNCPROC DeleteSync;
	PFNGLVERTEXATTRIBP4UIVPROC VertexAttribP4uiv;
	PFNGLENABLEVERTEXATTRIBARRAYPROC EnableVertexAttribArray;
	PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC CompressedTexSubImage2D;
	PFNGLGETUNIFORMDVPROC GetUniformdv;
	PFNGLHINTPROC Hint;
	PFNGLFINISHPROC Finish;
	PFNGLSAMPLERPARAMETERIPROC SamplerParameteri;
	PFNGLISVERTEXARRAYPROC IsVertexArray;
	PFNGLBLENDEQUATIONPROC BlendEquation;
	PFNGLUNIFORM2DPROC Uniform2d;
	PFNGLISSYNCPROC IsSync;
	PFNGLVERTEXATTRIBL4DVPROC VertexAttribL4dv;
	PFNGLUNIFORMMATRIX4X2FVPROC UniformMatrix4x2fv;
	PFNGLVERTEXATTRIBI2IPROC VertexAttribI2i;
	PFNGLGETATTRIBLOCATIONPROC GetAttribLocation;
	PFNGLVERTEXATTRIB3DPROC VertexAttrib3d;
	PFNGLVERTEXATTRIBP3UIVPROC VertexAttribP3uiv;
	PFNGLGETFLOATVPROC GetFloatv;
	PFNGLFRAMEBUFFERRENDERBUFFERPROC FramebufferRenderbuffer;
	PFNGLGENFRAMEBUFFERSPROC GenFramebuffers;
	PFNGLVERTEXATTRIB4SPROC VertexAttrib4s;
	PFNGLVERTEXATTRIBL2DVPROC VertexAttribL2dv;
	PFNGLUNIFORMMATRIX4X3DVPROC UniformMatrix4x3dv;
	PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC GetActiveUniformBlockName;
	PFNGLCOMPILESHADERPROC CompileShader;
	PFNGLDEPTHMASKPROC DepthMask;
	PFNGLVERTEXATTRIBIPOINTERPROC VertexAttribIPointer;
	PFNGLDEPTHRANGEINDEXEDPROC DepthRangeIndexed;
	PFNGLPROGRAMUNIFORMMATRIX4DVPROC ProgramUniformMatrix4dv;
	PFNGLUNIFORM3UIPROC Uniform3ui;
	PFNGLGETSAMPLERPARAMETERFVPROC GetSamplerParameterfv;
	PFNGLREADBUFFERPROC ReadBuffer;
	PFNGLVERTEXATTRIB2FPROC VertexAttrib2f;
	PFNGLVERTEXATTRIB2SVPROC VertexAttrib2sv;
	PFNGLVERTEXATTRIB4BVPROC VertexAttrib4bv;
	PFNGLUNIFORM3FVPROC Uniform3fv;
	PFNGLGETBUFFERPOINTERVPROC GetBufferPointerv;
	PFNGLGETPROGRAMPIPELINEINFOLOGPROC GetProgramPipelineInfoLog;
	PFNGLUNIFORM2FVPROC Uniform2fv;
	PFNGLGETERRORPROC GetError;
	PFNGLPROGRAMUNIFORMMATRIX2DVPROC ProgramUniformMatrix2dv;
	PFNGLISENABLEDPROC IsEnabled;
	PFNGLUNIFORM4FPROC Uniform4f;
	PFNGLDRAWARRAYSINSTANCEDPROC DrawArraysInstanced;
	PFNGLCOMPRESSEDTEXIMAGE1DPROC CompressedTexImage1D;
	PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC ProgramUniformMatrix2x4dv;
	PFNGLVERTEXATTRIB3FPROC VertexAttrib3f;
	PFNGLVERTEXATTRIBI1IPROC VertexAttribI1i;
	PFNGLPOINTPARAMETERFVPROC PointParameterfv;
	PFNGLBINDTEXTUREPROC BindTexture;
	PFNGLPROGRAMUNIFORM2FVPROC ProgramUniform2fv;
	PFNGLBINDVERTEXBUFFERSPROC BindVertexBuffers;
	PFNGLISTRANSFORMFEEDBACKPROC IsTransformFeedback;
	PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC ProgramUniformMatrix2x3dv;
	PFNGLBEGINQUERYINDEXEDPROC BeginQueryIndexed;
	PFNGLSAMPLECOVERAGEPROC SampleCoverage;
	PFNGLDEPTHFUNCPROC DepthFunc;
	PFNGLGENBUFFERSPROC GenBuffers;
	PFNGLOBJECTLABELPROC ObjectLabel;
	PFNGLUNIFORM1FVPROC Uniform1fv;
	PFNGLUNIFORM4UIPROC Uniform4ui;
	PFNGLBINDSAMPLERPROC BindSampler;
	PFNGLDRAWARRAYSPROC DrawArrays;
	PFNGLDELETESHADERPROC DeleteShader;
	PFNGLMULTIDRAWARRAYSPROC MultiDrawArrays;
	PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC ProgramUniformMatrix2x3fv;
	PFNGLPROGRAMUNIFORM2UIPROC ProgramUniform2ui;
	PFNGLBUFFERSTORAGEPROC BufferStorage;
	PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC ProgramUniformMatrix4x2fv;
	PFNGLDRAWELEMENTSBASEVERTEXPROC DrawElementsBaseVertex;
	PFNGLPROGRAMUNIFORM3FVPROC ProgramUniform3fv;
	PFNGLCOLORMASKIPROC ColorMaski;
	PFNGLGETQUERYOBJECTUI64VPROC GetQueryObjectui64v;
	PFNGLGENVERTEXARRAYSPROC GenVertexArrays;
	PFNGLUNIFORMMATRIX3X4DVPROC UniformMatrix3x4dv;
	PFNGLDELETEFRAMEBUFFERSPROC DeleteFramebuffers;
	PFNGLPROGRAMUNIFORM3UIVPROC ProgramUniform3uiv;
	PFNGLUNIFORM2DVPROC Uniform2dv;
	PFNGLGETDOUBLEI_VPROC GetDoublei_v;
	PFNGLUNIFORM3IPROC Uniform3i;
	PFNGLVERTEXATTRIBP2UIPROC VertexAttribP2ui;
	PFNGLGETINTEGERVPROC GetIntegerv;
	PFNGLCLAMPCOLORPROC ClampColor;
	PFNGLTEXSTORAGE3DMULTISAMPLEPROC TexStorage3DMultisample;
	PFNGLCLEARBUFFERSUBDATAPROC ClearBufferSubData;
	PFNGLCOPYIMAGESUBDATAPROC CopyImageSubData;
	PFNGLPAUSETRANSFORMFEEDBACKPROC PauseTransformFeedback;
	PFNGLUNIFORM3DVPROC Uniform3dv;
	PFNGLPROGRAMUNIFORM1DPROC ProgramUniform1d;
	PFNGLGETTEXPARAMETERIIVPROC GetTexParameterIiv;
	PFNGLTEXPARAMETERFVPROC TexParameterfv;
	PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC ProgramUniformMatrix3x4dv;
	PFNGLGETFRAMEBUFFERPARAMETERIVPROC GetFramebufferParameteriv;
	PFNGLGENQUERIESPROC GenQueries;
	PFNGLDELETEBUFFERSPROC DeleteBuffers;
	PFNGLUNIFORM1IPROC Uniform1i;
	PFNGLPROGRAMUNIFORM4FVPROC ProgramUniform4fv;
	PFNGLPROGRAMUNIFORM4FPROC ProgramUniform4f;
	PFNGLSHADERBINARYPROC ShaderBinary;
	PFNGLTEXPARAMETERFPROC TexParameterf;
	PFNGLUNIFORMMATRIX3X2FVPROC UniformMatrix3x2fv;
	PFNGLGETTEXIMAGEPROC GetTexImage;
	PFNGLPROGRAMUNIFORMMATRIX4FVPROC ProgramUniformMatrix4fv;
	PFNGLVERTEXATTRIB4FPROC VertexAttrib4f;
	PFNGLBLENDFUNCSEPARATEPROC BlendFuncSeparate;
	PFNGLGETVERTEXATTRIBFVPROC GetVertexAttribfv;
	PFNGLVERTEXATTRIB4DVPROC VertexAttrib4dv;
	PFNGLCLEARDEPTHFPROC ClearDepthf;
	PFNGLINVALIDATEFRAMEBUFFERPROC InvalidateFramebuffer;
	PFNGLPIXELSTOREIPROC PixelStorei;
	PFNGLACTIVETEXTUREPROC ActiveTexture;
	PFNGLISPROGRAMPIPELINEPROC IsProgramPipeline;
	PFNGLUNIFORM4IVPROC Uniform4iv;
	PFNGLBINDATTRIBLOCATIONPROC BindAttribLocation;
	PFNGLGETVERTEXATTRIBLDVPROC GetVertexAttribLdv;
	PFNGLGETPROGRAMRESOURCENAMEPROC GetProgramResourceName;
	PFNGLGETINTEGER64I_VPROC GetInteger64i_v;
	PFNGLPATCHPARAMETERFVPROC PatchParameterfv;
	PFNGLUNIFORM1DVPROC Uniform1dv;
	PFNGLVERTEXATTRIBI1IVPROC VertexAttribI1iv;
	PFNGLVERTEXATTRIBI3UIVPROC VertexAttribI3uiv;
	PFNGLVERTEXATTRIBI4UBVPROC VertexAttribI4ubv;
	PFNGLUSEPROGRAMSTAGESPROC UseProgramStages;
	PFNGLISRENDERBUFFERPROC IsRenderbuffer;
	PFNGLBINDFRAGDATALOCATIONPROC BindFragDataLocation;
	PFNGLUNIFORM1UIPROC Uniform1ui;
	PFNGLSTENCILMASKPROC StencilMask;
	PFNGLGETSHADERPRECISIONFORMATPROC GetShaderPrecisionFormat;
	PFNGLBINDIMAGETEXTUREPROC BindImageTexture;
	PFNGLVERTEXATTRIB2DVPROC VertexAttrib2dv;
	PFNGLPROGRAMUNIFORM1IVPROC ProgramUniform1iv;
	PFNGLGETACTIVESUBROUTINENAMEPROC GetActiveSubroutineName;
	PFNGLGETFLOATI_VPROC GetFloati_v;
	PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC RenderbufferStorageMultisample;
	PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog;
	PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC DrawElementsInstancedBaseInstance;
	PFNGLVERTEXATTRIBP4UIPROC VertexAttribP4ui;
	PFNGLVERTEXATTRIB4NUSVPROC VertexAttrib4Nusv;
	PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC GetActiveSubroutineUniformName;
	PFNGLUNIFORM1UIVPROC Uniform1uiv;
	PFNGLUNIFORMMATRIX4X2DVPROC UniformMatrix4x2dv;
	PFNGLVERTEXATTRIB4NSVPROC VertexAttrib4Nsv;
	PFNGLVERTEXATTRIB1DVPROC VertexAttrib1dv;
	PFNGLDELETETEXTURESPROC DeleteTextures;
	PFNGLGENERATEMIPMAPPROC GenerateMipmap;
	PFNGLGENTRANSFORMFEEDBACKSPROC GenTransformFeedbacks;
	PFNGLWAITSYNCPROC WaitSync;
	PFNGLUNIFORM2UIPROC Uniform2ui;
	PFNGLBLENDEQUATIONIPROC BlendEquationi;
	PFNGLBUFFERDATAPROC BufferData;
	PFNGLGETUNIFORMINDICESPROC GetUniformIndices;
	PFNGLVERTEXATTRIB4FVPROC VertexAttrib4fv;
	PFNGLRESUMETRANSFORMFEEDBACKPROC ResumeTransformFeedback;
	PFNGLBINDTRANSFORMFEEDBACKPROC BindTransformFeedback;
	PFNGLVERTEXATTRIB4IVPROC VertexAttrib4iv;
	PFNGLLINKPROGRAMPROC LinkProgram;
	PFNGLTEXIMAGE3DPROC TexImage3D;
	PFNGLCLEARPROC Clear;
	PFNGLVERTEXATTRIB3FVPROC VertexAttrib3fv;
	PFNGLFENCESYNCPROC FenceSync;
	PFNGLGETACTIVEATTRIBPROC GetActiveAttrib;
	PFNGLREADPIXELSPROC ReadPixels;
	PFNGLPROGRAMUNIFORM2DPROC ProgramUniform2d;
	PFNGLGETSAMPLERPARAMETERIIVPROC GetSamplerParameterIiv;
	PFNGLGETPROGRAMSTAGEIVPROC GetProgramStageiv;
	PFNGLRELEASESHADERCOMPILERPROC ReleaseShaderCompiler;
	PFNGLVERTEXATTRIBI4USVPROC VertexAttribI4usv;
	PFNGLGETUNIFORMUIVPROC GetUniformuiv;
	PFNGLPROGRAMUNIFORM1DVPROC ProgramUniform1dv;
	PFNGLFRAMEBUFFERTEXTURELAYERPROC FramebufferTextureLayer;
	PFNGLPROGRAMUNIFORM3FPROC ProgramUniform3f;
	PFNGLPROGRAMUNIFORM3UIPROC ProgramUniform3ui;
	PFNGLDELETEPROGRAMPROC DeleteProgram;
	PFNGLPOLYGONOFFSETPROC PolygonOffset;
	PFNGLSAMPLERPARAMETERIIVPROC SamplerParameterIiv;
	PFNGLUNIFORMMATRIX3X2DVPROC UniformMatrix3x2dv;
	PFNGLUNIFORM4DVPROC Uniform4dv;
	PFNGLDELETEVERTEXARRAYSPROC DeleteVertexArrays;
	PFNGLGETPROGRAMRESOURCEIVPROC GetProgramResourceiv;
	PFNGLUNIFORMMATRIX2X4FVPROC UniformMatrix2x4fv;
	PFNGLGETINTERNALFORMATI64VPROC GetInternalformati64v;
	PFNGLPOINTPARAMETERIVPROC PointParameteriv;
	PFNGLVERTEXATTRIBI4SVPROC VertexAttribI4sv;
	PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC DrawTransformFeedbackInstanced;
	PFNGLGETATTACHEDSHADERSPROC GetAttachedShaders;
	PFNGLVERTEXATTRIBI3IVPROC VertexAttribI3iv;
	PFNGLTEXPARAMETERIUIVPROC TexParameterIuiv;
	PFNGLVERTEXATTRIBBINDINGPROC VertexAttribBinding;
	PFNGLMULTIDRAWELEMENTSPROC MultiDrawElements;
	PFNGLTEXBUFFERPROC TexBuffer;
	PFNGLGETSTRINGPROC GetString;
	PFNGLGETNUNIFORMUIVPROC GetnUniformuiv;
	PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC DrawElementsInstancedBaseVertexBaseInstance;
	PFNGLGETUNIFORMIVPROC GetUniformiv;
	PFNGLDELETEPROGRAMPIPELINESPROC DeleteProgramPipelines;
	PFNGLVERTEXATTRIBI2UIPROC VertexAttribI2ui;
	PFNGLPROGRAMUNIFORM2DVPROC ProgramUniform2dv;
	PFNGLTEXBUFFERRANGEPROC TexBufferRange;
	PFNGLTEXPARAMETERIPROC TexParameteri;
	PFNGLBINDBUFFERSBASEPROC BindBuffersBase;
	PFNGLVERTEXATTRIB2DPROC VertexAttrib2d;
	PFNGLCREATESHADERPROC CreateShader;
	PFNGLBINDVERTEXBUFFERPROC BindVertexBuffer;
	PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D;
	PFNGLDEPTHRANGEARRAYVPROC DepthRangeArrayv;
	PFNGLVERTEXATTRIB4NUIVPROC VertexAttrib4Nuiv;
	PFNGLUNIFORMMATRIX4FVPROC UniformMatrix4fv;
	PFNGLCLEARSTENCILPROC ClearStencil;
	PFNGLBINDBUFFERBASEPROC BindBufferBase;
	PFNGLINVALIDATETEXSUBIMAGEPROC InvalidateTexSubImage;
	PFNGLOBJECTPTRLABELPROC ObjectPtrLabel;
	PFNGLMINSAMPLESHADINGPROC MinSampleShading;
	PFNGLENABLEPROC Enable;
	PFNGLINVALIDATEBUFFERDATAPROC InvalidateBufferData;
	PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC ProgramUniformMatrix2x4fv;
	PFNGLVERTEXATTRIBLFORMATPROC VertexAttribLFormat;
	PFNGLMULTIDRAWELEMENTSINDIRECTPROC MultiDrawElementsIndirect;
	PFNGLGETOBJECTLABELPROC GetObjectLabel;
	PFNGLVERTEXATTRIBI3UIPROC VertexAttribI3ui;
	PFNGLFLUSHMAPPEDBUFFERRANGEPROC FlushMappedBufferRange;
	PFNGLGETUNIFORMBLOCKINDEXPROC GetUniformBlockIndex;
	PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation;
	PFNGLGETQUERYOBJECTI64VPROC GetQueryObjecti64v;
	PFNGLPROGRAMUNIFORM1UIVPROC ProgramUniform1uiv;
	PFNGLISSAMPLERPROC IsSampler;
	PFNGLPROGRAMUNIFORM4UIVPROC ProgramUniform4uiv;
	PFNGLVERTEXATTRIB4NUBVPROC VertexAttrib4Nubv;
	PFNGLVERTEXATTRIBI4UIPROC VertexAttribI4ui;
	PFNGLTEXSUBIMAGE3DPROC TexSubImage3D;
	PFNGLFRAMEBUFFERTEXTUREPROC FramebufferTexture;
	PFNGLPOINTPARAMETERFPROC PointParameterf;
	PFNGLGETINTERNALFORMATIVPROC GetInternalformativ;
	PFNGLGETACTIVEUNIFORMBLOCKIVPROC GetActiveUniformBlockiv;
	PFNGLDETACHSHADERPROC DetachShader;
	PFNGLUNIFORM2IPROC Uniform2i;
	PFNGLPROGRAMPARAMETERIPROC ProgramParameteri;
	PFNGLGETQUERYOBJECTIVPROC GetQueryObjectiv;
	PFNGLSAMPLERPARAMETERFVPROC SamplerParameterfv;
	PFNGLVERTEXATTRIB4UBVPROC VertexAttrib4ubv;
	PFNGLCLEARCOLORPROC ClearColor;
	PFNGLTEXPARAMETERIVPROC TexParameteriv;
	PFNGLUNIFORM3DPROC Uniform3d;
	PFNGLENDTRANSFORMFEEDBACKPROC EndTransformFeedback;
	PFNGLDRAWELEMENTSPROC DrawElements;
	PFNGLVERTEXATTRIB4UIVPROC VertexAttrib4uiv;
	PFNGLMAPBUFFERPROC MapBuffer;
	PFNGLGETPROGRAMIVPROC GetProgramiv;
	PFNGLPROGRAMUNIFORM2UIVPROC ProgramUniform2uiv;
	PFNGLUNIFORMMATRIX4DVPROC UniformMatrix4dv;
	PFNGLPROGRAMUNIFORM1FVPROC ProgramUniform1fv;
	PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC DrawArraysInstancedBaseInstance;
	PFNGLGETQUERYINDEXEDIVPROC GetQueryIndexediv;
	PFNGLSTENCILFUNCPROC StencilFunc;
	PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC GetActiveAtomicCounterBufferiv;
	PFNGLSTENCILFUNCSEPARATEPROC StencilFuncSeparate;
	PFNGLSTENCILOPPROC StencilOp;
	PFNGLVERTEXATTRIBDIVISORPROC VertexAttribDivisor;
	PFNGLDEBUGMESSAGECALLBACKPROC DebugMessageCallback;
	PFNGLVERTEXATTRIBP3UIPROC VertexAttribP3ui;
	PFNGLBINDFRAMEBUFFERPROC BindFramebuffer;
	PFNGLISPROGRAMPROC IsProgram;
	PFNGLPROGRAMUNIFORM2IVPROC ProgramUniform2iv;
	PFNGLDELETESAMPLERSPROC DeleteSamplers;
	PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC CompressedTexSubImage1D;
	PFNGLFLUSHPROC Flush;
	PFNGLDEPTHRANGEFPROC DepthRangef;
	PFNGLMEMORYBARRIERBYREGIONPROC MemoryBarrierByRegion;
	PFNGLGETACTIVEUNIFORMNAMEPROC GetActiveUniformName;
	PFNGLGETPROGRAMINTERFACEIVPROC GetProgramInterfaceiv;
	PFNGLDISABLEIPROC Disablei;
	PFNGLISTEXTUREPROC IsTexture;
	PFNGLUNIFORMMATRIX2X3DVPROC UniformMatrix2x3dv;
	PFNGLBLENDFUNCSEPARATEIPROC BlendFuncSeparatei;
	PFNGLDISABLEVERTEXATTRIBARRAYPROC DisableVertexAttribArray;
	PFNGLCOMPRESSEDTEXIMAGE2DPROC CompressedTexImage2D;
	PFNGLISQUERYPROC IsQuery;
	PFNGLTEXIMAGE2DPROC TexImage2D;
	PFNGLUNIFORM1FPROC Uniform1f;
	PFNGLBINDRENDERBUFFERPROC BindRenderbuffer;
	PFNGLBINDFRAGDATALOCATIONINDEXEDPROC BindFragDataLocationIndexed;
	PFNGLVERTEXATTRIBI4BVPROC VertexAttribI4bv;
	PFNGLVERTEXATTRIB1SPROC VertexAttrib1s;
	PFNGLGETCOMPRESSEDTEXIMAGEPROC GetCompressedTexImage;
	PFNGLUNIFORMMATRIX3FVPROC UniformMatrix3fv;
	PFNGLSTENCILOPSEPARATEPROC StencilOpSeparate;
	PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC ProgramUniformMatrix4x3fv;
	PFNGLGETSTRINGIPROC GetStringi;
	PFNGLDISPATCHCOMPUTEPROC DispatchCompute;
	PFNGLPOINTPARAMETERIPROC PointParameteri;
	PFNGLBINDIMAGETEXTURESPROC BindImageTextures;
	PFNGLDELETETRANSFORMFEEDBACKSPROC DeleteTransformFeedbacks;
	PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC DrawRangeElementsBaseVertex;
	PFNGLPROGRAMUNIFORM4DPROC ProgramUniform4d;
	PFNGLVERTEXATTRIBI4IPROC VertexAttribI4i;
	PFNGLDRAWBUFFERPROC DrawBuffer;
	PFNGLTEXSTORAGE2DPROC TexStorage2D;
	PFNGLVERTEXATTRIBFORMATPROC VertexAttribFormat;
	PFNGLENDQUERYPROC EndQuery;
	PFNGLPATCHPARAMETERIPROC PatchParameteri;
	PFNGLCLEARBUFFERIVPROC ClearBufferiv;
	PFNGLENDQUERYINDEXEDPROC EndQueryIndexed;
	PFNGLPOINTSIZEPROC PointSize;
	PFNGLVERTEXATTRIB3DVPROC VertexAttrib3dv;
	PFNGLUNIFORM4DPROC Uniform4d;
	PFNGLGENTEXTURESPROC GenTextures;
	PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC GetProgramResourceLocationIndex;
	PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC MultiDrawElementsBaseVertex;
	PFNGLPROGRAMUNIFORM3DPROC ProgramUniform3d;
	PFNGLGETFRAGDATAINDEXPROC GetFragDataIndex;
	PFNGLCLIENTWAITSYNCPROC ClientWaitSync;
	PFNGLDELETERENDERBUFFERSPROC DeleteRenderbuffers;
	PFNGLPROGRAMUNIFORM3IVPROC ProgramUniform3iv;
	PFNGLDRAWELEMENTSINDIRECTPROC DrawElementsIndirect;
	PFNGLPRIMITIVEBOUNDINGBOXPROC PrimitiveBoundingBox;
	PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC CompressedTexSubImage3D;
	PFNGLDRAWRANGEELEMENTSPROC DrawRangeElements;
	PFNGLUNIFORM1IVPROC Uniform1iv;
	PFNGLGETSAMPLERPARAMETERIUIVPROC GetSamplerParameterIuiv;
	PFNGLVALIDATEPROGRAMPIPELINEPROC ValidateProgramPipeline;
	PFNGLGETPROGRAMRESOURCEINDEXPROC GetProgramResourceIndex;
	PFNGLVERTEXATTRIBI1UIVPROC VertexAttribI1uiv;
	PFNGLGETTEXLEVELPARAMETERIVPROC GetTexLevelParameteriv;
	PFNGLBLITFRAMEBUFFERPROC BlitFramebuffer;
	PFNGLVERTEXBINDINGDIVISORPROC VertexBindingDivisor;
	PFNGLGETPROGRAMPIPELINEIVPROC GetProgramPipelineiv;
	PFNGLPROGRAMUNIFORM1FPROC ProgramUniform1f;
	PFNGLISBUFFERPROC IsBuffer;
	PFNGLGETTEXPARAMETERIVPROC GetTexParameteriv;
	PFNGLUNIFORMMATRIX2FVPROC UniformMatrix2fv;
} mg_gl_api;

MP_API mg_gl_api* mg_gl_get_api(void);

#define glVertexAttrib4Nbv mg_gl_get_api()->VertexAttrib4Nbv
#define glClearDepth mg_gl_get_api()->ClearDepth
#define glSamplerParameteriv mg_gl_get_api()->SamplerParameteriv
#define glUniformSubroutinesuiv mg_gl_get_api()->UniformSubroutinesuiv
#define glVertexAttrib3sv mg_gl_get_api()->VertexAttrib3sv
#define glInvalidateBufferSubData mg_gl_get_api()->InvalidateBufferSubData
#define glActiveShaderProgram mg_gl_get_api()->ActiveShaderProgram
#define glGenProgramPipelines mg_gl_get_api()->GenProgramPipelines
#define glUniformMatrix4x3fv mg_gl_get_api()->UniformMatrix4x3fv
#define glVertexAttrib1fv mg_gl_get_api()->VertexAttrib1fv
#define glGetSamplerParameteriv mg_gl_get_api()->GetSamplerParameteriv
#define glLogicOp mg_gl_get_api()->LogicOp
#define glClearBufferData mg_gl_get_api()->ClearBufferData
#define glDrawElementsInstancedBaseVertex mg_gl_get_api()->DrawElementsInstancedBaseVertex
#define glTexStorage2DMultisample mg_gl_get_api()->TexStorage2DMultisample
#define glProgramUniform2i mg_gl_get_api()->ProgramUniform2i
#define glStencilMaskSeparate mg_gl_get_api()->StencilMaskSeparate
#define glVertexAttrib1d mg_gl_get_api()->VertexAttrib1d
#define glBlendEquationSeparatei mg_gl_get_api()->BlendEquationSeparatei
#define glVertexAttrib2fv mg_gl_get_api()->VertexAttrib2fv
#define glVertexAttribI2uiv mg_gl_get_api()->VertexAttribI2uiv
#define glVertexAttrib4usv mg_gl_get_api()->VertexAttrib4usv
#define glVertexAttribL2d mg_gl_get_api()->VertexAttribL2d
#define glBindBuffer mg_gl_get_api()->BindBuffer
#define glBlendFunc mg_gl_get_api()->BlendFunc
#define glDeleteQueries mg_gl_get_api()->DeleteQueries
#define glGetProgramBinary mg_gl_get_api()->GetProgramBinary
#define glBlendEquationSeparate mg_gl_get_api()->BlendEquationSeparate
#define glGetUniformSubroutineuiv mg_gl_get_api()->GetUniformSubroutineuiv
#define glBindProgramPipeline mg_gl_get_api()->BindProgramPipeline
#define glGenSamplers mg_gl_get_api()->GenSamplers
#define glGetObjectPtrLabel mg_gl_get_api()->GetObjectPtrLabel
#define glGetRenderbufferParameteriv mg_gl_get_api()->GetRenderbufferParameteriv
#define glGetTexParameterIuiv mg_gl_get_api()->GetTexParameterIuiv
#define glProgramUniformMatrix3fv mg_gl_get_api()->ProgramUniformMatrix3fv
#define glCopyTexImage2D mg_gl_get_api()->CopyTexImage2D
#define glGetShaderiv mg_gl_get_api()->GetShaderiv
#define glClearBufferuiv mg_gl_get_api()->ClearBufferuiv
#define glVertexAttribP1uiv mg_gl_get_api()->VertexAttribP1uiv
#define glProgramUniformMatrix3x4fv mg_gl_get_api()->ProgramUniformMatrix3x4fv
#define glMemoryBarrier mg_gl_get_api()->MemoryBarrier
#define glVertexAttribL1dv mg_gl_get_api()->VertexAttribL1dv
#define glUniformBlockBinding mg_gl_get_api()->UniformBlockBinding
#define glBindTextures mg_gl_get_api()->BindTextures
#define glBlendFunci mg_gl_get_api()->BlendFunci
#define glVertexAttribL3dv mg_gl_get_api()->VertexAttribL3dv
#define glTexStorage1D mg_gl_get_api()->TexStorage1D
#define glUniform1d mg_gl_get_api()->Uniform1d
#define glUniformMatrix2x4dv mg_gl_get_api()->UniformMatrix2x4dv
#define glProgramUniform1i mg_gl_get_api()->ProgramUniform1i
#define glQueryCounter mg_gl_get_api()->QueryCounter
#define glGetDebugMessageLog mg_gl_get_api()->GetDebugMessageLog
#define glGetMultisamplefv mg_gl_get_api()->GetMultisamplefv
#define glGetFragDataLocation mg_gl_get_api()->GetFragDataLocation
#define glCheckFramebufferStatus mg_gl_get_api()->CheckFramebufferStatus
#define glIsFramebuffer mg_gl_get_api()->IsFramebuffer
#define glTexStorage3D mg_gl_get_api()->TexStorage3D
#define glVertexAttribIFormat mg_gl_get_api()->VertexAttribIFormat
#define glVertexAttrib4Nub mg_gl_get_api()->VertexAttrib4Nub
#define glVertexAttrib4Niv mg_gl_get_api()->VertexAttrib4Niv
#define glUniformMatrix3x4fv mg_gl_get_api()->UniformMatrix3x4fv
#define glGetBufferSubData mg_gl_get_api()->GetBufferSubData
#define glUniform2iv mg_gl_get_api()->Uniform2iv
#define glIsEnabledi mg_gl_get_api()->IsEnabledi
#define glGetProgramResourceLocation mg_gl_get_api()->GetProgramResourceLocation
#define glCompressedTexImage3D mg_gl_get_api()->CompressedTexImage3D
#define glCopyTexSubImage2D mg_gl_get_api()->CopyTexSubImage2D
#define glProgramUniformMatrix4x3dv mg_gl_get_api()->ProgramUniformMatrix4x3dv
#define glViewportIndexedfv mg_gl_get_api()->ViewportIndexedfv
#define glEnablei mg_gl_get_api()->Enablei
#define glProgramUniformMatrix4x2dv mg_gl_get_api()->ProgramUniformMatrix4x2dv
#define glProgramUniform4i mg_gl_get_api()->ProgramUniform4i
#define glGetSynciv mg_gl_get_api()->GetSynciv
#define glGenRenderbuffers mg_gl_get_api()->GenRenderbuffers
#define glSamplerParameterIuiv mg_gl_get_api()->SamplerParameterIuiv
#define glProgramUniform3i mg_gl_get_api()->ProgramUniform3i
#define glUniform3iv mg_gl_get_api()->Uniform3iv
#define glVertexAttrib1sv mg_gl_get_api()->VertexAttrib1sv
#define glProvokingVertex mg_gl_get_api()->ProvokingVertex
#define glPopDebugGroup mg_gl_get_api()->PopDebugGroup
#define glTexSubImage2D mg_gl_get_api()->TexSubImage2D
#define glBindBuffersRange mg_gl_get_api()->BindBuffersRange
#define glUniformMatrix3dv mg_gl_get_api()->UniformMatrix3dv
#define glProgramUniform1ui mg_gl_get_api()->ProgramUniform1ui
#define glCreateShaderProgramv mg_gl_get_api()->CreateShaderProgramv
#define glDispatchComputeIndirect mg_gl_get_api()->DispatchComputeIndirect
#define glClearTexImage mg_gl_get_api()->ClearTexImage
#define glVertexAttribP1ui mg_gl_get_api()->VertexAttribP1ui
#define glSampleMaski mg_gl_get_api()->SampleMaski
#define glUniform4i mg_gl_get_api()->Uniform4i
#define glCopyTexImage1D mg_gl_get_api()->CopyTexImage1D
#define glGetSubroutineUniformLocation mg_gl_get_api()->GetSubroutineUniformLocation
#define glGetGraphicsResetStatus mg_gl_get_api()->GetGraphicsResetStatus
#define glPolygonMode mg_gl_get_api()->PolygonMode
#define glUniform4fv mg_gl_get_api()->Uniform4fv
#define glPushDebugGroup mg_gl_get_api()->PushDebugGroup
#define glMultiDrawArraysIndirect mg_gl_get_api()->MultiDrawArraysIndirect
#define glCreateProgram mg_gl_get_api()->CreateProgram
#define glScissorIndexedv mg_gl_get_api()->ScissorIndexedv
#define glFramebufferTexture1D mg_gl_get_api()->FramebufferTexture1D
#define glProgramUniformMatrix3dv mg_gl_get_api()->ProgramUniformMatrix3dv
#define glShaderSource mg_gl_get_api()->ShaderSource
#define glUniform2f mg_gl_get_api()->Uniform2f
#define glBufferSubData mg_gl_get_api()->BufferSubData
#define glBindSamplers mg_gl_get_api()->BindSamplers
#define glClearTexSubImage mg_gl_get_api()->ClearTexSubImage
#define glBlendColor mg_gl_get_api()->BlendColor
#define glBindVertexArray mg_gl_get_api()->BindVertexArray
#define glClearBufferfv mg_gl_get_api()->ClearBufferfv
#define glTexSubImage1D mg_gl_get_api()->TexSubImage1D
#define glVertexAttribI1ui mg_gl_get_api()->VertexAttribI1ui
#define glGetBooleani_v mg_gl_get_api()->GetBooleani_v
#define glGetActiveUniformsiv mg_gl_get_api()->GetActiveUniformsiv
#define glUniform2uiv mg_gl_get_api()->Uniform2uiv
#define glGetSubroutineIndex mg_gl_get_api()->GetSubroutineIndex
#define glBeginConditionalRender mg_gl_get_api()->BeginConditionalRender
#define glGetFramebufferAttachmentParameteriv mg_gl_get_api()->GetFramebufferAttachmentParameteriv
#define glVertexAttribI4uiv mg_gl_get_api()->VertexAttribI4uiv
#define glViewportArrayv mg_gl_get_api()->ViewportArrayv
#define glUniform3f mg_gl_get_api()->Uniform3f
#define glVertexAttrib4d mg_gl_get_api()->VertexAttrib4d
#define glGetQueryiv mg_gl_get_api()->GetQueryiv
#define glCopyBufferSubData mg_gl_get_api()->CopyBufferSubData
#define glDrawTransformFeedbackStream mg_gl_get_api()->DrawTransformFeedbackStream
#define glGetPointerv mg_gl_get_api()->GetPointerv
#define glVertexAttribPointer mg_gl_get_api()->VertexAttribPointer
#define glGetActiveUniform mg_gl_get_api()->GetActiveUniform
#define glUniform3uiv mg_gl_get_api()->Uniform3uiv
#define glGetBufferParameteri64v mg_gl_get_api()->GetBufferParameteri64v
#define glTexImage1D mg_gl_get_api()->TexImage1D
#define glProgramUniformMatrix2fv mg_gl_get_api()->ProgramUniformMatrix2fv
#define glDrawTransformFeedback mg_gl_get_api()->DrawTransformFeedback
#define glTextureView mg_gl_get_api()->TextureView
#define glVertexAttrib4sv mg_gl_get_api()->VertexAttrib4sv
#define glGetProgramInfoLog mg_gl_get_api()->GetProgramInfoLog
#define glVertexAttribLPointer mg_gl_get_api()->VertexAttribLPointer
#define glProgramUniform4iv mg_gl_get_api()->ProgramUniform4iv
#define glSamplerParameterf mg_gl_get_api()->SamplerParameterf
#define glGetTexParameterfv mg_gl_get_api()->GetTexParameterfv
#define glGetUniformfv mg_gl_get_api()->GetUniformfv
#define glScissorArrayv mg_gl_get_api()->ScissorArrayv
#define glDebugMessageInsert mg_gl_get_api()->DebugMessageInsert
#define glDrawElementsInstanced mg_gl_get_api()->DrawElementsInstanced
#define glGetDoublev mg_gl_get_api()->GetDoublev
#define glGetInteger64v mg_gl_get_api()->GetInteger64v
#define glDrawArraysIndirect mg_gl_get_api()->DrawArraysIndirect
#define glLineWidth mg_gl_get_api()->LineWidth
#define glVertexAttrib2s mg_gl_get_api()->VertexAttrib2s
#define glGetBooleanv mg_gl_get_api()->GetBooleanv
#define glTransformFeedbackVaryings mg_gl_get_api()->TransformFeedbackVaryings
#define glGetTexLevelParameterfv mg_gl_get_api()->GetTexLevelParameterfv
#define glCopyTexSubImage3D mg_gl_get_api()->CopyTexSubImage3D
#define glViewportIndexedf mg_gl_get_api()->ViewportIndexedf
#define glScissor mg_gl_get_api()->Scissor
#define glTexParameterIiv mg_gl_get_api()->TexParameterIiv
#define glInvalidateTexImage mg_gl_get_api()->InvalidateTexImage
#define glBeginTransformFeedback mg_gl_get_api()->BeginTransformFeedback
#define glDrawTransformFeedbackStreamInstanced mg_gl_get_api()->DrawTransformFeedbackStreamInstanced
#define glGetQueryObjectuiv mg_gl_get_api()->GetQueryObjectuiv
#define glUniformMatrix2dv mg_gl_get_api()->UniformMatrix2dv
#define glColorMask mg_gl_get_api()->ColorMask
#define glTexImage2DMultisample mg_gl_get_api()->TexImage2DMultisample
#define glFramebufferTexture3D mg_gl_get_api()->FramebufferTexture3D
#define glGetVertexAttribIiv mg_gl_get_api()->GetVertexAttribIiv
#define glVertexAttribL3d mg_gl_get_api()->VertexAttribL3d
#define glVertexAttrib1f mg_gl_get_api()->VertexAttrib1f
#define glGetTransformFeedbackVarying mg_gl_get_api()->GetTransformFeedbackVarying
#define glIsShader mg_gl_get_api()->IsShader
#define glClearBufferfi mg_gl_get_api()->ClearBufferfi
#define glValidateProgram mg_gl_get_api()->ValidateProgram
#define glProgramUniform2f mg_gl_get_api()->ProgramUniform2f
#define glGetnUniformfv mg_gl_get_api()->GetnUniformfv
#define glTexImage3DMultisample mg_gl_get_api()->TexImage3DMultisample
#define glFrontFace mg_gl_get_api()->FrontFace
#define glVertexAttribI2iv mg_gl_get_api()->VertexAttribI2iv
#define glRenderbufferStorage mg_gl_get_api()->RenderbufferStorage
#define glProgramUniform4dv mg_gl_get_api()->ProgramUniform4dv
#define glGetShaderSource mg_gl_get_api()->GetShaderSource
#define glGetVertexAttribdv mg_gl_get_api()->GetVertexAttribdv
#define glPrimitiveRestartIndex mg_gl_get_api()->PrimitiveRestartIndex
#define glUnmapBuffer mg_gl_get_api()->UnmapBuffer
#define glVertexAttribP2uiv mg_gl_get_api()->VertexAttribP2uiv
#define glGetBufferParameteriv mg_gl_get_api()->GetBufferParameteriv
#define glUniformMatrix2x3fv mg_gl_get_api()->UniformMatrix2x3fv
#define glDebugMessageControl mg_gl_get_api()->DebugMessageControl
#define glPixelStoref mg_gl_get_api()->PixelStoref
#define glProgramUniformMatrix3x2fv mg_gl_get_api()->ProgramUniformMatrix3x2fv
#define glGetnUniformiv mg_gl_get_api()->GetnUniformiv
#define glGetIntegeri_v mg_gl_get_api()->GetIntegeri_v
#define glVertexAttribL4d mg_gl_get_api()->VertexAttribL4d
#define glReadnPixels mg_gl_get_api()->ReadnPixels
#define glUseProgram mg_gl_get_api()->UseProgram
#define glGetActiveSubroutineUniformiv mg_gl_get_api()->GetActiveSubroutineUniformiv
#define glDisable mg_gl_get_api()->Disable
#define glCullFace mg_gl_get_api()->CullFace
#define glGetVertexAttribiv mg_gl_get_api()->GetVertexAttribiv
#define glVertexAttribI4iv mg_gl_get_api()->VertexAttribI4iv
#define glViewport mg_gl_get_api()->Viewport
#define glAttachShader mg_gl_get_api()->AttachShader
#define glProgramBinary mg_gl_get_api()->ProgramBinary
#define glDepthRange mg_gl_get_api()->DepthRange
#define glProgramUniformMatrix3x2dv mg_gl_get_api()->ProgramUniformMatrix3x2dv
#define glProgramUniform3dv mg_gl_get_api()->ProgramUniform3dv
#define glFramebufferParameteri mg_gl_get_api()->FramebufferParameteri
#define glDrawBuffers mg_gl_get_api()->DrawBuffers
#define glVertexAttribI3i mg_gl_get_api()->VertexAttribI3i
#define glVertexAttribL1d mg_gl_get_api()->VertexAttribL1d
#define glBlendBarrier mg_gl_get_api()->BlendBarrier
#define glGetVertexAttribPointerv mg_gl_get_api()->GetVertexAttribPointerv
#define glUniform4uiv mg_gl_get_api()->Uniform4uiv
#define glBeginQuery mg_gl_get_api()->BeginQuery
#define glEndConditionalRender mg_gl_get_api()->EndConditionalRender
#define glShaderStorageBlockBinding mg_gl_get_api()->ShaderStorageBlockBinding
#define glGetVertexAttribIuiv mg_gl_get_api()->GetVertexAttribIuiv
#define glBindBufferRange mg_gl_get_api()->BindBufferRange
#define glCopyTexSubImage1D mg_gl_get_api()->CopyTexSubImage1D
#define glVertexAttrib3s mg_gl_get_api()->VertexAttrib3s
#define glMapBufferRange mg_gl_get_api()->MapBufferRange
#define glProgramUniform4ui mg_gl_get_api()->ProgramUniform4ui
#define glInvalidateSubFramebuffer mg_gl_get_api()->InvalidateSubFramebuffer
#define glScissorIndexed mg_gl_get_api()->ScissorIndexed
#define glDeleteSync mg_gl_get_api()->DeleteSync
#define glVertexAttribP4uiv mg_gl_get_api()->VertexAttribP4uiv
#define glEnableVertexAttribArray mg_gl_get_api()->EnableVertexAttribArray
#define glCompressedTexSubImage2D mg_gl_get_api()->CompressedTexSubImage2D
#define glGetUniformdv mg_gl_get_api()->GetUniformdv
#define glHint mg_gl_get_api()->Hint
#define glFinish mg_gl_get_api()->Finish
#define glSamplerParameteri mg_gl_get_api()->SamplerParameteri
#define glIsVertexArray mg_gl_get_api()->IsVertexArray
#define glBlendEquation mg_gl_get_api()->BlendEquation
#define glUniform2d mg_gl_get_api()->Uniform2d
#define glIsSync mg_gl_get_api()->IsSync
#define glVertexAttribL4dv mg_gl_get_api()->VertexAttribL4dv
#define glUniformMatrix4x2fv mg_gl_get_api()->UniformMatrix4x2fv
#define glVertexAttribI2i mg_gl_get_api()->VertexAttribI2i
#define glGetAttribLocation mg_gl_get_api()->GetAttribLocation
#define glVertexAttrib3d mg_gl_get_api()->VertexAttrib3d
#define glVertexAttribP3uiv mg_gl_get_api()->VertexAttribP3uiv
#define glGetFloatv mg_gl_get_api()->GetFloatv
#define glFramebufferRenderbuffer mg_gl_get_api()->FramebufferRenderbuffer
#define glGenFramebuffers mg_gl_get_api()->GenFramebuffers
#define glVertexAttrib4s mg_gl_get_api()->VertexAttrib4s
#define glVertexAttribL2dv mg_gl_get_api()->VertexAttribL2dv
#define glUniformMatrix4x3dv mg_gl_get_api()->UniformMatrix4x3dv
#define glGetActiveUniformBlockName mg_gl_get_api()->GetActiveUniformBlockName
#define glCompileShader mg_gl_get_api()->CompileShader
#define glDepthMask mg_gl_get_api()->DepthMask
#define glVertexAttribIPointer mg_gl_get_api()->VertexAttribIPointer
#define glDepthRangeIndexed mg_gl_get_api()->DepthRangeIndexed
#define glProgramUniformMatrix4dv mg_gl_get_api()->ProgramUniformMatrix4dv
#define glUniform3ui mg_gl_get_api()->Uniform3ui
#define glGetSamplerParameterfv mg_gl_get_api()->GetSamplerParameterfv
#define glReadBuffer mg_gl_get_api()->ReadBuffer
#define glVertexAttrib2f mg_gl_get_api()->VertexAttrib2f
#define glVertexAttrib2sv mg_gl_get_api()->VertexAttrib2sv
#define glVertexAttrib4bv mg_gl_get_api()->VertexAttrib4bv
#define glUniform3fv mg_gl_get_api()->Uniform3fv
#define glGetBufferPointerv mg_gl_get_api()->GetBufferPointerv
#define glGetProgramPipelineInfoLog mg_gl_get_api()->GetProgramPipelineInfoLog
#define glUniform2fv mg_gl_get_api()->Uniform2fv
#define glGetError mg_gl_get_api()->GetError
#define glProgramUniformMatrix2dv mg_gl_get_api()->ProgramUniformMatrix2dv
#define glIsEnabled mg_gl_get_api()->IsEnabled
#define glUniform4f mg_gl_get_api()->Uniform4f
#define glDrawArraysInstanced mg_gl_get_api()->DrawArraysInstanced
#define glCompressedTexImage1D mg_gl_get_api()->CompressedTexImage1D
#define glProgramUniformMatrix2x4dv mg_gl_get_api()->ProgramUniformMatrix2x4dv
#define glVertexAttrib3f mg_gl_get_api()->VertexAttrib3f
#define glVertexAttribI1i mg_gl_get_api()->VertexAttribI1i
#define glPointParameterfv mg_gl_get_api()->PointParameterfv
#define glBindTexture mg_gl_get_api()->BindTexture
#define glProgramUniform2fv mg_gl_get_api()->ProgramUniform2fv
#define glBindVertexBuffers mg_gl_get_api()->BindVertexBuffers
#define glIsTransformFeedback mg_gl_get_api()->IsTransformFeedback
#define glProgramUniformMatrix2x3dv mg_gl_get_api()->ProgramUniformMatrix2x3dv
#define glBeginQueryIndexed mg_gl_get_api()->BeginQueryIndexed
#define glSampleCoverage mg_gl_get_api()->SampleCoverage
#define glDepthFunc mg_gl_get_api()->DepthFunc
#define glGenBuffers mg_gl_get_api()->GenBuffers
#define glObjectLabel mg_gl_get_api()->ObjectLabel
#define glUniform1fv mg_gl_get_api()->Uniform1fv
#define glUniform4ui mg_gl_get_api()->Uniform4ui
#define glBindSampler mg_gl_get_api()->BindSampler
#define glDrawArrays mg_gl_get_api()->DrawArrays
#define glDeleteShader mg_gl_get_api()->DeleteShader
#define glMultiDrawArrays mg_gl_get_api()->MultiDrawArrays
#define glProgramUniformMatrix2x3fv mg_gl_get_api()->ProgramUniformMatrix2x3fv
#define glProgramUniform2ui mg_gl_get_api()->ProgramUniform2ui
#define glBufferStorage mg_gl_get_api()->BufferStorage
#define glProgramUniformMatrix4x2fv mg_gl_get_api()->ProgramUniformMatrix4x2fv
#define glDrawElementsBaseVertex mg_gl_get_api()->DrawElementsBaseVertex
#define glProgramUniform3fv mg_gl_get_api()->ProgramUniform3fv
#define glColorMaski mg_gl_get_api()->ColorMaski
#define glGetQueryObjectui64v mg_gl_get_api()->GetQueryObjectui64v
#define glGenVertexArrays mg_gl_get_api()->GenVertexArrays
#define glUniformMatrix3x4dv mg_gl_get_api()->UniformMatrix3x4dv
#define glDeleteFramebuffers mg_gl_get_api()->DeleteFramebuffers
#define glProgramUniform3uiv mg_gl_get_api()->ProgramUniform3uiv
#define glUniform2dv mg_gl_get_api()->Uniform2dv
#define glGetDoublei_v mg_gl_get_api()->GetDoublei_v
#define glUniform3i mg_gl_get_api()->Uniform3i
#define glVertexAttribP2ui mg_gl_get_api()->VertexAttribP2ui
#define glGetIntegerv mg_gl_get_api()->GetIntegerv
#define glClampColor mg_gl_get_api()->ClampColor
#define glTexStorage3DMultisample mg_gl_get_api()->TexStorage3DMultisample
#define glClearBufferSubData mg_gl_get_api()->ClearBufferSubData
#define glCopyImageSubData mg_gl_get_api()->CopyImageSubData
#define glPauseTransformFeedback mg_gl_get_api()->PauseTransformFeedback
#define glUniform3dv mg_gl_get_api()->Uniform3dv
#define glProgramUniform1d mg_gl_get_api()->ProgramUniform1d
#define glGetTexParameterIiv mg_gl_get_api()->GetTexParameterIiv
#define glTexParameterfv mg_gl_get_api()->TexParameterfv
#define glProgramUniformMatrix3x4dv mg_gl_get_api()->ProgramUniformMatrix3x4dv
#define glGetFramebufferParameteriv mg_gl_get_api()->GetFramebufferParameteriv
#define glGenQueries mg_gl_get_api()->GenQueries
#define glDeleteBuffers mg_gl_get_api()->DeleteBuffers
#define glUniform1i mg_gl_get_api()->Uniform1i
#define glProgramUniform4fv mg_gl_get_api()->ProgramUniform4fv
#define glProgramUniform4f mg_gl_get_api()->ProgramUniform4f
#define glShaderBinary mg_gl_get_api()->ShaderBinary
#define glTexParameterf mg_gl_get_api()->TexParameterf
#define glUniformMatrix3x2fv mg_gl_get_api()->UniformMatrix3x2fv
#define glGetTexImage mg_gl_get_api()->GetTexImage
#define glProgramUniformMatrix4fv mg_gl_get_api()->ProgramUniformMatrix4fv
#define glVertexAttrib4f mg_gl_get_api()->VertexAttrib4f
#define glBlendFuncSeparate mg_gl_get_api()->BlendFuncSeparate
#define glGetVertexAttribfv mg_gl_get_api()->GetVertexAttribfv
#define glVertexAttrib4dv mg_gl_get_api()->VertexAttrib4dv
#define glClearDepthf mg_gl_get_api()->ClearDepthf
#define glInvalidateFramebuffer mg_gl_get_api()->InvalidateFramebuffer
#define glPixelStorei mg_gl_get_api()->PixelStorei
#define glActiveTexture mg_gl_get_api()->ActiveTexture
#define glIsProgramPipeline mg_gl_get_api()->IsProgramPipeline
#define glUniform4iv mg_gl_get_api()->Uniform4iv
#define glBindAttribLocation mg_gl_get_api()->BindAttribLocation
#define glGetVertexAttribLdv mg_gl_get_api()->GetVertexAttribLdv
#define glGetProgramResourceName mg_gl_get_api()->GetProgramResourceName
#define glGetInteger64i_v mg_gl_get_api()->GetInteger64i_v
#define glPatchParameterfv mg_gl_get_api()->PatchParameterfv
#define glUniform1dv mg_gl_get_api()->Uniform1dv
#define glVertexAttribI1iv mg_gl_get_api()->VertexAttribI1iv
#define glVertexAttribI3uiv mg_gl_get_api()->VertexAttribI3uiv
#define glVertexAttribI4ubv mg_gl_get_api()->VertexAttribI4ubv
#define glUseProgramStages mg_gl_get_api()->UseProgramStages
#define glIsRenderbuffer mg_gl_get_api()->IsRenderbuffer
#define glBindFragDataLocation mg_gl_get_api()->BindFragDataLocation
#define glUniform1ui mg_gl_get_api()->Uniform1ui
#define glStencilMask mg_gl_get_api()->StencilMask
#define glGetShaderPrecisionFormat mg_gl_get_api()->GetShaderPrecisionFormat
#define glBindImageTexture mg_gl_get_api()->BindImageTexture
#define glVertexAttrib2dv mg_gl_get_api()->VertexAttrib2dv
#define glProgramUniform1iv mg_gl_get_api()->ProgramUniform1iv
#define glGetActiveSubroutineName mg_gl_get_api()->GetActiveSubroutineName
#define glGetFloati_v mg_gl_get_api()->GetFloati_v
#define glRenderbufferStorageMultisample mg_gl_get_api()->RenderbufferStorageMultisample
#define glGetShaderInfoLog mg_gl_get_api()->GetShaderInfoLog
#define glDrawElementsInstancedBaseInstance mg_gl_get_api()->DrawElementsInstancedBaseInstance
#define glVertexAttribP4ui mg_gl_get_api()->VertexAttribP4ui
#define glVertexAttrib4Nusv mg_gl_get_api()->VertexAttrib4Nusv
#define glGetActiveSubroutineUniformName mg_gl_get_api()->GetActiveSubroutineUniformName
#define glUniform1uiv mg_gl_get_api()->Uniform1uiv
#define glUniformMatrix4x2dv mg_gl_get_api()->UniformMatrix4x2dv
#define glVertexAttrib4Nsv mg_gl_get_api()->VertexAttrib4Nsv
#define glVertexAttrib1dv mg_gl_get_api()->VertexAttrib1dv
#define glDeleteTextures mg_gl_get_api()->DeleteTextures
#define glGenerateMipmap mg_gl_get_api()->GenerateMipmap
#define glGenTransformFeedbacks mg_gl_get_api()->GenTransformFeedbacks
#define glWaitSync mg_gl_get_api()->WaitSync
#define glUniform2ui mg_gl_get_api()->Uniform2ui
#define glBlendEquationi mg_gl_get_api()->BlendEquationi
#define glBufferData mg_gl_get_api()->BufferData
#define glGetUniformIndices mg_gl_get_api()->GetUniformIndices
#define glVertexAttrib4fv mg_gl_get_api()->VertexAttrib4fv
#define glResumeTransformFeedback mg_gl_get_api()->ResumeTransformFeedback
#define glBindTransformFeedback mg_gl_get_api()->BindTransformFeedback
#define glVertexAttrib4iv mg_gl_get_api()->VertexAttrib4iv
#define glLinkProgram mg_gl_get_api()->LinkProgram
#define glTexImage3D mg_gl_get_api()->TexImage3D
#define glClear mg_gl_get_api()->Clear
#define glVertexAttrib3fv mg_gl_get_api()->VertexAttrib3fv
#define glFenceSync mg_gl_get_api()->FenceSync
#define glGetActiveAttrib mg_gl_get_api()->GetActiveAttrib
#define glReadPixels mg_gl_get_api()->ReadPixels
#define glProgramUniform2d mg_gl_get_api()->ProgramUniform2d
#define glGetSamplerParameterIiv mg_gl_get_api()->GetSamplerParameterIiv
#define glGetProgramStageiv mg_gl_get_api()->GetProgramStageiv
#define glReleaseShaderCompiler mg_gl_get_api()->ReleaseShaderCompiler
#define glVertexAttribI4usv mg_gl_get_api()->VertexAttribI4usv
#define glGetUniformuiv mg_gl_get_api()->GetUniformuiv
#define glProgramUniform1dv mg_gl_get_api()->ProgramUniform1dv
#define glFramebufferTextureLayer mg_gl_get_api()->FramebufferTextureLayer
#define glProgramUniform3f mg_gl_get_api()->ProgramUniform3f
#define glProgramUniform3ui mg_gl_get_api()->ProgramUniform3ui
#define glDeleteProgram mg_gl_get_api()->DeleteProgram
#define glPolygonOffset mg_gl_get_api()->PolygonOffset
#define glSamplerParameterIiv mg_gl_get_api()->SamplerParameterIiv
#define glUniformMatrix3x2dv mg_gl_get_api()->UniformMatrix3x2dv
#define glUniform4dv mg_gl_get_api()->Uniform4dv
#define glDeleteVertexArrays mg_gl_get_api()->DeleteVertexArrays
#define glGetProgramResourceiv mg_gl_get_api()->GetProgramResourceiv
#define glUniformMatrix2x4fv mg_gl_get_api()->UniformMatrix2x4fv
#define glGetInternalformati64v mg_gl_get_api()->GetInternalformati64v
#define glPointParameteriv mg_gl_get_api()->PointParameteriv
#define glVertexAttribI4sv mg_gl_get_api()->VertexAttribI4sv
#define glDrawTransformFeedbackInstanced mg_gl_get_api()->DrawTransformFeedbackInstanced
#define glGetAttachedShaders mg_gl_get_api()->GetAttachedShaders
#define glVertexAttribI3iv mg_gl_get_api()->VertexAttribI3iv
#define glTexParameterIuiv mg_gl_get_api()->TexParameterIuiv
#define glVertexAttribBinding mg_gl_get_api()->VertexAttribBinding
#define glMultiDrawElements mg_gl_get_api()->MultiDrawElements
#define glTexBuffer mg_gl_get_api()->TexBuffer
#define glGetString mg_gl_get_api()->GetString
#define glGetnUniformuiv mg_gl_get_api()->GetnUniformuiv
#define glDrawElementsInstancedBaseVertexBaseInstance mg_gl_get_api()->DrawElementsInstancedBaseVertexBaseInstance
#define glGetUniformiv mg_gl_get_api()->GetUniformiv
#define glDeleteProgramPipelines mg_gl_get_api()->DeleteProgramPipelines
#define glVertexAttribI2ui mg_gl_get_api()->VertexAttribI2ui
#define glProgramUniform2dv mg_gl_get_api()->ProgramUniform2dv
#define glTexBufferRange mg_gl_get_api()->TexBufferRange
#define glTexParameteri mg_gl_get_api()->TexParameteri
#define glBindBuffersBase mg_gl_get_api()->BindBuffersBase
#define glVertexAttrib2d mg_gl_get_api()->VertexAttrib2d
#define glCreateShader mg_gl_get_api()->CreateShader
#define glBindVertexBuffer mg_gl_get_api()->BindVertexBuffer
#define glFramebufferTexture2D mg_gl_get_api()->FramebufferTexture2D
#define glDepthRangeArrayv mg_gl_get_api()->DepthRangeArrayv
#define glVertexAttrib4Nuiv mg_gl_get_api()->VertexAttrib4Nuiv
#define glUniformMatrix4fv mg_gl_get_api()->UniformMatrix4fv
#define glClearStencil mg_gl_get_api()->ClearStencil
#define glBindBufferBase mg_gl_get_api()->BindBufferBase
#define glInvalidateTexSubImage mg_gl_get_api()->InvalidateTexSubImage
#define glObjectPtrLabel mg_gl_get_api()->ObjectPtrLabel
#define glMinSampleShading mg_gl_get_api()->MinSampleShading
#define glEnable mg_gl_get_api()->Enable
#define glInvalidateBufferData mg_gl_get_api()->InvalidateBufferData
#define glProgramUniformMatrix2x4fv mg_gl_get_api()->ProgramUniformMatrix2x4fv
#define glVertexAttribLFormat mg_gl_get_api()->VertexAttribLFormat
#define glMultiDrawElementsIndirect mg_gl_get_api()->MultiDrawElementsIndirect
#define glGetObjectLabel mg_gl_get_api()->GetObjectLabel
#define glVertexAttribI3ui mg_gl_get_api()->VertexAttribI3ui
#define glFlushMappedBufferRange mg_gl_get_api()->FlushMappedBufferRange
#define glGetUniformBlockIndex mg_gl_get_api()->GetUniformBlockIndex
#define glGetUniformLocation mg_gl_get_api()->GetUniformLocation
#define glGetQueryObjecti64v mg_gl_get_api()->GetQueryObjecti64v
#define glProgramUniform1uiv mg_gl_get_api()->ProgramUniform1uiv
#define glIsSampler mg_gl_get_api()->IsSampler
#define glProgramUniform4uiv mg_gl_get_api()->ProgramUniform4uiv
#define glVertexAttrib4Nubv mg_gl_get_api()->VertexAttrib4Nubv
#define glVertexAttribI4ui mg_gl_get_api()->VertexAttribI4ui
#define glTexSubImage3D mg_gl_get_api()->TexSubImage3D
#define glFramebufferTexture mg_gl_get_api()->FramebufferTexture
#define glPointParameterf mg_gl_get_api()->PointParameterf
#define glGetInternalformativ mg_gl_get_api()->GetInternalformativ
#define glGetActiveUniformBlockiv mg_gl_get_api()->GetActiveUniformBlockiv
#define glDetachShader mg_gl_get_api()->DetachShader
#define glUniform2i mg_gl_get_api()->Uniform2i
#define glProgramParameteri mg_gl_get_api()->ProgramParameteri
#define glGetQueryObjectiv mg_gl_get_api()->GetQueryObjectiv
#define glSamplerParameterfv mg_gl_get_api()->SamplerParameterfv
#define glVertexAttrib4ubv mg_gl_get_api()->VertexAttrib4ubv
#define glClearColor mg_gl_get_api()->ClearColor
#define glTexParameteriv mg_gl_get_api()->TexParameteriv
#define glUniform3d mg_gl_get_api()->Uniform3d
#define glEndTransformFeedback mg_gl_get_api()->EndTransformFeedback
#define glDrawElements mg_gl_get_api()->DrawElements
#define glVertexAttrib4uiv mg_gl_get_api()->VertexAttrib4uiv
#define glMapBuffer mg_gl_get_api()->MapBuffer
#define glGetProgramiv mg_gl_get_api()->GetProgramiv
#define glProgramUniform2uiv mg_gl_get_api()->ProgramUniform2uiv
#define glUniformMatrix4dv mg_gl_get_api()->UniformMatrix4dv
#define glProgramUniform1fv mg_gl_get_api()->ProgramUniform1fv
#define glDrawArraysInstancedBaseInstance mg_gl_get_api()->DrawArraysInstancedBaseInstance
#define glGetQueryIndexediv mg_gl_get_api()->GetQueryIndexediv
#define glStencilFunc mg_gl_get_api()->StencilFunc
#define glGetActiveAtomicCounterBufferiv mg_gl_get_api()->GetActiveAtomicCounterBufferiv
#define glStencilFuncSeparate mg_gl_get_api()->StencilFuncSeparate
#define glStencilOp mg_gl_get_api()->StencilOp
#define glVertexAttribDivisor mg_gl_get_api()->VertexAttribDivisor
#define glDebugMessageCallback mg_gl_get_api()->DebugMessageCallback
#define glVertexAttribP3ui mg_gl_get_api()->VertexAttribP3ui
#define glBindFramebuffer mg_gl_get_api()->BindFramebuffer
#define glIsProgram mg_gl_get_api()->IsProgram
#define glProgramUniform2iv mg_gl_get_api()->ProgramUniform2iv
#define glDeleteSamplers mg_gl_get_api()->DeleteSamplers
#define glCompressedTexSubImage1D mg_gl_get_api()->CompressedTexSubImage1D
#define glFlush mg_gl_get_api()->Flush
#define glDepthRangef mg_gl_get_api()->DepthRangef
#define glMemoryBarrierByRegion mg_gl_get_api()->MemoryBarrierByRegion
#define glGetActiveUniformName mg_gl_get_api()->GetActiveUniformName
#define glGetProgramInterfaceiv mg_gl_get_api()->GetProgramInterfaceiv
#define glDisablei mg_gl_get_api()->Disablei
#define glIsTexture mg_gl_get_api()->IsTexture
#define glUniformMatrix2x3dv mg_gl_get_api()->UniformMatrix2x3dv
#define glBlendFuncSeparatei mg_gl_get_api()->BlendFuncSeparatei
#define glDisableVertexAttribArray mg_gl_get_api()->DisableVertexAttribArray
#define glCompressedTexImage2D mg_gl_get_api()->CompressedTexImage2D
#define glIsQuery mg_gl_get_api()->IsQuery
#define glTexImage2D mg_gl_get_api()->TexImage2D
#define glUniform1f mg_gl_get_api()->Uniform1f
#define glBindRenderbuffer mg_gl_get_api()->BindRenderbuffer
#define glBindFragDataLocationIndexed mg_gl_get_api()->BindFragDataLocationIndexed
#define glVertexAttribI4bv mg_gl_get_api()->VertexAttribI4bv
#define glVertexAttrib1s mg_gl_get_api()->VertexAttrib1s
#define glGetCompressedTexImage mg_gl_get_api()->GetCompressedTexImage
#define glUniformMatrix3fv mg_gl_get_api()->UniformMatrix3fv
#define glStencilOpSeparate mg_gl_get_api()->StencilOpSeparate
#define glProgramUniformMatrix4x3fv mg_gl_get_api()->ProgramUniformMatrix4x3fv
#define glGetStringi mg_gl_get_api()->GetStringi
#define glDispatchCompute mg_gl_get_api()->DispatchCompute
#define glPointParameteri mg_gl_get_api()->PointParameteri
#define glBindImageTextures mg_gl_get_api()->BindImageTextures
#define glDeleteTransformFeedbacks mg_gl_get_api()->DeleteTransformFeedbacks
#define glDrawRangeElementsBaseVertex mg_gl_get_api()->DrawRangeElementsBaseVertex
#define glProgramUniform4d mg_gl_get_api()->ProgramUniform4d
#define glVertexAttribI4i mg_gl_get_api()->VertexAttribI4i
#define glDrawBuffer mg_gl_get_api()->DrawBuffer
#define glTexStorage2D mg_gl_get_api()->TexStorage2D
#define glVertexAttribFormat mg_gl_get_api()->VertexAttribFormat
#define glEndQuery mg_gl_get_api()->EndQuery
#define glPatchParameteri mg_gl_get_api()->PatchParameteri
#define glClearBufferiv mg_gl_get_api()->ClearBufferiv
#define glEndQueryIndexed mg_gl_get_api()->EndQueryIndexed
#define glPointSize mg_gl_get_api()->PointSize
#define glVertexAttrib3dv mg_gl_get_api()->VertexAttrib3dv
#define glUniform4d mg_gl_get_api()->Uniform4d
#define glGenTextures mg_gl_get_api()->GenTextures
#define glGetProgramResourceLocationIndex mg_gl_get_api()->GetProgramResourceLocationIndex
#define glMultiDrawElementsBaseVertex mg_gl_get_api()->MultiDrawElementsBaseVertex
#define glProgramUniform3d mg_gl_get_api()->ProgramUniform3d
#define glGetFragDataIndex mg_gl_get_api()->GetFragDataIndex
#define glClientWaitSync mg_gl_get_api()->ClientWaitSync
#define glDeleteRenderbuffers mg_gl_get_api()->DeleteRenderbuffers
#define glProgramUniform3iv mg_gl_get_api()->ProgramUniform3iv
#define glDrawElementsIndirect mg_gl_get_api()->DrawElementsIndirect
#define glPrimitiveBoundingBox mg_gl_get_api()->PrimitiveBoundingBox
#define glCompressedTexSubImage3D mg_gl_get_api()->CompressedTexSubImage3D
#define glDrawRangeElements mg_gl_get_api()->DrawRangeElements
#define glUniform1iv mg_gl_get_api()->Uniform1iv
#define glGetSamplerParameterIuiv mg_gl_get_api()->GetSamplerParameterIuiv
#define glValidateProgramPipeline mg_gl_get_api()->ValidateProgramPipeline
#define glGetProgramResourceIndex mg_gl_get_api()->GetProgramResourceIndex
#define glVertexAttribI1uiv mg_gl_get_api()->VertexAttribI1uiv
#define glGetTexLevelParameteriv mg_gl_get_api()->GetTexLevelParameteriv
#define glBlitFramebuffer mg_gl_get_api()->BlitFramebuffer
#define glVertexBindingDivisor mg_gl_get_api()->VertexBindingDivisor
#define glGetProgramPipelineiv mg_gl_get_api()->GetProgramPipelineiv
#define glProgramUniform1f mg_gl_get_api()->ProgramUniform1f
#define glIsBuffer mg_gl_get_api()->IsBuffer
#define glGetTexParameteriv mg_gl_get_api()->GetTexParameteriv
#define glUniformMatrix2fv mg_gl_get_api()->UniformMatrix2fv
#endif // __GL_API_H__
