/********************************************************
*
*	@file: gl_api.h
*	@note: auto-generated by glapi.py from gl.xml
*	@date: 16/022023
*
/********************************************************/
#ifndef __GL_API_H__
#define __GL_API_H__

#include"GL/glcorearb.h"
#include"GLES3/gl32.h"

typedef struct mg_gl_api
{
	PFNGLFRAMEBUFFERRENDERBUFFERPROC FramebufferRenderbuffer;
	PFNGLPROGRAMUNIFORM3FPROC ProgramUniform3f;
	PFNGLCOPYTEXIMAGE2DPROC CopyTexImage2D;
	PFNGLPROGRAMUNIFORM3FVPROC ProgramUniform3fv;
	PFNGLQUERYCOUNTERPROC QueryCounter;
	PFNGLPROGRAMPARAMETERIPROC ProgramParameteri;
	PFNGLDEBUGMESSAGECALLBACKPROC DebugMessageCallback;
	PFNGLGETQUERYOBJECTI64VPROC GetQueryObjecti64v;
	PFNGLVERTEXATTRIBL2DVPROC VertexAttribL2dv;
	PFNGLCHECKFRAMEBUFFERSTATUSPROC CheckFramebufferStatus;
	PFNGLGETBUFFERPARAMETERI64VPROC GetBufferParameteri64v;
	PFNGLDELETESYNCPROC DeleteSync;
	PFNGLBINDIMAGETEXTUREPROC BindImageTexture;
	PFNGLDRAWELEMENTSPROC DrawElements;
	PFNGLGENRENDERBUFFERSPROC GenRenderbuffers;
	PFNGLUNIFORMMATRIX2X3FVPROC UniformMatrix2x3fv;
	PFNGLMULTIDRAWARRAYSPROC MultiDrawArrays;
	PFNGLVERTEXATTRIBI4IPROC VertexAttribI4i;
	PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC GetSubroutineUniformLocation;
	PFNGLFRAMEBUFFERPARAMETERIPROC FramebufferParameteri;
	PFNGLBINDBUFFERBASEPROC BindBufferBase;
	PFNGLTEXIMAGE3DPROC TexImage3D;
	PFNGLUNIFORMMATRIX4FVPROC UniformMatrix4fv;
	PFNGLGETVERTEXATTRIBIVPROC GetVertexAttribiv;
	PFNGLTEXSTORAGE1DPROC TexStorage1D;
	PFNGLDELETEPROGRAMPIPELINESPROC DeleteProgramPipelines;
	PFNGLMAPBUFFERPROC MapBuffer;
	PFNGLPOLYGONMODEPROC PolygonMode;
	PFNGLGETPROGRAMBINARYPROC GetProgramBinary;
	PFNGLGETSAMPLERPARAMETERFVPROC GetSamplerParameterfv;
	PFNGLDEPTHFUNCPROC DepthFunc;
	PFNGLVERTEXATTRIB2SVPROC VertexAttrib2sv;
	PFNGLGETPROGRAMRESOURCENAMEPROC GetProgramResourceName;
	PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC ProgramUniformMatrix2x4fv;
	PFNGLUNIFORMMATRIX4DVPROC UniformMatrix4dv;
	PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC ProgramUniformMatrix2x3fv;
	PFNGLPROGRAMUNIFORM4FPROC ProgramUniform4f;
	PFNGLTEXTUREVIEWPROC TextureView;
	PFNGLDEPTHMASKPROC DepthMask;
	PFNGLUNIFORM2UIVPROC Uniform2uiv;
	PFNGLBINDSAMPLERPROC BindSampler;
	PFNGLGETTEXLEVELPARAMETERIVPROC GetTexLevelParameteriv;
	PFNGLVERTEXATTRIB4NUBVPROC VertexAttrib4Nubv;
	PFNGLFRAMEBUFFERTEXTURE3DPROC FramebufferTexture3D;
	PFNGLPROGRAMUNIFORM2DVPROC ProgramUniform2dv;
	PFNGLBINDBUFFERRANGEPROC BindBufferRange;
	PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D;
	PFNGLENDTRANSFORMFEEDBACKPROC EndTransformFeedback;
	PFNGLGETTEXPARAMETERIUIVPROC GetTexParameterIuiv;
	PFNGLGETVERTEXATTRIBIIVPROC GetVertexAttribIiv;
	PFNGLVERTEXATTRIB4SPROC VertexAttrib4s;
	PFNGLGENFRAMEBUFFERSPROC GenFramebuffers;
	PFNGLENABLEPROC Enable;
	PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC GetActiveSubroutineUniformiv;
	PFNGLVERTEXBINDINGDIVISORPROC VertexBindingDivisor;
	PFNGLPOINTPARAMETERFPROC PointParameterf;
	PFNGLUNIFORM3DVPROC Uniform3dv;
	PFNGLSAMPLERPARAMETERIIVPROC SamplerParameterIiv;
	PFNGLDRAWARRAYSPROC DrawArrays;
	PFNGLGETERRORPROC GetError;
	PFNGLINVALIDATEBUFFERDATAPROC InvalidateBufferData;
	PFNGLGETTRANSFORMFEEDBACKVARYINGPROC GetTransformFeedbackVarying;
	PFNGLGETACTIVEATTRIBPROC GetActiveAttrib;
	PFNGLVERTEXATTRIBDIVISORPROC VertexAttribDivisor;
	PFNGLUNIFORM1FPROC Uniform1f;
	PFNGLGETUNIFORMSUBROUTINEUIVPROC GetUniformSubroutineuiv;
	PFNGLPROGRAMUNIFORM1UIVPROC ProgramUniform1uiv;
	PFNGLDRAWRANGEELEMENTSPROC DrawRangeElements;
	PFNGLPUSHDEBUGGROUPPROC PushDebugGroup;
	PFNGLGENPROGRAMPIPELINESPROC GenProgramPipelines;
	PFNGLVIEWPORTPROC Viewport;
	PFNGLGETOBJECTLABELPROC GetObjectLabel;
	PFNGLDISABLEVERTEXATTRIBARRAYPROC DisableVertexAttribArray;
	PFNGLUNIFORM1DPROC Uniform1d;
	PFNGLCLEARBUFFERDATAPROC ClearBufferData;
	PFNGLISQUERYPROC IsQuery;
	PFNGLVERTEXATTRIBI4UIPROC VertexAttribI4ui;
	PFNGLPROGRAMUNIFORM3UIPROC ProgramUniform3ui;
	PFNGLGETUNIFORMIVPROC GetUniformiv;
	PFNGLGETINTEGER64VPROC GetInteger64v;
	PFNGLSCISSORINDEXEDVPROC ScissorIndexedv;
	PFNGLGETINTERNALFORMATI64VPROC GetInternalformati64v;
	PFNGLSHADERSTORAGEBLOCKBINDINGPROC ShaderStorageBlockBinding;
	PFNGLUNIFORM3IVPROC Uniform3iv;
	PFNGLPROGRAMUNIFORM1UIPROC ProgramUniform1ui;
	PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC ProgramUniformMatrix2x4dv;
	PFNGLUNIFORM3UIPROC Uniform3ui;
	PFNGLPOPDEBUGGROUPPROC PopDebugGroup;
	PFNGLSAMPLERPARAMETERIPROC SamplerParameteri;
	PFNGLSTENCILMASKPROC StencilMask;
	PFNGLUNIFORM3FPROC Uniform3f;
	PFNGLPROGRAMUNIFORM4FVPROC ProgramUniform4fv;
	PFNGLGETQUERYOBJECTIVPROC GetQueryObjectiv;
	PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC DrawElementsInstancedBaseVertex;
	PFNGLVIEWPORTARRAYVPROC ViewportArrayv;
	PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC DrawTransformFeedbackStream;
	PFNGLGETPOINTERVPROC GetPointerv;
	PFNGLBEGINTRANSFORMFEEDBACKPROC BeginTransformFeedback;
	PFNGLMEMORYBARRIERPROC MemoryBarrier;
	PFNGLGETPROGRAMPIPELINEIVPROC GetProgramPipelineiv;
	PFNGLBLENDBARRIERPROC BlendBarrier;
	PFNGLGETSAMPLERPARAMETERIVPROC GetSamplerParameteriv;
	PFNGLUNIFORM1IVPROC Uniform1iv;
	PFNGLUNIFORMMATRIX2DVPROC UniformMatrix2dv;
	PFNGLPATCHPARAMETERIPROC PatchParameteri;
	PFNGLPATCHPARAMETERFVPROC PatchParameterfv;
	PFNGLUNIFORMMATRIX4X2DVPROC UniformMatrix4x2dv;
	PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC DrawRangeElementsBaseVertex;
	PFNGLCLEARBUFFERUIVPROC ClearBufferuiv;
	PFNGLVERTEXATTRIBI1IPROC VertexAttribI1i;
	PFNGLOBJECTPTRLABELPROC ObjectPtrLabel;
	PFNGLGETBUFFERPOINTERVPROC GetBufferPointerv;
	PFNGLPOINTPARAMETERIPROC PointParameteri;
	PFNGLCREATESHADERPROGRAMVPROC CreateShaderProgramv;
	PFNGLBLENDFUNCSEPARATEPROC BlendFuncSeparate;
	PFNGLPROGRAMUNIFORM2UIVPROC ProgramUniform2uiv;
	PFNGLVERTEXATTRIB3SVPROC VertexAttrib3sv;
	PFNGLVERTEXATTRIBIPOINTERPROC VertexAttribIPointer;
	PFNGLBINDTEXTUREPROC BindTexture;
	PFNGLVERTEXATTRIB2DVPROC VertexAttrib2dv;
	PFNGLVALIDATEPROGRAMPIPELINEPROC ValidateProgramPipeline;
	PFNGLTEXPARAMETERIVPROC TexParameteriv;
	PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC DrawTransformFeedbackInstanced;
	PFNGLTEXSUBIMAGE2DPROC TexSubImage2D;
	PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC CompressedTexSubImage2D;
	PFNGLCULLFACEPROC CullFace;
	PFNGLINVALIDATESUBFRAMEBUFFERPROC InvalidateSubFramebuffer;
	PFNGLUNIFORM1UIPROC Uniform1ui;
	PFNGLVERTEXATTRIBP2UIVPROC VertexAttribP2uiv;
	PFNGLUNIFORM2DPROC Uniform2d;
	PFNGLENDCONDITIONALRENDERPROC EndConditionalRender;
	PFNGLCOPYTEXIMAGE1DPROC CopyTexImage1D;
	PFNGLSTENCILOPSEPARATEPROC StencilOpSeparate;
	PFNGLISENABLEDIPROC IsEnabledi;
	PFNGLVERTEXATTRIB4NSVPROC VertexAttrib4Nsv;
	PFNGLCLEARBUFFERSUBDATAPROC ClearBufferSubData;
	PFNGLCOLORMASKPROC ColorMask;
	PFNGLDELETEVERTEXARRAYSPROC DeleteVertexArrays;
	PFNGLDELETETEXTURESPROC DeleteTextures;
	PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC DrawTransformFeedbackStreamInstanced;
	PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC ProgramUniformMatrix4x3dv;
	PFNGLISTEXTUREPROC IsTexture;
	PFNGLSAMPLERPARAMETERFPROC SamplerParameterf;
	PFNGLDEBUGMESSAGEINSERTPROC DebugMessageInsert;
	PFNGLUNIFORMMATRIX2FVPROC UniformMatrix2fv;
	PFNGLVERTEXATTRIB4FVPROC VertexAttrib4fv;
	PFNGLATTACHSHADERPROC AttachShader;
	PFNGLGETBOOLEANI_VPROC GetBooleani_v;
	PFNGLVERTEXATTRIBL3DVPROC VertexAttribL3dv;
	PFNGLPROGRAMUNIFORM4DVPROC ProgramUniform4dv;
	PFNGLDRAWTRANSFORMFEEDBACKPROC DrawTransformFeedback;
	PFNGLVERTEXATTRIBI1UIVPROC VertexAttribI1uiv;
	PFNGLMAPBUFFERRANGEPROC MapBufferRange;
	PFNGLRELEASESHADERCOMPILERPROC ReleaseShaderCompiler;
	PFNGLMULTIDRAWELEMENTSPROC MultiDrawElements;
	PFNGLCLEARBUFFERIVPROC ClearBufferiv;
	PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC DrawElementsInstancedBaseVertexBaseInstance;
	PFNGLBINDFRAGDATALOCATIONPROC BindFragDataLocation;
	PFNGLUNIFORMMATRIX2X4DVPROC UniformMatrix2x4dv;
	PFNGLUNIFORM4IVPROC Uniform4iv;
	PFNGLUNIFORM4DPROC Uniform4d;
	PFNGLVERTEXATTRIBI4UBVPROC VertexAttribI4ubv;
	PFNGLGETVERTEXATTRIBFVPROC GetVertexAttribfv;
	PFNGLVERTEXATTRIBI4USVPROC VertexAttribI4usv;
	PFNGLVERTEXATTRIBI3UIPROC VertexAttribI3ui;
	PFNGLLINEWIDTHPROC LineWidth;
	PFNGLGETBUFFERPARAMETERIVPROC GetBufferParameteriv;
	PFNGLGENERATEMIPMAPPROC GenerateMipmap;
	PFNGLGETQUERYOBJECTUI64VPROC GetQueryObjectui64v;
	PFNGLPOLYGONOFFSETPROC PolygonOffset;
	PFNGLDELETEFRAMEBUFFERSPROC DeleteFramebuffers;
	PFNGLSHADERBINARYPROC ShaderBinary;
	PFNGLDELETEQUERIESPROC DeleteQueries;
	PFNGLVERTEXATTRIB4IVPROC VertexAttrib4iv;
	PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC DrawArraysInstancedBaseInstance;
	PFNGLGETSYNCIVPROC GetSynciv;
	PFNGLVERTEXATTRIB3SPROC VertexAttrib3s;
	PFNGLBLENDEQUATIONIPROC BlendEquationi;
	PFNGLGETFLOATVPROC GetFloatv;
	PFNGLBLENDFUNCPROC BlendFunc;
	PFNGLBLENDFUNCSEPARATEIPROC BlendFuncSeparatei;
	PFNGLGETQUERYINDEXEDIVPROC GetQueryIndexediv;
	PFNGLPROGRAMUNIFORMMATRIX2DVPROC ProgramUniformMatrix2dv;
	PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC CompressedTexSubImage1D;
	PFNGLVERTEXATTRIB2SPROC VertexAttrib2s;
	PFNGLDRAWBUFFERSPROC DrawBuffers;
	PFNGLGETPROGRAMINTERFACEIVPROC GetProgramInterfaceiv;
	PFNGLVERTEXATTRIB4NBVPROC VertexAttrib4Nbv;
	PFNGLUNIFORM4IPROC Uniform4i;
	PFNGLISVERTEXARRAYPROC IsVertexArray;
	PFNGLGETDEBUGMESSAGELOGPROC GetDebugMessageLog;
	PFNGLPROGRAMUNIFORM3IVPROC ProgramUniform3iv;
	PFNGLPIXELSTOREIPROC PixelStorei;
	PFNGLPROGRAMUNIFORM1FVPROC ProgramUniform1fv;
	PFNGLVERTEXATTRIBI4UIVPROC VertexAttribI4uiv;
	PFNGLVERTEXATTRIB4NIVPROC VertexAttrib4Niv;
	PFNGLUNIFORMMATRIX4X3FVPROC UniformMatrix4x3fv;
	PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC ProgramUniformMatrix2x3dv;
	PFNGLVERTEXATTRIB4FPROC VertexAttrib4f;
	PFNGLTEXSTORAGE3DPROC TexStorage3D;
	PFNGLBLITFRAMEBUFFERPROC BlitFramebuffer;
	PFNGLFRAMEBUFFERTEXTURE1DPROC FramebufferTexture1D;
	PFNGLVERTEXATTRIB2FPROC VertexAttrib2f;
	PFNGLSAMPLERPARAMETERFVPROC SamplerParameterfv;
	PFNGLPROGRAMBINARYPROC ProgramBinary;
	PFNGLFLUSHPROC Flush;
	PFNGLCLEARDEPTHFPROC ClearDepthf;
	PFNGLTEXSTORAGE3DMULTISAMPLEPROC TexStorage3DMultisample;
	PFNGLPROGRAMUNIFORM1IPROC ProgramUniform1i;
	PFNGLVERTEXATTRIB4NUSVPROC VertexAttrib4Nusv;
	PFNGLENABLEVERTEXATTRIBARRAYPROC EnableVertexAttribArray;
	PFNGLGETACTIVEUNIFORMSIVPROC GetActiveUniformsiv;
	PFNGLVERTEXATTRIB4BVPROC VertexAttrib4bv;
	PFNGLVERTEXATTRIB2DPROC VertexAttrib2d;
	PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC ProgramUniformMatrix3x2dv;
	PFNGLPOINTPARAMETERFVPROC PointParameterfv;
	PFNGLCLIENTWAITSYNCPROC ClientWaitSync;
	PFNGLBINDBUFFERPROC BindBuffer;
	PFNGLBINDFRAGDATALOCATIONINDEXEDPROC BindFragDataLocationIndexed;
	PFNGLGETSHADERIVPROC GetShaderiv;
	PFNGLUSEPROGRAMPROC UseProgram;
	PFNGLVERTEXATTRIB4DVPROC VertexAttrib4dv;
	PFNGLGENQUERIESPROC GenQueries;
	PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog;
	PFNGLPROGRAMUNIFORM2IPROC ProgramUniform2i;
	PFNGLENDQUERYINDEXEDPROC EndQueryIndexed;
	PFNGLISSAMPLERPROC IsSampler;
	PFNGLBINDATTRIBLOCATIONPROC BindAttribLocation;
	PFNGLCLAMPCOLORPROC ClampColor;
	PFNGLUNIFORMMATRIX4X2FVPROC UniformMatrix4x2fv;
	PFNGLLOGICOPPROC LogicOp;
	PFNGLGETINTERNALFORMATIVPROC GetInternalformativ;
	PFNGLUNIFORM1UIVPROC Uniform1uiv;
	PFNGLCREATEPROGRAMPROC CreateProgram;
	PFNGLVERTEXATTRIBL1DPROC VertexAttribL1d;
	PFNGLUNIFORM2FPROC Uniform2f;
	PFNGLBLENDEQUATIONPROC BlendEquation;
	PFNGLFINISHPROC Finish;
	PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC GetFramebufferAttachmentParameteriv;
	PFNGLVERTEXATTRIBFORMATPROC VertexAttribFormat;
	PFNGLVERTEXATTRIBL3DPROC VertexAttribL3d;
	PFNGLGETUNIFORMBLOCKINDEXPROC GetUniformBlockIndex;
	PFNGLCLEARPROC Clear;
	PFNGLGENTEXTURESPROC GenTextures;
	PFNGLGETTEXLEVELPARAMETERFVPROC GetTexLevelParameterfv;
	PFNGLHINTPROC Hint;
	PFNGLUNIFORM4UIPROC Uniform4ui;
	PFNGLVERTEXATTRIB3FVPROC VertexAttrib3fv;
	PFNGLISRENDERBUFFERPROC IsRenderbuffer;
	PFNGLGETATTACHEDSHADERSPROC GetAttachedShaders;
	PFNGLACTIVESHADERPROGRAMPROC ActiveShaderProgram;
	PFNGLUSEPROGRAMSTAGESPROC UseProgramStages;
	PFNGLPROGRAMUNIFORM2FPROC ProgramUniform2f;
	PFNGLGETPROGRAMIVPROC GetProgramiv;
	PFNGLGETUNIFORMINDICESPROC GetUniformIndices;
	PFNGLVERTEXATTRIBP2UIPROC VertexAttribP2ui;
	PFNGLGETACTIVEUNIFORMBLOCKIVPROC GetActiveUniformBlockiv;
	PFNGLCLEARBUFFERFIPROC ClearBufferfi;
	PFNGLVERTEXATTRIB4SVPROC VertexAttrib4sv;
	PFNGLGETSAMPLERPARAMETERIIVPROC GetSamplerParameterIiv;
	PFNGLCOMPILESHADERPROC CompileShader;
	PFNGLTEXSTORAGE2DPROC TexStorage2D;
	PFNGLGETVERTEXATTRIBDVPROC GetVertexAttribdv;
	PFNGLREADPIXELSPROC ReadPixels;
	PFNGLVERTEXATTRIB4NUIVPROC VertexAttrib4Nuiv;
	PFNGLGETSHADERPRECISIONFORMATPROC GetShaderPrecisionFormat;
	PFNGLGETBOOLEANVPROC GetBooleanv;
	PFNGLGETFRAMEBUFFERPARAMETERIVPROC GetFramebufferParameteriv;
	PFNGLVERTEXATTRIBP4UIVPROC VertexAttribP4uiv;
	PFNGLDELETETRANSFORMFEEDBACKSPROC DeleteTransformFeedbacks;
	PFNGLISBUFFERPROC IsBuffer;
	PFNGLPROGRAMUNIFORM3IPROC ProgramUniform3i;
	PFNGLINVALIDATEBUFFERSUBDATAPROC InvalidateBufferSubData;
	PFNGLVERTEXATTRIBI2IPROC VertexAttribI2i;
	PFNGLBLENDEQUATIONSEPARATEIPROC BlendEquationSeparatei;
	PFNGLTEXSUBIMAGE3DPROC TexSubImage3D;
	PFNGLVERTEXATTRIBI4BVPROC VertexAttribI4bv;
	PFNGLUNIFORM1FVPROC Uniform1fv;
	PFNGLPROGRAMUNIFORM4IVPROC ProgramUniform4iv;
	PFNGLPROGRAMUNIFORM2IVPROC ProgramUniform2iv;
	PFNGLGETSHADERSOURCEPROC GetShaderSource;
	PFNGLGETPROGRAMRESOURCEINDEXPROC GetProgramResourceIndex;
	PFNGLUNIFORM2UIPROC Uniform2ui;
	PFNGLOBJECTLABELPROC ObjectLabel;
	PFNGLVERTEXATTRIBLPOINTERPROC VertexAttribLPointer;
	PFNGLPOINTSIZEPROC PointSize;
	PFNGLGETINTEGERVPROC GetIntegerv;
	PFNGLDEPTHRANGEINDEXEDPROC DepthRangeIndexed;
	PFNGLPAUSETRANSFORMFEEDBACKPROC PauseTransformFeedback;
	PFNGLFRAMEBUFFERTEXTUREPROC FramebufferTexture;
	PFNGLSCISSORARRAYVPROC ScissorArrayv;
	PFNGLPROGRAMUNIFORM2UIPROC ProgramUniform2ui;
	PFNGLVERTEXATTRIBP1UIPROC VertexAttribP1ui;
	PFNGLMULTIDRAWELEMENTSINDIRECTPROC MultiDrawElementsIndirect;
	PFNGLUNIFORMMATRIX3X4DVPROC UniformMatrix3x4dv;
	PFNGLGETACTIVEUNIFORMNAMEPROC GetActiveUniformName;
	PFNGLSTENCILOPPROC StencilOp;
	PFNGLGETINTEGERI_VPROC GetIntegeri_v;
	PFNGLSCISSORPROC Scissor;
	PFNGLPROGRAMUNIFORM1IVPROC ProgramUniform1iv;
	PFNGLGETTEXPARAMETERIVPROC GetTexParameteriv;
	PFNGLPROGRAMUNIFORM4UIPROC ProgramUniform4ui;
	PFNGLDISABLEIPROC Disablei;
	PFNGLTEXSTORAGE2DMULTISAMPLEPROC TexStorage2DMultisample;
	PFNGLVERTEXATTRIB1SPROC VertexAttrib1s;
	PFNGLUNIFORMMATRIX3X4FVPROC UniformMatrix3x4fv;
	PFNGLDRAWELEMENTSINDIRECTPROC DrawElementsIndirect;
	PFNGLFRAMEBUFFERTEXTURELAYERPROC FramebufferTextureLayer;
	PFNGLGETTEXPARAMETERFVPROC GetTexParameterfv;
	PFNGLGETQUERYIVPROC GetQueryiv;
	PFNGLGETVERTEXATTRIBLDVPROC GetVertexAttribLdv;
	PFNGLCOMPRESSEDTEXIMAGE3DPROC CompressedTexImage3D;
	PFNGLVERTEXATTRIBIFORMATPROC VertexAttribIFormat;
	PFNGLDRAWELEMENTSBASEVERTEXPROC DrawElementsBaseVertex;
	PFNGLTEXSUBIMAGE1DPROC TexSubImage1D;
	PFNGLBINDVERTEXARRAYPROC BindVertexArray;
	PFNGLPROGRAMUNIFORM3UIVPROC ProgramUniform3uiv;
	PFNGLGETFRAGDATALOCATIONPROC GetFragDataLocation;
	PFNGLBUFFERDATAPROC BufferData;
	PFNGLSTENCILMASKSEPARATEPROC StencilMaskSeparate;
	PFNGLMULTIDRAWARRAYSINDIRECTPROC MultiDrawArraysIndirect;
	PFNGLGETUNIFORMDVPROC GetUniformdv;
	PFNGLPROGRAMUNIFORMMATRIX3DVPROC ProgramUniformMatrix3dv;
	PFNGLVERTEXATTRIB1DVPROC VertexAttrib1dv;
	PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC ProgramUniformMatrix4x2dv;
	PFNGLGETVERTEXATTRIBPOINTERVPROC GetVertexAttribPointerv;
	PFNGLTRANSFORMFEEDBACKVARYINGSPROC TransformFeedbackVaryings;
	PFNGLVERTEXATTRIBI2UIVPROC VertexAttribI2uiv;
	PFNGLVERTEXATTRIB3DPROC VertexAttrib3d;
	PFNGLDETACHSHADERPROC DetachShader;
	PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC ProgramUniformMatrix3x4dv;
	PFNGLGENVERTEXARRAYSPROC GenVertexArrays;
	PFNGLFENCESYNCPROC FenceSync;
	PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC ProgramUniformMatrix4x2fv;
	PFNGLMEMORYBARRIERBYREGIONPROC MemoryBarrierByRegion;
	PFNGLGETNUNIFORMFVPROC GetnUniformfv;
	PFNGLISTRANSFORMFEEDBACKPROC IsTransformFeedback;
	PFNGLBINDRENDERBUFFERPROC BindRenderbuffer;
	PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC ProgramUniformMatrix3x2fv;
	PFNGLPROGRAMUNIFORM1DVPROC ProgramUniform1dv;
	PFNGLGETBUFFERSUBDATAPROC GetBufferSubData;
	PFNGLUNIFORM4FVPROC Uniform4fv;
	PFNGLVERTEXATTRIBL2DPROC VertexAttribL2d;
	PFNGLTEXIMAGE2DPROC TexImage2D;
	PFNGLTEXPARAMETERIPROC TexParameteri;
	PFNGLVERTEXATTRIB4NUBPROC VertexAttrib4Nub;
	PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC GetProgramResourceLocationIndex;
	PFNGLCOPYTEXSUBIMAGE3DPROC CopyTexSubImage3D;
	PFNGLUNIFORMMATRIX2X3DVPROC UniformMatrix2x3dv;
	PFNGLVERTEXATTRIB4UBVPROC VertexAttrib4ubv;
	PFNGLGETINTEGER64I_VPROC GetInteger64i_v;
	PFNGLDELETEPROGRAMPROC DeleteProgram;
	PFNGLCOPYBUFFERSUBDATAPROC CopyBufferSubData;
	PFNGLPRIMITIVEBOUNDINGBOXPROC PrimitiveBoundingBox;
	PFNGLINVALIDATETEXIMAGEPROC InvalidateTexImage;
	PFNGLVERTEXATTRIBP3UIPROC VertexAttribP3ui;
	PFNGLSTENCILFUNCPROC StencilFunc;
	PFNGLCLEARDEPTHPROC ClearDepth;
	PFNGLISSHADERPROC IsShader;
	PFNGLRENDERBUFFERSTORAGEPROC RenderbufferStorage;
	PFNGLVERTEXATTRIB4USVPROC VertexAttrib4usv;
	PFNGLSTENCILFUNCSEPARATEPROC StencilFuncSeparate;
	PFNGLDEPTHRANGEPROC DepthRange;
	PFNGLVERTEXATTRIB4UIVPROC VertexAttrib4uiv;
	PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC DrawElementsInstancedBaseInstance;
	PFNGLUNIFORM2IVPROC Uniform2iv;
	PFNGLGETCOMPRESSEDTEXIMAGEPROC GetCompressedTexImage;
	PFNGLUNIFORM3IPROC Uniform3i;
	PFNGLVIEWPORTINDEXEDFVPROC ViewportIndexedfv;
	PFNGLUNIFORM2DVPROC Uniform2dv;
	PFNGLCOPYIMAGESUBDATAPROC CopyImageSubData;
	PFNGLUNIFORM2FVPROC Uniform2fv;
	PFNGLVERTEXATTRIB1SVPROC VertexAttrib1sv;
	PFNGLVERTEXATTRIBPOINTERPROC VertexAttribPointer;
	PFNGLSHADERSOURCEPROC ShaderSource;
	PFNGLGETPROGRAMRESOURCELOCATIONPROC GetProgramResourceLocation;
	PFNGLREADBUFFERPROC ReadBuffer;
	PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC GetActiveAtomicCounterBufferiv;
	PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog;
	PFNGLPROGRAMUNIFORM2FVPROC ProgramUniform2fv;
	PFNGLGETFLOATI_VPROC GetFloati_v;
	PFNGLGETDOUBLEVPROC GetDoublev;
	PFNGLGETOBJECTPTRLABELPROC GetObjectPtrLabel;
	PFNGLFLUSHMAPPEDBUFFERRANGEPROC FlushMappedBufferRange;
	PFNGLDELETESAMPLERSPROC DeleteSamplers;
	PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation;
	PFNGLCOLORMASKIPROC ColorMaski;
	PFNGLGETMULTISAMPLEFVPROC GetMultisamplefv;
	PFNGLCLEARSTENCILPROC ClearStencil;
	PFNGLISPROGRAMPROC IsProgram;
	PFNGLGETFRAGDATAINDEXPROC GetFragDataIndex;
	PFNGLGENTRANSFORMFEEDBACKSPROC GenTransformFeedbacks;
	PFNGLDELETERENDERBUFFERSPROC DeleteRenderbuffers;
	PFNGLVERTEXATTRIB2FVPROC VertexAttrib2fv;
	PFNGLGETPROGRAMRESOURCEIVPROC GetProgramResourceiv;
	PFNGLVERTEXATTRIBL4DVPROC VertexAttribL4dv;
	PFNGLINVALIDATEFRAMEBUFFERPROC InvalidateFramebuffer;
	PFNGLVERTEXATTRIBLFORMATPROC VertexAttribLFormat;
	PFNGLDISPATCHCOMPUTEINDIRECTPROC DispatchComputeIndirect;
	PFNGLUNIFORM3DPROC Uniform3d;
	PFNGLBINDTRANSFORMFEEDBACKPROC BindTransformFeedback;
	PFNGLGETSAMPLERPARAMETERIUIVPROC GetSamplerParameterIuiv;
	PFNGLVERTEXATTRIBI3UIVPROC VertexAttribI3uiv;
	PFNGLPROGRAMUNIFORM1FPROC ProgramUniform1f;
	PFNGLPROGRAMUNIFORMMATRIX4DVPROC ProgramUniformMatrix4dv;
	PFNGLPROVOKINGVERTEXPROC ProvokingVertex;
	PFNGLUNIFORMMATRIX3DVPROC UniformMatrix3dv;
	PFNGLLINKPROGRAMPROC LinkProgram;
	PFNGLUNIFORMMATRIX3X2DVPROC UniformMatrix3x2dv;
	PFNGLENDQUERYPROC EndQuery;
	PFNGLGETTEXIMAGEPROC GetTexImage;
	PFNGLVERTEXATTRIBI3IVPROC VertexAttribI3iv;
	PFNGLGENBUFFERSPROC GenBuffers;
	PFNGLCOMPRESSEDTEXIMAGE1DPROC CompressedTexImage1D;
	PFNGLVERTEXATTRIBP4UIPROC VertexAttribP4ui;
	PFNGLINVALIDATETEXSUBIMAGEPROC InvalidateTexSubImage;
	PFNGLGETRENDERBUFFERPARAMETERIVPROC GetRenderbufferParameteriv;
	PFNGLTEXIMAGE1DPROC TexImage1D;
	PFNGLISFRAMEBUFFERPROC IsFramebuffer;
	PFNGLVERTEXATTRIBI2IVPROC VertexAttribI2iv;
	PFNGLUNIFORMSUBROUTINESUIVPROC UniformSubroutinesuiv;
	PFNGLBLENDCOLORPROC BlendColor;
	PFNGLBLENDFUNCIPROC BlendFunci;
	PFNGLDRAWELEMENTSINSTANCEDPROC DrawElementsInstanced;
	PFNGLPROGRAMUNIFORMMATRIX2FVPROC ProgramUniformMatrix2fv;
	PFNGLMINSAMPLESHADINGPROC MinSampleShading;
	PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC CompressedTexSubImage3D;
	PFNGLDRAWBUFFERPROC DrawBuffer;
	PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC ProgramUniformMatrix4x3fv;
	PFNGLSAMPLEMASKIPROC SampleMaski;
	PFNGLGETACTIVESUBROUTINENAMEPROC GetActiveSubroutineName;
	PFNGLPROGRAMUNIFORMMATRIX3FVPROC ProgramUniformMatrix3fv;
	PFNGLTEXIMAGE2DMULTISAMPLEPROC TexImage2DMultisample;
	PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC MultiDrawElementsBaseVertex;
	PFNGLUNIFORMMATRIX2X4FVPROC UniformMatrix2x4fv;
	PFNGLGETATTRIBLOCATIONPROC GetAttribLocation;
	PFNGLGETSTRINGIPROC GetStringi;
	PFNGLVERTEXATTRIBBINDINGPROC VertexAttribBinding;
	PFNGLUNIFORMBLOCKBINDINGPROC UniformBlockBinding;
	PFNGLDISABLEPROC Disable;
	PFNGLVERTEXATTRIB1FPROC VertexAttrib1f;
	PFNGLGETSUBROUTINEINDEXPROC GetSubroutineIndex;
	PFNGLISPROGRAMPIPELINEPROC IsProgramPipeline;
	PFNGLUNIFORM2IPROC Uniform2i;
	PFNGLCLEARBUFFERFVPROC ClearBufferfv;
	PFNGLGETQUERYOBJECTUIVPROC GetQueryObjectuiv;
	PFNGLGETDOUBLEI_VPROC GetDoublei_v;
	PFNGLVERTEXATTRIB4DPROC VertexAttrib4d;
	PFNGLUNIFORM1DVPROC Uniform1dv;
	PFNGLDELETESHADERPROC DeleteShader;
	PFNGLGETSTRINGPROC GetString;
	PFNGLVIEWPORTINDEXEDFPROC ViewportIndexedf;
	PFNGLGETNUNIFORMUIVPROC GetnUniformuiv;
	PFNGLUNIFORM1IPROC Uniform1i;
	PFNGLUNIFORM4UIVPROC Uniform4uiv;
	PFNGLTEXPARAMETERIIVPROC TexParameterIiv;
	PFNGLENABLEIPROC Enablei;
	PFNGLCOPYTEXSUBIMAGE1DPROC CopyTexSubImage1D;
	PFNGLBINDFRAMEBUFFERPROC BindFramebuffer;
	PFNGLVALIDATEPROGRAMPROC ValidateProgram;
	PFNGLUNIFORM3UIVPROC Uniform3uiv;
	PFNGLBEGINQUERYPROC BeginQuery;
	PFNGLVERTEXATTRIBI4IVPROC VertexAttribI4iv;
	PFNGLVERTEXATTRIBL4DPROC VertexAttribL4d;
	PFNGLTEXBUFFERPROC TexBuffer;
	PFNGLTEXBUFFERRANGEPROC TexBufferRange;
	PFNGLSAMPLERPARAMETERIUIVPROC SamplerParameterIuiv;
	PFNGLTEXPARAMETERFVPROC TexParameterfv;
	PFNGLUNIFORMMATRIX3FVPROC UniformMatrix3fv;
	PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC GetActiveUniformBlockName;
	PFNGLISENABLEDPROC IsEnabled;
	PFNGLGETUNIFORMUIVPROC GetUniformuiv;
	PFNGLPROGRAMUNIFORMMATRIX4FVPROC ProgramUniformMatrix4fv;
	PFNGLPROGRAMUNIFORM3DVPROC ProgramUniform3dv;
	PFNGLBINDPROGRAMPIPELINEPROC BindProgramPipeline;
	PFNGLPROGRAMUNIFORM4DPROC ProgramUniform4d;
	PFNGLGETACTIVEUNIFORMPROC GetActiveUniform;
	PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC RenderbufferStorageMultisample;
	PFNGLVERTEXATTRIBI1UIPROC VertexAttribI1ui;
	PFNGLSAMPLERPARAMETERIVPROC SamplerParameteriv;
	PFNGLCOPYTEXSUBIMAGE2DPROC CopyTexSubImage2D;
	PFNGLGENSAMPLERSPROC GenSamplers;
	PFNGLDEBUGMESSAGECONTROLPROC DebugMessageControl;
	PFNGLUNMAPBUFFERPROC UnmapBuffer;
	PFNGLDEPTHRANGEFPROC DepthRangef;
	PFNGLSCISSORINDEXEDPROC ScissorIndexed;
	PFNGLUNIFORM4DVPROC Uniform4dv;
	PFNGLGETVERTEXATTRIBIUIVPROC GetVertexAttribIuiv;
	PFNGLVERTEXATTRIBI3IPROC VertexAttribI3i;
	PFNGLTEXPARAMETERIUIVPROC TexParameterIuiv;
	PFNGLVERTEXATTRIBL1DVPROC VertexAttribL1dv;
	PFNGLBLENDEQUATIONSEPARATEPROC BlendEquationSeparate;
	PFNGLGETTEXPARAMETERIIVPROC GetTexParameterIiv;
	PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC ProgramUniformMatrix3x4fv;
	PFNGLCOMPRESSEDTEXIMAGE2DPROC CompressedTexImage2D;
	PFNGLSAMPLECOVERAGEPROC SampleCoverage;
	PFNGLBEGINQUERYINDEXEDPROC BeginQueryIndexed;
	PFNGLDELETEBUFFERSPROC DeleteBuffers;
	PFNGLGETPROGRAMSTAGEIVPROC GetProgramStageiv;
	PFNGLDRAWARRAYSINSTANCEDPROC DrawArraysInstanced;
	PFNGLBEGINCONDITIONALRENDERPROC BeginConditionalRender;
	PFNGLVERTEXATTRIBP1UIVPROC VertexAttribP1uiv;
	PFNGLDISPATCHCOMPUTEPROC DispatchCompute;
	PFNGLISSYNCPROC IsSync;
	PFNGLPIXELSTOREFPROC PixelStoref;
	PFNGLFRONTFACEPROC FrontFace;
	PFNGLVERTEXATTRIBI4SVPROC VertexAttribI4sv;
	PFNGLBUFFERSUBDATAPROC BufferSubData;
	PFNGLVERTEXATTRIB3DVPROC VertexAttrib3dv;
	PFNGLWAITSYNCPROC WaitSync;
	PFNGLUNIFORM3FVPROC Uniform3fv;
	PFNGLPOINTPARAMETERIVPROC PointParameteriv;
	PFNGLPROGRAMUNIFORM1DPROC ProgramUniform1d;
	PFNGLCREATESHADERPROC CreateShader;
	PFNGLGETGRAPHICSRESETSTATUSPROC GetGraphicsResetStatus;
	PFNGLBINDVERTEXBUFFERPROC BindVertexBuffer;
	PFNGLVERTEXATTRIB1DPROC VertexAttrib1d;
	PFNGLGETPROGRAMPIPELINEINFOLOGPROC GetProgramPipelineInfoLog;
	PFNGLGETNUNIFORMIVPROC GetnUniformiv;
	PFNGLVERTEXATTRIBI2UIPROC VertexAttribI2ui;
	PFNGLDRAWARRAYSINDIRECTPROC DrawArraysIndirect;
	PFNGLDEPTHRANGEARRAYVPROC DepthRangeArrayv;
	PFNGLTEXIMAGE3DMULTISAMPLEPROC TexImage3DMultisample;
	PFNGLUNIFORMMATRIX4X3DVPROC UniformMatrix4x3dv;
	PFNGLPROGRAMUNIFORM4IPROC ProgramUniform4i;
	PFNGLVERTEXATTRIB3FPROC VertexAttrib3f;
	PFNGLGETUNIFORMFVPROC GetUniformfv;
	PFNGLVERTEXATTRIB1FVPROC VertexAttrib1fv;
	PFNGLVERTEXATTRIBI1IVPROC VertexAttribI1iv;
	PFNGLTEXPARAMETERFPROC TexParameterf;
	PFNGLRESUMETRANSFORMFEEDBACKPROC ResumeTransformFeedback;
	PFNGLREADNPIXELSPROC ReadnPixels;
	PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC GetActiveSubroutineUniformName;
	PFNGLPROGRAMUNIFORM3DPROC ProgramUniform3d;
	PFNGLUNIFORM4FPROC Uniform4f;
	PFNGLUNIFORMMATRIX3X2FVPROC UniformMatrix3x2fv;
	PFNGLCLEARCOLORPROC ClearColor;
	PFNGLVERTEXATTRIBP3UIVPROC VertexAttribP3uiv;
	PFNGLACTIVETEXTUREPROC ActiveTexture;
	PFNGLPROGRAMUNIFORM4UIVPROC ProgramUniform4uiv;
	PFNGLPRIMITIVERESTARTINDEXPROC PrimitiveRestartIndex;
	PFNGLPROGRAMUNIFORM2DPROC ProgramUniform2d;
} mg_gl_api;

extern mp_thread_local mg_gl_api* __mgGLAPI;

#define glFramebufferRenderbuffer __mgGLAPI->FramebufferRenderbuffer
#define glProgramUniform3f __mgGLAPI->ProgramUniform3f
#define glCopyTexImage2D __mgGLAPI->CopyTexImage2D
#define glProgramUniform3fv __mgGLAPI->ProgramUniform3fv
#define glQueryCounter __mgGLAPI->QueryCounter
#define glProgramParameteri __mgGLAPI->ProgramParameteri
#define glDebugMessageCallback __mgGLAPI->DebugMessageCallback
#define glGetQueryObjecti64v __mgGLAPI->GetQueryObjecti64v
#define glVertexAttribL2dv __mgGLAPI->VertexAttribL2dv
#define glCheckFramebufferStatus __mgGLAPI->CheckFramebufferStatus
#define glGetBufferParameteri64v __mgGLAPI->GetBufferParameteri64v
#define glDeleteSync __mgGLAPI->DeleteSync
#define glBindImageTexture __mgGLAPI->BindImageTexture
#define glDrawElements __mgGLAPI->DrawElements
#define glGenRenderbuffers __mgGLAPI->GenRenderbuffers
#define glUniformMatrix2x3fv __mgGLAPI->UniformMatrix2x3fv
#define glMultiDrawArrays __mgGLAPI->MultiDrawArrays
#define glVertexAttribI4i __mgGLAPI->VertexAttribI4i
#define glGetSubroutineUniformLocation __mgGLAPI->GetSubroutineUniformLocation
#define glFramebufferParameteri __mgGLAPI->FramebufferParameteri
#define glBindBufferBase __mgGLAPI->BindBufferBase
#define glTexImage3D __mgGLAPI->TexImage3D
#define glUniformMatrix4fv __mgGLAPI->UniformMatrix4fv
#define glGetVertexAttribiv __mgGLAPI->GetVertexAttribiv
#define glTexStorage1D __mgGLAPI->TexStorage1D
#define glDeleteProgramPipelines __mgGLAPI->DeleteProgramPipelines
#define glMapBuffer __mgGLAPI->MapBuffer
#define glPolygonMode __mgGLAPI->PolygonMode
#define glGetProgramBinary __mgGLAPI->GetProgramBinary
#define glGetSamplerParameterfv __mgGLAPI->GetSamplerParameterfv
#define glDepthFunc __mgGLAPI->DepthFunc
#define glVertexAttrib2sv __mgGLAPI->VertexAttrib2sv
#define glGetProgramResourceName __mgGLAPI->GetProgramResourceName
#define glProgramUniformMatrix2x4fv __mgGLAPI->ProgramUniformMatrix2x4fv
#define glUniformMatrix4dv __mgGLAPI->UniformMatrix4dv
#define glProgramUniformMatrix2x3fv __mgGLAPI->ProgramUniformMatrix2x3fv
#define glProgramUniform4f __mgGLAPI->ProgramUniform4f
#define glTextureView __mgGLAPI->TextureView
#define glDepthMask __mgGLAPI->DepthMask
#define glUniform2uiv __mgGLAPI->Uniform2uiv
#define glBindSampler __mgGLAPI->BindSampler
#define glGetTexLevelParameteriv __mgGLAPI->GetTexLevelParameteriv
#define glVertexAttrib4Nubv __mgGLAPI->VertexAttrib4Nubv
#define glFramebufferTexture3D __mgGLAPI->FramebufferTexture3D
#define glProgramUniform2dv __mgGLAPI->ProgramUniform2dv
#define glBindBufferRange __mgGLAPI->BindBufferRange
#define glFramebufferTexture2D __mgGLAPI->FramebufferTexture2D
#define glEndTransformFeedback __mgGLAPI->EndTransformFeedback
#define glGetTexParameterIuiv __mgGLAPI->GetTexParameterIuiv
#define glGetVertexAttribIiv __mgGLAPI->GetVertexAttribIiv
#define glVertexAttrib4s __mgGLAPI->VertexAttrib4s
#define glGenFramebuffers __mgGLAPI->GenFramebuffers
#define glEnable __mgGLAPI->Enable
#define glGetActiveSubroutineUniformiv __mgGLAPI->GetActiveSubroutineUniformiv
#define glVertexBindingDivisor __mgGLAPI->VertexBindingDivisor
#define glPointParameterf __mgGLAPI->PointParameterf
#define glUniform3dv __mgGLAPI->Uniform3dv
#define glSamplerParameterIiv __mgGLAPI->SamplerParameterIiv
#define glDrawArrays __mgGLAPI->DrawArrays
#define glGetError __mgGLAPI->GetError
#define glInvalidateBufferData __mgGLAPI->InvalidateBufferData
#define glGetTransformFeedbackVarying __mgGLAPI->GetTransformFeedbackVarying
#define glGetActiveAttrib __mgGLAPI->GetActiveAttrib
#define glVertexAttribDivisor __mgGLAPI->VertexAttribDivisor
#define glUniform1f __mgGLAPI->Uniform1f
#define glGetUniformSubroutineuiv __mgGLAPI->GetUniformSubroutineuiv
#define glProgramUniform1uiv __mgGLAPI->ProgramUniform1uiv
#define glDrawRangeElements __mgGLAPI->DrawRangeElements
#define glPushDebugGroup __mgGLAPI->PushDebugGroup
#define glGenProgramPipelines __mgGLAPI->GenProgramPipelines
#define glViewport __mgGLAPI->Viewport
#define glGetObjectLabel __mgGLAPI->GetObjectLabel
#define glDisableVertexAttribArray __mgGLAPI->DisableVertexAttribArray
#define glUniform1d __mgGLAPI->Uniform1d
#define glClearBufferData __mgGLAPI->ClearBufferData
#define glIsQuery __mgGLAPI->IsQuery
#define glVertexAttribI4ui __mgGLAPI->VertexAttribI4ui
#define glProgramUniform3ui __mgGLAPI->ProgramUniform3ui
#define glGetUniformiv __mgGLAPI->GetUniformiv
#define glGetInteger64v __mgGLAPI->GetInteger64v
#define glScissorIndexedv __mgGLAPI->ScissorIndexedv
#define glGetInternalformati64v __mgGLAPI->GetInternalformati64v
#define glShaderStorageBlockBinding __mgGLAPI->ShaderStorageBlockBinding
#define glUniform3iv __mgGLAPI->Uniform3iv
#define glProgramUniform1ui __mgGLAPI->ProgramUniform1ui
#define glProgramUniformMatrix2x4dv __mgGLAPI->ProgramUniformMatrix2x4dv
#define glUniform3ui __mgGLAPI->Uniform3ui
#define glPopDebugGroup __mgGLAPI->PopDebugGroup
#define glSamplerParameteri __mgGLAPI->SamplerParameteri
#define glStencilMask __mgGLAPI->StencilMask
#define glUniform3f __mgGLAPI->Uniform3f
#define glProgramUniform4fv __mgGLAPI->ProgramUniform4fv
#define glGetQueryObjectiv __mgGLAPI->GetQueryObjectiv
#define glDrawElementsInstancedBaseVertex __mgGLAPI->DrawElementsInstancedBaseVertex
#define glViewportArrayv __mgGLAPI->ViewportArrayv
#define glDrawTransformFeedbackStream __mgGLAPI->DrawTransformFeedbackStream
#define glGetPointerv __mgGLAPI->GetPointerv
#define glBeginTransformFeedback __mgGLAPI->BeginTransformFeedback
#define glMemoryBarrier __mgGLAPI->MemoryBarrier
#define glGetProgramPipelineiv __mgGLAPI->GetProgramPipelineiv
#define glBlendBarrier __mgGLAPI->BlendBarrier
#define glGetSamplerParameteriv __mgGLAPI->GetSamplerParameteriv
#define glUniform1iv __mgGLAPI->Uniform1iv
#define glUniformMatrix2dv __mgGLAPI->UniformMatrix2dv
#define glPatchParameteri __mgGLAPI->PatchParameteri
#define glPatchParameterfv __mgGLAPI->PatchParameterfv
#define glUniformMatrix4x2dv __mgGLAPI->UniformMatrix4x2dv
#define glDrawRangeElementsBaseVertex __mgGLAPI->DrawRangeElementsBaseVertex
#define glClearBufferuiv __mgGLAPI->ClearBufferuiv
#define glVertexAttribI1i __mgGLAPI->VertexAttribI1i
#define glObjectPtrLabel __mgGLAPI->ObjectPtrLabel
#define glGetBufferPointerv __mgGLAPI->GetBufferPointerv
#define glPointParameteri __mgGLAPI->PointParameteri
#define glCreateShaderProgramv __mgGLAPI->CreateShaderProgramv
#define glBlendFuncSeparate __mgGLAPI->BlendFuncSeparate
#define glProgramUniform2uiv __mgGLAPI->ProgramUniform2uiv
#define glVertexAttrib3sv __mgGLAPI->VertexAttrib3sv
#define glVertexAttribIPointer __mgGLAPI->VertexAttribIPointer
#define glBindTexture __mgGLAPI->BindTexture
#define glVertexAttrib2dv __mgGLAPI->VertexAttrib2dv
#define glValidateProgramPipeline __mgGLAPI->ValidateProgramPipeline
#define glTexParameteriv __mgGLAPI->TexParameteriv
#define glDrawTransformFeedbackInstanced __mgGLAPI->DrawTransformFeedbackInstanced
#define glTexSubImage2D __mgGLAPI->TexSubImage2D
#define glCompressedTexSubImage2D __mgGLAPI->CompressedTexSubImage2D
#define glCullFace __mgGLAPI->CullFace
#define glInvalidateSubFramebuffer __mgGLAPI->InvalidateSubFramebuffer
#define glUniform1ui __mgGLAPI->Uniform1ui
#define glVertexAttribP2uiv __mgGLAPI->VertexAttribP2uiv
#define glUniform2d __mgGLAPI->Uniform2d
#define glEndConditionalRender __mgGLAPI->EndConditionalRender
#define glCopyTexImage1D __mgGLAPI->CopyTexImage1D
#define glStencilOpSeparate __mgGLAPI->StencilOpSeparate
#define glIsEnabledi __mgGLAPI->IsEnabledi
#define glVertexAttrib4Nsv __mgGLAPI->VertexAttrib4Nsv
#define glClearBufferSubData __mgGLAPI->ClearBufferSubData
#define glColorMask __mgGLAPI->ColorMask
#define glDeleteVertexArrays __mgGLAPI->DeleteVertexArrays
#define glDeleteTextures __mgGLAPI->DeleteTextures
#define glDrawTransformFeedbackStreamInstanced __mgGLAPI->DrawTransformFeedbackStreamInstanced
#define glProgramUniformMatrix4x3dv __mgGLAPI->ProgramUniformMatrix4x3dv
#define glIsTexture __mgGLAPI->IsTexture
#define glSamplerParameterf __mgGLAPI->SamplerParameterf
#define glDebugMessageInsert __mgGLAPI->DebugMessageInsert
#define glUniformMatrix2fv __mgGLAPI->UniformMatrix2fv
#define glVertexAttrib4fv __mgGLAPI->VertexAttrib4fv
#define glAttachShader __mgGLAPI->AttachShader
#define glGetBooleani_v __mgGLAPI->GetBooleani_v
#define glVertexAttribL3dv __mgGLAPI->VertexAttribL3dv
#define glProgramUniform4dv __mgGLAPI->ProgramUniform4dv
#define glDrawTransformFeedback __mgGLAPI->DrawTransformFeedback
#define glVertexAttribI1uiv __mgGLAPI->VertexAttribI1uiv
#define glMapBufferRange __mgGLAPI->MapBufferRange
#define glReleaseShaderCompiler __mgGLAPI->ReleaseShaderCompiler
#define glMultiDrawElements __mgGLAPI->MultiDrawElements
#define glClearBufferiv __mgGLAPI->ClearBufferiv
#define glDrawElementsInstancedBaseVertexBaseInstance __mgGLAPI->DrawElementsInstancedBaseVertexBaseInstance
#define glBindFragDataLocation __mgGLAPI->BindFragDataLocation
#define glUniformMatrix2x4dv __mgGLAPI->UniformMatrix2x4dv
#define glUniform4iv __mgGLAPI->Uniform4iv
#define glUniform4d __mgGLAPI->Uniform4d
#define glVertexAttribI4ubv __mgGLAPI->VertexAttribI4ubv
#define glGetVertexAttribfv __mgGLAPI->GetVertexAttribfv
#define glVertexAttribI4usv __mgGLAPI->VertexAttribI4usv
#define glVertexAttribI3ui __mgGLAPI->VertexAttribI3ui
#define glLineWidth __mgGLAPI->LineWidth
#define glGetBufferParameteriv __mgGLAPI->GetBufferParameteriv
#define glGenerateMipmap __mgGLAPI->GenerateMipmap
#define glGetQueryObjectui64v __mgGLAPI->GetQueryObjectui64v
#define glPolygonOffset __mgGLAPI->PolygonOffset
#define glDeleteFramebuffers __mgGLAPI->DeleteFramebuffers
#define glShaderBinary __mgGLAPI->ShaderBinary
#define glDeleteQueries __mgGLAPI->DeleteQueries
#define glVertexAttrib4iv __mgGLAPI->VertexAttrib4iv
#define glDrawArraysInstancedBaseInstance __mgGLAPI->DrawArraysInstancedBaseInstance
#define glGetSynciv __mgGLAPI->GetSynciv
#define glVertexAttrib3s __mgGLAPI->VertexAttrib3s
#define glBlendEquationi __mgGLAPI->BlendEquationi
#define glGetFloatv __mgGLAPI->GetFloatv
#define glBlendFunc __mgGLAPI->BlendFunc
#define glBlendFuncSeparatei __mgGLAPI->BlendFuncSeparatei
#define glGetQueryIndexediv __mgGLAPI->GetQueryIndexediv
#define glProgramUniformMatrix2dv __mgGLAPI->ProgramUniformMatrix2dv
#define glCompressedTexSubImage1D __mgGLAPI->CompressedTexSubImage1D
#define glVertexAttrib2s __mgGLAPI->VertexAttrib2s
#define glDrawBuffers __mgGLAPI->DrawBuffers
#define glGetProgramInterfaceiv __mgGLAPI->GetProgramInterfaceiv
#define glVertexAttrib4Nbv __mgGLAPI->VertexAttrib4Nbv
#define glUniform4i __mgGLAPI->Uniform4i
#define glIsVertexArray __mgGLAPI->IsVertexArray
#define glGetDebugMessageLog __mgGLAPI->GetDebugMessageLog
#define glProgramUniform3iv __mgGLAPI->ProgramUniform3iv
#define glPixelStorei __mgGLAPI->PixelStorei
#define glProgramUniform1fv __mgGLAPI->ProgramUniform1fv
#define glVertexAttribI4uiv __mgGLAPI->VertexAttribI4uiv
#define glVertexAttrib4Niv __mgGLAPI->VertexAttrib4Niv
#define glUniformMatrix4x3fv __mgGLAPI->UniformMatrix4x3fv
#define glProgramUniformMatrix2x3dv __mgGLAPI->ProgramUniformMatrix2x3dv
#define glVertexAttrib4f __mgGLAPI->VertexAttrib4f
#define glTexStorage3D __mgGLAPI->TexStorage3D
#define glBlitFramebuffer __mgGLAPI->BlitFramebuffer
#define glFramebufferTexture1D __mgGLAPI->FramebufferTexture1D
#define glVertexAttrib2f __mgGLAPI->VertexAttrib2f
#define glSamplerParameterfv __mgGLAPI->SamplerParameterfv
#define glProgramBinary __mgGLAPI->ProgramBinary
#define glFlush __mgGLAPI->Flush
#define glClearDepthf __mgGLAPI->ClearDepthf
#define glTexStorage3DMultisample __mgGLAPI->TexStorage3DMultisample
#define glProgramUniform1i __mgGLAPI->ProgramUniform1i
#define glVertexAttrib4Nusv __mgGLAPI->VertexAttrib4Nusv
#define glEnableVertexAttribArray __mgGLAPI->EnableVertexAttribArray
#define glGetActiveUniformsiv __mgGLAPI->GetActiveUniformsiv
#define glVertexAttrib4bv __mgGLAPI->VertexAttrib4bv
#define glVertexAttrib2d __mgGLAPI->VertexAttrib2d
#define glProgramUniformMatrix3x2dv __mgGLAPI->ProgramUniformMatrix3x2dv
#define glPointParameterfv __mgGLAPI->PointParameterfv
#define glClientWaitSync __mgGLAPI->ClientWaitSync
#define glBindBuffer __mgGLAPI->BindBuffer
#define glBindFragDataLocationIndexed __mgGLAPI->BindFragDataLocationIndexed
#define glGetShaderiv __mgGLAPI->GetShaderiv
#define glUseProgram __mgGLAPI->UseProgram
#define glVertexAttrib4dv __mgGLAPI->VertexAttrib4dv
#define glGenQueries __mgGLAPI->GenQueries
#define glGetProgramInfoLog __mgGLAPI->GetProgramInfoLog
#define glProgramUniform2i __mgGLAPI->ProgramUniform2i
#define glEndQueryIndexed __mgGLAPI->EndQueryIndexed
#define glIsSampler __mgGLAPI->IsSampler
#define glBindAttribLocation __mgGLAPI->BindAttribLocation
#define glClampColor __mgGLAPI->ClampColor
#define glUniformMatrix4x2fv __mgGLAPI->UniformMatrix4x2fv
#define glLogicOp __mgGLAPI->LogicOp
#define glGetInternalformativ __mgGLAPI->GetInternalformativ
#define glUniform1uiv __mgGLAPI->Uniform1uiv
#define glCreateProgram __mgGLAPI->CreateProgram
#define glVertexAttribL1d __mgGLAPI->VertexAttribL1d
#define glUniform2f __mgGLAPI->Uniform2f
#define glBlendEquation __mgGLAPI->BlendEquation
#define glFinish __mgGLAPI->Finish
#define glGetFramebufferAttachmentParameteriv __mgGLAPI->GetFramebufferAttachmentParameteriv
#define glVertexAttribFormat __mgGLAPI->VertexAttribFormat
#define glVertexAttribL3d __mgGLAPI->VertexAttribL3d
#define glGetUniformBlockIndex __mgGLAPI->GetUniformBlockIndex
#define glClear __mgGLAPI->Clear
#define glGenTextures __mgGLAPI->GenTextures
#define glGetTexLevelParameterfv __mgGLAPI->GetTexLevelParameterfv
#define glHint __mgGLAPI->Hint
#define glUniform4ui __mgGLAPI->Uniform4ui
#define glVertexAttrib3fv __mgGLAPI->VertexAttrib3fv
#define glIsRenderbuffer __mgGLAPI->IsRenderbuffer
#define glGetAttachedShaders __mgGLAPI->GetAttachedShaders
#define glActiveShaderProgram __mgGLAPI->ActiveShaderProgram
#define glUseProgramStages __mgGLAPI->UseProgramStages
#define glProgramUniform2f __mgGLAPI->ProgramUniform2f
#define glGetProgramiv __mgGLAPI->GetProgramiv
#define glGetUniformIndices __mgGLAPI->GetUniformIndices
#define glVertexAttribP2ui __mgGLAPI->VertexAttribP2ui
#define glGetActiveUniformBlockiv __mgGLAPI->GetActiveUniformBlockiv
#define glClearBufferfi __mgGLAPI->ClearBufferfi
#define glVertexAttrib4sv __mgGLAPI->VertexAttrib4sv
#define glGetSamplerParameterIiv __mgGLAPI->GetSamplerParameterIiv
#define glCompileShader __mgGLAPI->CompileShader
#define glTexStorage2D __mgGLAPI->TexStorage2D
#define glGetVertexAttribdv __mgGLAPI->GetVertexAttribdv
#define glReadPixels __mgGLAPI->ReadPixels
#define glVertexAttrib4Nuiv __mgGLAPI->VertexAttrib4Nuiv
#define glGetShaderPrecisionFormat __mgGLAPI->GetShaderPrecisionFormat
#define glGetBooleanv __mgGLAPI->GetBooleanv
#define glGetFramebufferParameteriv __mgGLAPI->GetFramebufferParameteriv
#define glVertexAttribP4uiv __mgGLAPI->VertexAttribP4uiv
#define glDeleteTransformFeedbacks __mgGLAPI->DeleteTransformFeedbacks
#define glIsBuffer __mgGLAPI->IsBuffer
#define glProgramUniform3i __mgGLAPI->ProgramUniform3i
#define glInvalidateBufferSubData __mgGLAPI->InvalidateBufferSubData
#define glVertexAttribI2i __mgGLAPI->VertexAttribI2i
#define glBlendEquationSeparatei __mgGLAPI->BlendEquationSeparatei
#define glTexSubImage3D __mgGLAPI->TexSubImage3D
#define glVertexAttribI4bv __mgGLAPI->VertexAttribI4bv
#define glUniform1fv __mgGLAPI->Uniform1fv
#define glProgramUniform4iv __mgGLAPI->ProgramUniform4iv
#define glProgramUniform2iv __mgGLAPI->ProgramUniform2iv
#define glGetShaderSource __mgGLAPI->GetShaderSource
#define glGetProgramResourceIndex __mgGLAPI->GetProgramResourceIndex
#define glUniform2ui __mgGLAPI->Uniform2ui
#define glObjectLabel __mgGLAPI->ObjectLabel
#define glVertexAttribLPointer __mgGLAPI->VertexAttribLPointer
#define glPointSize __mgGLAPI->PointSize
#define glGetIntegerv __mgGLAPI->GetIntegerv
#define glDepthRangeIndexed __mgGLAPI->DepthRangeIndexed
#define glPauseTransformFeedback __mgGLAPI->PauseTransformFeedback
#define glFramebufferTexture __mgGLAPI->FramebufferTexture
#define glScissorArrayv __mgGLAPI->ScissorArrayv
#define glProgramUniform2ui __mgGLAPI->ProgramUniform2ui
#define glVertexAttribP1ui __mgGLAPI->VertexAttribP1ui
#define glMultiDrawElementsIndirect __mgGLAPI->MultiDrawElementsIndirect
#define glUniformMatrix3x4dv __mgGLAPI->UniformMatrix3x4dv
#define glGetActiveUniformName __mgGLAPI->GetActiveUniformName
#define glStencilOp __mgGLAPI->StencilOp
#define glGetIntegeri_v __mgGLAPI->GetIntegeri_v
#define glScissor __mgGLAPI->Scissor
#define glProgramUniform1iv __mgGLAPI->ProgramUniform1iv
#define glGetTexParameteriv __mgGLAPI->GetTexParameteriv
#define glProgramUniform4ui __mgGLAPI->ProgramUniform4ui
#define glDisablei __mgGLAPI->Disablei
#define glTexStorage2DMultisample __mgGLAPI->TexStorage2DMultisample
#define glVertexAttrib1s __mgGLAPI->VertexAttrib1s
#define glUniformMatrix3x4fv __mgGLAPI->UniformMatrix3x4fv
#define glDrawElementsIndirect __mgGLAPI->DrawElementsIndirect
#define glFramebufferTextureLayer __mgGLAPI->FramebufferTextureLayer
#define glGetTexParameterfv __mgGLAPI->GetTexParameterfv
#define glGetQueryiv __mgGLAPI->GetQueryiv
#define glGetVertexAttribLdv __mgGLAPI->GetVertexAttribLdv
#define glCompressedTexImage3D __mgGLAPI->CompressedTexImage3D
#define glVertexAttribIFormat __mgGLAPI->VertexAttribIFormat
#define glDrawElementsBaseVertex __mgGLAPI->DrawElementsBaseVertex
#define glTexSubImage1D __mgGLAPI->TexSubImage1D
#define glBindVertexArray __mgGLAPI->BindVertexArray
#define glProgramUniform3uiv __mgGLAPI->ProgramUniform3uiv
#define glGetFragDataLocation __mgGLAPI->GetFragDataLocation
#define glBufferData __mgGLAPI->BufferData
#define glStencilMaskSeparate __mgGLAPI->StencilMaskSeparate
#define glMultiDrawArraysIndirect __mgGLAPI->MultiDrawArraysIndirect
#define glGetUniformdv __mgGLAPI->GetUniformdv
#define glProgramUniformMatrix3dv __mgGLAPI->ProgramUniformMatrix3dv
#define glVertexAttrib1dv __mgGLAPI->VertexAttrib1dv
#define glProgramUniformMatrix4x2dv __mgGLAPI->ProgramUniformMatrix4x2dv
#define glGetVertexAttribPointerv __mgGLAPI->GetVertexAttribPointerv
#define glTransformFeedbackVaryings __mgGLAPI->TransformFeedbackVaryings
#define glVertexAttribI2uiv __mgGLAPI->VertexAttribI2uiv
#define glVertexAttrib3d __mgGLAPI->VertexAttrib3d
#define glDetachShader __mgGLAPI->DetachShader
#define glProgramUniformMatrix3x4dv __mgGLAPI->ProgramUniformMatrix3x4dv
#define glGenVertexArrays __mgGLAPI->GenVertexArrays
#define glFenceSync __mgGLAPI->FenceSync
#define glProgramUniformMatrix4x2fv __mgGLAPI->ProgramUniformMatrix4x2fv
#define glMemoryBarrierByRegion __mgGLAPI->MemoryBarrierByRegion
#define glGetnUniformfv __mgGLAPI->GetnUniformfv
#define glIsTransformFeedback __mgGLAPI->IsTransformFeedback
#define glBindRenderbuffer __mgGLAPI->BindRenderbuffer
#define glProgramUniformMatrix3x2fv __mgGLAPI->ProgramUniformMatrix3x2fv
#define glProgramUniform1dv __mgGLAPI->ProgramUniform1dv
#define glGetBufferSubData __mgGLAPI->GetBufferSubData
#define glUniform4fv __mgGLAPI->Uniform4fv
#define glVertexAttribL2d __mgGLAPI->VertexAttribL2d
#define glTexImage2D __mgGLAPI->TexImage2D
#define glTexParameteri __mgGLAPI->TexParameteri
#define glVertexAttrib4Nub __mgGLAPI->VertexAttrib4Nub
#define glGetProgramResourceLocationIndex __mgGLAPI->GetProgramResourceLocationIndex
#define glCopyTexSubImage3D __mgGLAPI->CopyTexSubImage3D
#define glUniformMatrix2x3dv __mgGLAPI->UniformMatrix2x3dv
#define glVertexAttrib4ubv __mgGLAPI->VertexAttrib4ubv
#define glGetInteger64i_v __mgGLAPI->GetInteger64i_v
#define glDeleteProgram __mgGLAPI->DeleteProgram
#define glCopyBufferSubData __mgGLAPI->CopyBufferSubData
#define glPrimitiveBoundingBox __mgGLAPI->PrimitiveBoundingBox
#define glInvalidateTexImage __mgGLAPI->InvalidateTexImage
#define glVertexAttribP3ui __mgGLAPI->VertexAttribP3ui
#define glStencilFunc __mgGLAPI->StencilFunc
#define glClearDepth __mgGLAPI->ClearDepth
#define glIsShader __mgGLAPI->IsShader
#define glRenderbufferStorage __mgGLAPI->RenderbufferStorage
#define glVertexAttrib4usv __mgGLAPI->VertexAttrib4usv
#define glStencilFuncSeparate __mgGLAPI->StencilFuncSeparate
#define glDepthRange __mgGLAPI->DepthRange
#define glVertexAttrib4uiv __mgGLAPI->VertexAttrib4uiv
#define glDrawElementsInstancedBaseInstance __mgGLAPI->DrawElementsInstancedBaseInstance
#define glUniform2iv __mgGLAPI->Uniform2iv
#define glGetCompressedTexImage __mgGLAPI->GetCompressedTexImage
#define glUniform3i __mgGLAPI->Uniform3i
#define glViewportIndexedfv __mgGLAPI->ViewportIndexedfv
#define glUniform2dv __mgGLAPI->Uniform2dv
#define glCopyImageSubData __mgGLAPI->CopyImageSubData
#define glUniform2fv __mgGLAPI->Uniform2fv
#define glVertexAttrib1sv __mgGLAPI->VertexAttrib1sv
#define glVertexAttribPointer __mgGLAPI->VertexAttribPointer
#define glShaderSource __mgGLAPI->ShaderSource
#define glGetProgramResourceLocation __mgGLAPI->GetProgramResourceLocation
#define glReadBuffer __mgGLAPI->ReadBuffer
#define glGetActiveAtomicCounterBufferiv __mgGLAPI->GetActiveAtomicCounterBufferiv
#define glGetShaderInfoLog __mgGLAPI->GetShaderInfoLog
#define glProgramUniform2fv __mgGLAPI->ProgramUniform2fv
#define glGetFloati_v __mgGLAPI->GetFloati_v
#define glGetDoublev __mgGLAPI->GetDoublev
#define glGetObjectPtrLabel __mgGLAPI->GetObjectPtrLabel
#define glFlushMappedBufferRange __mgGLAPI->FlushMappedBufferRange
#define glDeleteSamplers __mgGLAPI->DeleteSamplers
#define glGetUniformLocation __mgGLAPI->GetUniformLocation
#define glColorMaski __mgGLAPI->ColorMaski
#define glGetMultisamplefv __mgGLAPI->GetMultisamplefv
#define glClearStencil __mgGLAPI->ClearStencil
#define glIsProgram __mgGLAPI->IsProgram
#define glGetFragDataIndex __mgGLAPI->GetFragDataIndex
#define glGenTransformFeedbacks __mgGLAPI->GenTransformFeedbacks
#define glDeleteRenderbuffers __mgGLAPI->DeleteRenderbuffers
#define glVertexAttrib2fv __mgGLAPI->VertexAttrib2fv
#define glGetProgramResourceiv __mgGLAPI->GetProgramResourceiv
#define glVertexAttribL4dv __mgGLAPI->VertexAttribL4dv
#define glInvalidateFramebuffer __mgGLAPI->InvalidateFramebuffer
#define glVertexAttribLFormat __mgGLAPI->VertexAttribLFormat
#define glDispatchComputeIndirect __mgGLAPI->DispatchComputeIndirect
#define glUniform3d __mgGLAPI->Uniform3d
#define glBindTransformFeedback __mgGLAPI->BindTransformFeedback
#define glGetSamplerParameterIuiv __mgGLAPI->GetSamplerParameterIuiv
#define glVertexAttribI3uiv __mgGLAPI->VertexAttribI3uiv
#define glProgramUniform1f __mgGLAPI->ProgramUniform1f
#define glProgramUniformMatrix4dv __mgGLAPI->ProgramUniformMatrix4dv
#define glProvokingVertex __mgGLAPI->ProvokingVertex
#define glUniformMatrix3dv __mgGLAPI->UniformMatrix3dv
#define glLinkProgram __mgGLAPI->LinkProgram
#define glUniformMatrix3x2dv __mgGLAPI->UniformMatrix3x2dv
#define glEndQuery __mgGLAPI->EndQuery
#define glGetTexImage __mgGLAPI->GetTexImage
#define glVertexAttribI3iv __mgGLAPI->VertexAttribI3iv
#define glGenBuffers __mgGLAPI->GenBuffers
#define glCompressedTexImage1D __mgGLAPI->CompressedTexImage1D
#define glVertexAttribP4ui __mgGLAPI->VertexAttribP4ui
#define glInvalidateTexSubImage __mgGLAPI->InvalidateTexSubImage
#define glGetRenderbufferParameteriv __mgGLAPI->GetRenderbufferParameteriv
#define glTexImage1D __mgGLAPI->TexImage1D
#define glIsFramebuffer __mgGLAPI->IsFramebuffer
#define glVertexAttribI2iv __mgGLAPI->VertexAttribI2iv
#define glUniformSubroutinesuiv __mgGLAPI->UniformSubroutinesuiv
#define glBlendColor __mgGLAPI->BlendColor
#define glBlendFunci __mgGLAPI->BlendFunci
#define glDrawElementsInstanced __mgGLAPI->DrawElementsInstanced
#define glProgramUniformMatrix2fv __mgGLAPI->ProgramUniformMatrix2fv
#define glMinSampleShading __mgGLAPI->MinSampleShading
#define glCompressedTexSubImage3D __mgGLAPI->CompressedTexSubImage3D
#define glDrawBuffer __mgGLAPI->DrawBuffer
#define glProgramUniformMatrix4x3fv __mgGLAPI->ProgramUniformMatrix4x3fv
#define glSampleMaski __mgGLAPI->SampleMaski
#define glGetActiveSubroutineName __mgGLAPI->GetActiveSubroutineName
#define glProgramUniformMatrix3fv __mgGLAPI->ProgramUniformMatrix3fv
#define glTexImage2DMultisample __mgGLAPI->TexImage2DMultisample
#define glMultiDrawElementsBaseVertex __mgGLAPI->MultiDrawElementsBaseVertex
#define glUniformMatrix2x4fv __mgGLAPI->UniformMatrix2x4fv
#define glGetAttribLocation __mgGLAPI->GetAttribLocation
#define glGetStringi __mgGLAPI->GetStringi
#define glVertexAttribBinding __mgGLAPI->VertexAttribBinding
#define glUniformBlockBinding __mgGLAPI->UniformBlockBinding
#define glDisable __mgGLAPI->Disable
#define glVertexAttrib1f __mgGLAPI->VertexAttrib1f
#define glGetSubroutineIndex __mgGLAPI->GetSubroutineIndex
#define glIsProgramPipeline __mgGLAPI->IsProgramPipeline
#define glUniform2i __mgGLAPI->Uniform2i
#define glClearBufferfv __mgGLAPI->ClearBufferfv
#define glGetQueryObjectuiv __mgGLAPI->GetQueryObjectuiv
#define glGetDoublei_v __mgGLAPI->GetDoublei_v
#define glVertexAttrib4d __mgGLAPI->VertexAttrib4d
#define glUniform1dv __mgGLAPI->Uniform1dv
#define glDeleteShader __mgGLAPI->DeleteShader
#define glGetString __mgGLAPI->GetString
#define glViewportIndexedf __mgGLAPI->ViewportIndexedf
#define glGetnUniformuiv __mgGLAPI->GetnUniformuiv
#define glUniform1i __mgGLAPI->Uniform1i
#define glUniform4uiv __mgGLAPI->Uniform4uiv
#define glTexParameterIiv __mgGLAPI->TexParameterIiv
#define glEnablei __mgGLAPI->Enablei
#define glCopyTexSubImage1D __mgGLAPI->CopyTexSubImage1D
#define glBindFramebuffer __mgGLAPI->BindFramebuffer
#define glValidateProgram __mgGLAPI->ValidateProgram
#define glUniform3uiv __mgGLAPI->Uniform3uiv
#define glBeginQuery __mgGLAPI->BeginQuery
#define glVertexAttribI4iv __mgGLAPI->VertexAttribI4iv
#define glVertexAttribL4d __mgGLAPI->VertexAttribL4d
#define glTexBuffer __mgGLAPI->TexBuffer
#define glTexBufferRange __mgGLAPI->TexBufferRange
#define glSamplerParameterIuiv __mgGLAPI->SamplerParameterIuiv
#define glTexParameterfv __mgGLAPI->TexParameterfv
#define glUniformMatrix3fv __mgGLAPI->UniformMatrix3fv
#define glGetActiveUniformBlockName __mgGLAPI->GetActiveUniformBlockName
#define glIsEnabled __mgGLAPI->IsEnabled
#define glGetUniformuiv __mgGLAPI->GetUniformuiv
#define glProgramUniformMatrix4fv __mgGLAPI->ProgramUniformMatrix4fv
#define glProgramUniform3dv __mgGLAPI->ProgramUniform3dv
#define glBindProgramPipeline __mgGLAPI->BindProgramPipeline
#define glProgramUniform4d __mgGLAPI->ProgramUniform4d
#define glGetActiveUniform __mgGLAPI->GetActiveUniform
#define glRenderbufferStorageMultisample __mgGLAPI->RenderbufferStorageMultisample
#define glVertexAttribI1ui __mgGLAPI->VertexAttribI1ui
#define glSamplerParameteriv __mgGLAPI->SamplerParameteriv
#define glCopyTexSubImage2D __mgGLAPI->CopyTexSubImage2D
#define glGenSamplers __mgGLAPI->GenSamplers
#define glDebugMessageControl __mgGLAPI->DebugMessageControl
#define glUnmapBuffer __mgGLAPI->UnmapBuffer
#define glDepthRangef __mgGLAPI->DepthRangef
#define glScissorIndexed __mgGLAPI->ScissorIndexed
#define glUniform4dv __mgGLAPI->Uniform4dv
#define glGetVertexAttribIuiv __mgGLAPI->GetVertexAttribIuiv
#define glVertexAttribI3i __mgGLAPI->VertexAttribI3i
#define glTexParameterIuiv __mgGLAPI->TexParameterIuiv
#define glVertexAttribL1dv __mgGLAPI->VertexAttribL1dv
#define glBlendEquationSeparate __mgGLAPI->BlendEquationSeparate
#define glGetTexParameterIiv __mgGLAPI->GetTexParameterIiv
#define glProgramUniformMatrix3x4fv __mgGLAPI->ProgramUniformMatrix3x4fv
#define glCompressedTexImage2D __mgGLAPI->CompressedTexImage2D
#define glSampleCoverage __mgGLAPI->SampleCoverage
#define glBeginQueryIndexed __mgGLAPI->BeginQueryIndexed
#define glDeleteBuffers __mgGLAPI->DeleteBuffers
#define glGetProgramStageiv __mgGLAPI->GetProgramStageiv
#define glDrawArraysInstanced __mgGLAPI->DrawArraysInstanced
#define glBeginConditionalRender __mgGLAPI->BeginConditionalRender
#define glVertexAttribP1uiv __mgGLAPI->VertexAttribP1uiv
#define glDispatchCompute __mgGLAPI->DispatchCompute
#define glIsSync __mgGLAPI->IsSync
#define glPixelStoref __mgGLAPI->PixelStoref
#define glFrontFace __mgGLAPI->FrontFace
#define glVertexAttribI4sv __mgGLAPI->VertexAttribI4sv
#define glBufferSubData __mgGLAPI->BufferSubData
#define glVertexAttrib3dv __mgGLAPI->VertexAttrib3dv
#define glWaitSync __mgGLAPI->WaitSync
#define glUniform3fv __mgGLAPI->Uniform3fv
#define glPointParameteriv __mgGLAPI->PointParameteriv
#define glProgramUniform1d __mgGLAPI->ProgramUniform1d
#define glCreateShader __mgGLAPI->CreateShader
#define glGetGraphicsResetStatus __mgGLAPI->GetGraphicsResetStatus
#define glBindVertexBuffer __mgGLAPI->BindVertexBuffer
#define glVertexAttrib1d __mgGLAPI->VertexAttrib1d
#define glGetProgramPipelineInfoLog __mgGLAPI->GetProgramPipelineInfoLog
#define glGetnUniformiv __mgGLAPI->GetnUniformiv
#define glVertexAttribI2ui __mgGLAPI->VertexAttribI2ui
#define glDrawArraysIndirect __mgGLAPI->DrawArraysIndirect
#define glDepthRangeArrayv __mgGLAPI->DepthRangeArrayv
#define glTexImage3DMultisample __mgGLAPI->TexImage3DMultisample
#define glUniformMatrix4x3dv __mgGLAPI->UniformMatrix4x3dv
#define glProgramUniform4i __mgGLAPI->ProgramUniform4i
#define glVertexAttrib3f __mgGLAPI->VertexAttrib3f
#define glGetUniformfv __mgGLAPI->GetUniformfv
#define glVertexAttrib1fv __mgGLAPI->VertexAttrib1fv
#define glVertexAttribI1iv __mgGLAPI->VertexAttribI1iv
#define glTexParameterf __mgGLAPI->TexParameterf
#define glResumeTransformFeedback __mgGLAPI->ResumeTransformFeedback
#define glReadnPixels __mgGLAPI->ReadnPixels
#define glGetActiveSubroutineUniformName __mgGLAPI->GetActiveSubroutineUniformName
#define glProgramUniform3d __mgGLAPI->ProgramUniform3d
#define glUniform4f __mgGLAPI->Uniform4f
#define glUniformMatrix3x2fv __mgGLAPI->UniformMatrix3x2fv
#define glClearColor __mgGLAPI->ClearColor
#define glVertexAttribP3uiv __mgGLAPI->VertexAttribP3uiv
#define glActiveTexture __mgGLAPI->ActiveTexture
#define glProgramUniform4uiv __mgGLAPI->ProgramUniform4uiv
#define glPrimitiveRestartIndex __mgGLAPI->PrimitiveRestartIndex
#define glProgramUniform2d __mgGLAPI->ProgramUniform2d
#endif // __GL_API_H__
