/*************************************************************************
*
*  Orca
*  Copyright 2023 Martin Fouilleul and the Orca project contributors
*  See LICENSE.txt for licensing information
*
**************************************************************************/
#include <shlwapi.h> // PathIsRelative()

#include "win32_string_helpers.h"
#include "path.h"

bool oc_path_is_separator(char c)
{
    return (c == '/' || c == '\\');
}

bool oc_path_starts_with_volume_letter(oc_str8 path)
{
    return (path.len > 1
            && path.ptr[1] == ':'
            && ((path.ptr[0] >= 'a' && path.ptr[0] <= 'z')
                || (path.ptr[0] >= 'A' && path.ptr[0] <= 'Z')));
}

oc_str8 oc_path_slice_directory(oc_str8 fullPath)
{
    i64 lastSlashIndex = -1;

    for(i64 i = fullPath.len - 1; i >= 0; i--)
    {
        if(oc_path_is_separator(fullPath.ptr[i]))
        {
            lastSlashIndex = i;
            break;
        }
    }

    oc_str8 directory = { 0 };
    if(lastSlashIndex < 0)
    {
        //NOTE: we didn't find a separator
        if(oc_path_starts_with_volume_letter(fullPath))
        {
            directory = fullPath;
        }
        else
        {
            directory = OC_STR8(".");
        }
    }
    else if(lastSlashIndex == 0)
    {
        directory = oc_path_slice(fullPath, 0, 1);
    }
    else
    {
        directory = oc_str8_slice(fullPath, 0, lastSlashIndex);
    }

    return (directory);
}

oc_str8 oc_path_slice_filename(oc_str8 fullPath)
{
    i64 lastSlashIndex = -1;

    for(i64 i = fullPath.len - 1; i >= 0; i--)
    {
        if(oc_path_is_separator(fullPath.ptr[i]))
        {
            lastSlashIndex = i;
            break;
        }
    }

    if(lastSlashIndex == -1 && oc_path_starts_with_volume_letter(fullPath))
    {
        // trim the drive letter
        lastSlashIndex += 1;
    }

    oc_str8 basename = oc_str8_slice(fullPath, lastSlashIndex + 1, fullPath.len);
    return (basename);
}

oc_str8 oc_path_slice_stem(oc_str8 path)
{
    oc_str8 basename = oc_path_slice_filename(path);
    //NOTE: ignore leading dots
    u64 i = 0;
    for(; i < basename.len; i++)
    {
        if(basename.ptr[i] != '.')
        {
            break;
        }
    }
    //NOTE: now search to the first dot
    for(; i < basename.len; i++)
    {
        if(basename.ptr[i] == '.')
        {
            return oc_str8_slice(basename, 0, i);
        }
    }
    return (oc_str8){ 0 };
}

oc_str8 oc_path_slice_extension(oc_str8 path)
{
    oc_str8 basename = oc_path_slice_filename(path);
    for(u64 i = basename.len; i > 0; i--)
    {
        if(basename.ptr[i] == '.')
        {
            return oc_str8_slice(basename, i, basename.len);
        }
    }
    return (oc_str8){ 0 };
}

oc_str8_list oc_path_split(oc_arena* arena, oc_str8 path)
{
    oc_arena_scope tmp = oc_scratch_begin_next(arena);
    oc_str8_list sep = { 0 };
    oc_str8_list_push(tmp.arena, &sep, OC_STR8("/"));
    oc_str8_list_push(tmp.arena, &sep, OC_STR8("\\"));

    oc_str8_list res = oc_str8_split(arena, path, sep);

    if(path.len && oc_path_is_separator(path.ptr[0]))
    {
        //NOTE: if path is absolute, add the leading slash as the first element
        oc_str8_list_push_front(arena, &res, oc_str8_slice(path, 0, 1));
    }
    else if(oc_path_starts_with_volume_letter(path))
    {
        //NOTE: trim drive letter from first element
        oc_str8_elt* firstElt = oc_list_first_entry(res.list, oc_str8_elt, listElt);
        firstElt->string = oc_path_slice_filename(firstElt->string);

        //NOTE: add drive letter (with or without backslash) as first element
        if(path.len > 2 && (path.ptr[2] == '\\' || path.ptr[2] == '/'))
        {
            oc_str8_list_push_front(arena, oc_str8_slice(path, 0, 3));
        }
        else
        {
            oc_str8_list_push_front(arena, oc_str8_slice(path, 0, 2));
        }
    }

    //NOTE: strip empty elements (which could be generated by consecutive '/')
    oc_list_for_safe(res.list, elt, oc_str8_elt, listElt)
    {
        if(elt->string.len == 0)
        {
            oc_list_remove(&res.list, &elt->listElt);
        }
    }

    oc_scratch_end(tmp);
    return (res);
}

oc_str8 oc_path_join(oc_arena* arena, oc_str8_list elements)
{
    //TODO: check if elements have ending/begining '/' ?
    oc_arena_scope scratch = oc_scratch_begin_next(arena);
    oc_str8_list list = { 0 };
    oc_str8 driveWithouthSlash = { 0 };

    //NOTE: skip empty elements and eliminate redudant slashes
    oc_str8_list_for(elements, elt)
    {
        if(elt->listElt == elements.list.first
           && elt->string.len == 2
           && oc_path_starts_with_volume_letter(elt->string))
        {
            //NOTE: if the first element is a drive letter _without_ a slash or backslash,
            // it specifies a path relative to the current directory on that drive. We must
            // prepend it to the rest of the path _without a slash_
            driveWithouthSlash = elt->string;
        }
        else if(elt->string.len)
        {
            u64 start = 0;
            u64 end = elt->string.len;

            //NOTE: eliminate leading slashes
            while(start < elt->string.len && oc_path_is_separator(elt->string.ptr[start]))
            {
                start++;
            }
            //NOTE: for first element, keep at most 1 leading slash
            if(&elt->listElt == elements.list.first && start != 0)
            {
                start--;
            }

            //NOTE: eliminate trailing slashes
            while(end > start && oc_path_is_separator(elt->string.ptr[end - 1]))
            {
                end--;
            }
            //NOTE: for last element, keep at most 1 trailing slash
            if(&elt->listElt == elements.list.last && end != elt->string.len)
            {
                end++;
            }
            oc_str8_list_push(scratch.arena, &list, oc_str8_slice(elt->string, start, end));
        }
    }
    oc_str8 res = oc_str8_list_collate(arena, list, driveWithouthSlash, OC_STR8("/"), OC_STR8(""));

    oc_scratch_end(scratch);
    return (res);
}

oc_str8 oc_path_append(oc_arena* arena, oc_str8 parent, oc_str8 relPath)
{
    oc_str8 result = { 0 };

    if(parent.len == 0)
    {
        result = oc_str8_push_copy(arena, relPath);
    }
    else if(relPath.len == 0)
    {
        result = oc_str8_push_copy(arena, parent);
    }
    else
    {
        oc_arena_scope tmp = oc_scratch_begin_next(arena);

        oc_str8_list list = { 0 };
        oc_str8_list_push(tmp.arena, &list, parent);
        oc_str8_list_push(tmp.arena, &list, relPath);

        result = oc_path_join(arena, list);

        oc_scratch_end(tmp);
    }
    return (result);
}

oc_str8 oc_path_executable_relative(oc_arena* arena, oc_str8 relPath)
{
    oc_str8_list list = { 0 };
    oc_arena_scope scratch = oc_scratch_begin_next(arena);

    oc_str8 executablePath = oc_path_executable(scratch.arena);
    oc_str8 dirPath = oc_path_slice_directory(executablePath);

    oc_str8 path = oc_path_append(scratch.arena, dirPath, relPath);
    path = oc_path_canonical(arena, path);

    oc_scratch_end(scratch);
    return (path);
}

bool oc_path_is_absolute(oc_str8 path)
{
    oc_arena_scope scratch = oc_scratch_begin();
    oc_str16 pathW = oc_win32_utf8_to_wide(scratch.arena, path);
    bool result = !PathIsRelativeW(pathW.ptr);

    oc_scratch_end(scratch);
    return (result);
}

oc_str8 oc_path_executable(oc_arena* arena)
{
    ///////////////////////////////////////////////////////////////////
    //TODO use wide chars
    ///////////////////////////////////////////////////////////////////

    char* buffer = oc_arena_push_array(arena, char, MAX_PATH + 2);
    int size = GetModuleFileName(NULL, buffer, MAX_PATH + 1);
    //TODO: check for errors...
    oc_str8 path = oc_str8_from_buffer(size, buffer);

    return (path);
}

oc_str8 oc_path_canonical(oc_arena* arena, oc_str8 path)
{
    oc_arena_scope scratch = oc_scratch_begin_next(arena);
    oc_str16 pathW = oc_win32_utf8_to_wide(scratch.arena, path);

    DWORD required_size = GetFullPathNameW(pathW.ptr, 0, NULL, NULL);
    if(required_size == 0)
    {
        oc_log_error("oc_path_canonical: GetFullPathNameW failed to get required buffer size for full path of %.*s",
                     oc_str8_ip(path));
        oc_scratch_end(scratch);
        return path;
    }

    WCHAR* path_buf = oc_arena_push(scratch.arena, required_size);
    DWORD retval = GetFullPathNameW(pathW.ptr, required_size, path_buf, NULL);
    if(retval == 0)
    {
        oc_log_error("oc_path_canonical: GetFullPathNameW failed to get the full path of %.*s",
                     oc_str8_ip(path));
        oc_scratch_end(scratch);
        return path;
    }

    OC_ASSERT(retval < required_size);
    oc_str16 full_path_str16 = { .ptr = path_buf, .len = required_size - 1 };
    oc_str8 result = oc_win32_wide_to_utf8(arena, full_path_str16);

    oc_scratch_end(scratch);

    return (result);
}

oc_str8 oc_path_executable_relative(oc_arena* arena, oc_str8 relPath)
{
    oc_str8_list list = { 0 };
    oc_arena_scope scratch = oc_scratch_begin_next(arena);

    oc_str8 executablePath = oc_path_executable(scratch.arena);
    oc_str8 dirPath = oc_path_slice_directory(executablePath);

    oc_str8 path = oc_path_append(scratch.arena, dirPath, relPath);
    path = oc_path_canonical(arena, path);

    oc_scratch_end(scratch);
    return (path);
}
