(module $test.wasm
  (type (;0;) (func (result i32)))
  (import "test" "test" (func $test (param i32) (result i32)))
  (func $start (type 0) (result i32)
    (i32.const 42)
    (call $test)
    return)
  (memory (;0;) 2)
  (export "memory" (memory 0))
  (export "start" (func $start)))
