name: build-dawn-mac

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-mac:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dawn version
        id: dawn-version
        run: |
          echo "DAWN_COMMIT=$(cat deps/dawn-commit.txt)" >> $GITHUB_OUTPUT
          ARCH=${{ runner.arch }}
          echo "LOWERCASE_ARCH=$(echo $ARCH | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Cache
        id: cache-dawn
        uses: actions/cache@v3
        with:
          path: build/dawn.out
          key: dawn-${{ runner.os }}-${{ runner.arch }}-${{ steps.dawn-version.outputs.DAWN_COMMIT }}

      - name: Build Dawn
        if: steps.cache-dawn.outputs.cache-hit != 'true'
        run: |
          ./orcadev build-dawn --release --parallel 4

      - uses: actions/upload-artifact@v4
        with:
          name: dawn-mac-${{steps.dawn-version.outputs.LOWERCASE_ARCH}}
          path: build/dawn.out
