name: build-all

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-dawn-mac:
    uses: ./.github/workflows/build-dawn-mac.yaml

  build-dawn-win:
    uses: ./.github/workflows/build-dawn-win.yaml

  build-angle-mac:
    uses: ./.github/workflows/build-angle-mac.yaml

  build-angle-win:
    uses: ./.github/workflows/build-angle-win.yaml

  determine-version:
    runs-on: ubuntu-latest
    steps:
      - name: Determine the build version
        run: |
          if [ "${{ inputs.version }}" != '' ] ; then
            echo "version='${{ github.ref_name }}'" >> "$GITHUB_OUTPUT"
          else
            echo "version='${{ inputs.version }}'" >> "$GITHUB_OUTPUT"
          fi

  build-win:
    needs: [build-dawn-win, build-angle-win, determine-version]
    runs-on: windows-2022
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: Copy Dawn
        shell: cmd
        run: |
          xcopy artifact\dawn-windows-x64 build\dawn.out\ /s /y

      - name: Copy Angle
        shell: cmd
        run: |
          xcopy artifact\angle-windows-x64 build\angle.out\ /s /y

      - name: Build
        shell: cmd
        run: |
            zig build -Doptimize=ReleaseFast -Dversion=${{ steps.determine-version.outputs.version }}

      - name: Package
        shell: cmd
        run: |
          zig build -Doptimize=ReleaseFast -Dsdk-path=orca -Dsdk-deps-path=dev-dependencies -Dversion=${{ steps.determine-version.outputs.version }}
          tar --format=ustar -cvzf orca-windows.tar.gz orca
		tar --format=ustar -cvzf dev-dependencies-windows.tar.gz dev-dependencies

      - uses: actions/upload-artifact@v4
        with:
          name: orca-windows
          path: orca-windows.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: dev-dependencies-windows
          path: dev-dependencies-windows.tar.gz

  build-macos-x64:
    needs: [build-dawn-mac, build-angle-mac, determine-version]
    runs-on: macos-13
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: Copy Dawn
        run: |
          mkdir -p build
          cp -r artifact/dawn-mac-x64 build/dawn.out

      - name: Copy Angle
        run: |
          mkdir -p build
          cp -r artifact/angle-mac-x64 build/angle.out

      - name: Build
        run: |
          zig build -Doptimize=ReleaseFast -Dversion=${{ steps.determine-version.outputs.version }}

      - name: Package
        run: |
          zig build -Doptimize=ReleaseFast -Dsdk-path=orca -Dsdk-deps-path=dev-dependencies -Dversion=${{ steps.determine-version.outputs.version }}
          tar --format=ustar -czf orca-mac-x64.tar.gz orca
          tar --format=ustar -czf dev-dependencies-mac-x64.tar.gz dev-dependencies

      - uses: actions/upload-artifact@v4
        with:
          name: orca-mac-x64
          path: orca-mac-x64.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: dev-dependencies-mac-x64
          path: dev-dependencies-mac-x64.tar.gz

  build-macos-arm64:
    needs: [build-dawn-mac, build-angle-mac, determine-version]
    runs-on: macos-14
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: Copy Dawn
        run: |
          mkdir -p build
          cp -r artifact/dawn-mac-arm64 build/dawn.out

      - name: Copy Angle
        run: |
          mkdir -p build
          cp -r artifact/angle-mac-arm64 build/angle.out

      - name: Build
        run: |
          zig build -Doptimize=ReleaseFast -Dversion=${{ steps.determine-version.outputs.version }}

      - name: Package
        run: |
          zig build -Doptimize=ReleaseFast -Dsdk-path=orca -Dsdk-deps-path=dev-dependencies -Dversion=${{ steps.determine-version.outputs.version }}
          tar --format=ustar -czf orca-mac-arm64.tar.gz orca
          tar --format=ustar -czf dev-dependencies-mac-arm64.tar.gz dev-dependencies

      - uses: actions/upload-artifact@v4
        with:
          name: orca-mac-arm64
          path: orca-mac-arm64.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: dev-dependencies-mac-arm64
          path: dev-dependencies-mac-arm64.tar.gz
