name: build-dawn-mac

on:
  workflow_dispatch:
    inputs:
      ignore-cache:
        required: false
        type: string
        default: false
  workflow_call:
    inputs:
      ignore-cache:
        required: false
        type: string
        default: false
        
jobs:
  build-mac:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Dawn version
        id: dawn-version
        run: |
          echo "DAWN_COMMIT=$(zig build print-sha-dawn)" >> $GITHUB_OUTPUT
          ARCH=${{ runner.arch }}
          echo "LOWERCASE_ARCH=$(echo $ARCH | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Cache
        id: cache-dawn
        uses: actions/cache@v3
        if: inputs.ignore-cache != 'true'
        with:
          path: build/dawn.out
          key: dawn-${{ runner.os }}-${{ runner.arch }}-${{ steps.dawn-version.outputs.DAWN_COMMIT }}

      - uses: mlugg/setup-zig@v1
        if: steps.cache-angle.outputs.cache-hit != 'true' || inputs.ignore-cache == 'true' 
        with:
          version: 0.14.0

      - name: Build Dawn
        if: steps.cache-dawn.outputs.cache-hit != 'true' || inputs.ignore-cache == 'true' 
        run: |
          zig build dawn -Doptimize=ReleaseFast

      - uses: actions/upload-artifact@v4
        with:
          name: dawn-mac-${{steps.dawn-version.outputs.LOWERCASE_ARCH}}
          path: build/dawn.out
