name: build-dawn-win

on:
  workflow_dispatch:
    inputs:
      ignore-cache:
        required: false
        type: string
        default: false
  workflow_call:
    inputs:
      ignore-cache:
        required: false
        type: string
        default: false

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - name: crlf
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dawn version
        id: dawn-version
        shell: cmd
        run: |
          @chcp 65001>nul
          zig build print-sha-angle > dawn-commit.txt
          set /p DAWN_COMMIT=<dawn-commit.txt
          echo DAWN_COMMIT=%DAWN_COMMIT% >> %GITHUB_OUTPUT%

      - name: Cache
        id: cache-dawn
        uses: actions/cache@v3
        if: inputs.ignore-cache != 'true'
        with:
          path: build/dawn.out
          key: dawn-${{ runner.os }}-${{ runner.arch }}-${{ steps.dawn-version.outputs.DAWN_COMMIT }}

      - uses: mlugg/setup-zig@v1
        if: steps.cache-angle.outputs.cache-hit != 'true' || inputs.ignore-cache == 'true' 
        with:
          version: 0.14.0

      - name: Build Dawn
        if: steps.cache-dawn.outputs.cache-hit != 'true' || inputs.ignore-cache == 'true' 
        shell: cmd
        run: |
          zig build dawn -Doptimize=ReleaseFast

      - uses: actions/upload-artifact@v4
        with:
          name: dawn-windows-x64
          path: build/dawn.out
