name: build-dawn-win

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dawn version
        id: dawn-version
        shell: cmd
        run: |
          @chcp 65001>nul
          set /p DAWN_COMMIT=<deps/dawn-commit.txt
          echo DAWN_COMMIT=%DAWN_COMMIT% >> %GITHUB_OUTPUT%

      - name: Cache
        id: cache-dawn
        uses: actions/cache@v3
        with:
          path: build/dawn.out
          key: dawn-${{ runner.os }}-${{ runner.arch }}-${{ steps.dawn-version.outputs.DAWN_COMMIT }}

      - name: Build Dawn
        if: steps.cache-dawn.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          orcadev build-dawn --release --parallel 4

      - uses: actions/upload-artifact@v4
        with:
          name: dawn-windows-x64
          path: build/dawn.out
